---
title: 
  "**PSTAT10** Data Science Fundamentals"
subtitle: Summer 2026
author: "John Robin Inston"
image: "assets/pstat10-thumbnail.svg"
date: "2026-07-16"
toc: true
title-block-banner: false
categories: [Current, UCSB, Data Science, Python]

about:
  template: trestles
  image-width: 16em
  image-shape: rounded
  id: hero-heading

---

::: {#hero-heading}
<div class="h1">Welcome to PSTAT10!</div>

My name is [John Inston](about.qmd) and I will be the instructor for this course, I am a 4th year Ph.D. candidate in the Department of Statistics and Applied Probability here at UC Santa Barbara.  Thank you all for taking this course. I hope that you find it both interesting and informative.

This course aims to provide an overview of key concepts in data science and the use of tools for data retrieval, analysis, visualization, and reproducible research in preparation for advanced data science courses.  Topics include an introduction to inference and prediction, principles of measurement, missing data, and notions of causality, statistical traps, and concepts in data ethics and privacy.

#### 🔍 Reference Material

The contents of this course was prepared using past teaching material provided by [Ethan P. Marzpan](https://epm027.github.io) as well as historical course material made available online by the UCSB Department of Statistics and Applied Probability.

:::