---
title: Probability Theory
description: "Summary of topics in probability theory including measure 
theoretic probability, stochastic processes and stochastic calculus."
author: John Robin Inston
date: 2026-08-22
date-modified: 2026-08-22
toc: true
title-block-banner: true
---

## Related Topics

- [[linear-algebra]]
- [[real-analysis]]
- [[measure-theory]]

## Topics

### Foundations 

- [[probability-theory-fundamentals]]
- [[combinatorics]]
- [[random-variable-transformations]]
- [[generating-functions]]

### Measure Theoretic Probability

- Probability Spaces
- Random Variables and Distribution Functions
- Lebesgue Integration
- Expectation 
- Product Measures
- Conditional Probability

### Stochastic Processes

- **Convergence Results:**
  - Convergence of Stochastic Processes
  - Borel-Cantelli Lemma
  - $L_p$ Spaces
  - Uniform Integrability
  - Skorohod's Representation Theorem
  - **Convergence Theorems:**
    - Monotone Convergence Theorem
    - Dominated Convergence Theorem
  - **Limit Theorems:**
    - Law of Large Numbers
    - Central Limit Theorem
- Large Deviations
- [[markov-chains]]
- Branching Processes
  - Galton-Watson Process
- Random Walks
- **Martingale Theory:**
  - Filtrations & Adapted Processes
  - Martingales & Submartingales
  - Martingale Convergence Theorem
  - Optional Stopping Theorem
  - Doob's Decomposition & Inequalities
- Poisson Processes
- Continuous-Time Markov Chains
  - Infiniteseimal Generator
  - Kolmogorov Forward & Backward Equations
  - Birth-Death Processes


### Stochastic Calculus

- Brownian Motion
- Quadratic Variation
- Ito Calculus
- Stochastic Differential Equations
- **Common Stochastic Processes:**
  - Ornstein-Uhlenbeck Process
  - Geometric Brownian Motion
  - Brownian Bridge
  - Cox-Ingersoll-Ross Process

### Probability Distributions

#### Discrete 

- Discrete Uniform Distribution
- Binomial Distribution
- Geometric Distribution
- [[poisson-distribution]]

#### Continuous

- Continuous Uniform Distribution
- Normal Distribution
- Exponential Distribution
- Gamma Distribution
- Beta Distribution
- Cauchy Distribution
- Student's t-Distribution
- Chi-Squared Distribution
- F-Distribution
- Log-Normal Distribution
- Pareto Distribution
- Weibull Distribution
- Laplace Distribution
- Gumbel Distribution
- Rayleigh Distribution
- Maxwell-Boltzmann Distribution
- Dirichlet Distribution

