---
title: "PSTAT100 Data Science and Analysis"
author: "John Robin Inston"
date: "2026-03-16"
date-modified: "2026-03-16"
toc: true
title-block-banner: false
---

## Introduction

This collect of topics serves as the lecture notes for the PSTAT100 Data 
Science and Analysis course taugh at UC Santa Barbara (last taught in Summer 
2026).  In these lecture notes we study fundamental topics in data science and 
the tools we use for data retrieval, analysis, visualization, and reproducible
research in preparation for advanced data science courses.

Throughout these notes we will conduct our data analysis using the 
programming language `python`.  It is assumed throughout this course that you 
have had some experience working in `python` or a similar programming language
such as `R`.  You may use the **Integrated Development Environment (IDE)** of 
your choice but my recommendation would be to use **VSCode** or some branch of 
the repository such as **Positron** or **Cursor**.  If you are unfamiliar with
`python` and require some help with setup I have included some guidance in the
preliminary materials.

## Topics

- **Preliminary Material:**
    - Getting Started with Python
    - Python Fundamentals
    - Linear Algebra
- **Introduction:**
  - Data Science Fundamentals
  - Data Structure
- **Data Exploration:**
  - Data Preparation
  - Visualization
  - Exploratory Data Analysis
- **Probability and Statistics:**
  - Probability Theory Fundamentals
  - Statistics
- **Statistical Models:**
    - Simple Linear Regression
    - Multiple Linear Regression
    - Generalized Linear Models
      - Logistic Regression
      - Poisson Regression
    - Model Selection
      - Regularization
- **Machine Learning Models:**
  - Decision Trees
  - Random Forests
