---
title: 
  "**PSTAT188** Transfer Exploration Seminar"
subtitle: Summer 2026
author: "John Robin Inston"
image: "assets/pstat188-thumbnail.svg"
date: "2026-07-16"
toc: true
title-block-banner: false
categories: [Current, UCSB, Data Science, Python]

about:
  template: trestles
  image-width: 16em
  image-shape: rounded
  id: hero-heading

---

::: {#hero-heading}
<div class="h1">Welcome to PSTAT10!</div>

My name is [John Inston](about.qmd) and I am a 5th year Ph.D. candidate in 
the Department of Statistics and Applied Probability here at UC Santa Barbara.
I am the joint instructor alongside [Prof. Michael Ludkovski]() for PSTAT188 
this summer.  We hope you find this course both interesting and informative.

This course aims to provide an exploration of the field of data science and 
its applications in a variety of domains.  We will cover the fundamentals of 
programming for data science using both R and python, including data manipulation,
visualization and descriptive analysis.  We will also cover the foundational 
concepts of probability theory to prepare students for the PSTAT120 courses 
at UCSB.  

#### 🔍 Reference Material

The contents of this course was prepared using past teaching material provided 
by Prof. Ludkovski and [Prof. Uma Ravat](https://pstat.ucsb.edu/people/faculty/uma-ravat)
as well as historical course material made available online by the 
[UCSB Department of Statistics and Applied Probability](https://www.pstat.ucsb.edu).

:::

## 📚 Material

- **Course Syllabus:**
  - [Syllabus](material/syllabus.pdf)
- **Lecture Notes:**
  - Online lecture notes
- **Course Readings:**
  - [R for Data Science](https://r4ds.had.co.nz/)
  - [R Manuals: An Introduction to R](https://rstudio.github.io/r-manuals/r-intro/)
  - [Tidyverse Styling Guide](https://style.tidyverse.org/)
  - [Quarto Documentation](https://quarto.org/docs/)
  - [Python Documentation](https://docs.python.org/3/)
- **Helpful Resources:**
  - [Downloading R and RStudio](https://posit.co/download/rstudio-desktop/)
  - [Download Quarto.](https://quarto.org/docs/get-started/)
  - [Documentation: Quarto for PDF documents](https://quarto.org/docs/output-formats/pdf-basics.html)
  - [Documentation: Writing math using LaTeX](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

## ✏️ Information

### Teaching Staff

| Name           | Role       | Email                        | Office Hours                      |
|----------------|------------|------------------------------|-----------------------------------|
| Dr Ludkovski   | Instructor | ludkovski@pstat.ucsb.edu     | SH 5520 R 3:15PM - 4:15PM         | 
| John Inston    | Instructor | johninston@ucsb.edu          | SH 5431T W 1:00PM - 4:00PM        |

> For zoom meeting links please check the course Canvas page. 

### Instruction

Course instruction will comprise of **10 lectures** (held twice per week).  

- **Lecture:** 
  - TR 2:00PM - 3:05PM Phelps 1513

### Assessments

There will be **NO final exam** for this course.

Grading will be based on the completion of **weekly assignments** and 
**participation** in class discussions.  Your assignments will be due for 
submission on Canvas each week in PDF form.

### Course Schedule

Please check this schedule regularly throughout the term as it is updated with the latest material and reading suggestions.

| Week | Lecture | Date        | Topics                             | Materials  |
|------|---------|-------------|------------------------------------|------------|
| 1    | 1       | Tues Aug 4  | Welcome to the PSTAT Department    |            |


