project:
  type: website
  output-dir: "docs"

website:
  title: "John Robin Inston"
  navbar:
    left: 
      - text: About
        file: about.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Resume"
        file: resume.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



