project:
  type: website
  output-dir: "docs"

website:
  title: "John Robin Inston"
  favicon: favicon.png
  navbar:
    left: 
      - text: About
        file: about.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "Resume"
        file: resume.qmd
    right:
      - icon: youtube
        href: https://www.youtube.com/@JohnRobinInston
      - icon: twitter-x
        href: https://x.com/John_Inston
      - icon: linkedin
        href: https://www.linkedin.com/in/johninston/
      - icon: github
        href: https://github.com/johnrobininston
  page-footer: "Copyright 2025, John Inston." 


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



