---
title: "PSTAT100"
subtitle: Data Science Concepts and Analysis
author: "John Robin Inston"
date: "2026-03-16"
date-modified: "2026-03-16"
toc: true
title-block-banner: true
categories: [Data Science]
---

## ✏️ Information

This is the page for PSTAT100 Data Science Concepts and Analysis course taught in Spring 2026 at the University of California Santa Barbara.  This course aims to provide an overview of key concepts in data science and the use of tools for data retrieval, analysis, visualization, and reproducible research in preparation for advanced data science courses.  Topics include an introduction to inference and prediction, principles of measurement, missing data, and notions of causality, statistical traps, and concepts in data ethics and privacy.

::: {.callout-important}

### Thanks

The contents of this course was prepared using past teaching material provided by [Ethan P. Marzpan](https://epm027.github.io).

:::

## 📚 Material

My online lecture notes for this course can be found [here](notes.qmd).

Below are links to documents I have prepared for my past sections as well as a collection of additional exercise sheets covering similar questions to those covered in past assignments and exams.  These documents can also be found in the respective course pages on my GitHub.

### Past Teaching Material

- [PSTAT160A Fall 2025 (Prof. Tomoyuki Ichiba)](https://github.com/johnrobininston/pstat160a-fall-2025/tree/main)
- PSTAT160A Winter 2026 (Prof. Vellaisamy Palaniappan)

## 🙏 Thanks!

If you found any of this material helpful consider buying me a coffee but only if you can afford to!  Thank you for visiting this course page. 😊

<div style="text-align: center;">
  <script type="text/javascript" 
          src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" 
          data-name="bmc-button" 
          data-slug="johnrobininston" 
          data-color="#FF5F5F" 
          data-emoji="" 
          data-font="Cookie" 
          data-text="Buy me a coffee! " 
          data-outline-color="#000000" 
          data-font-color="#ffffff" 
          data-coffee-color="#FFDD00">
  </script>
</div>







