---
title: "Implementing Black Scholes and Vasiciek Models in R"
author: "John Robin Inston"
date: "2020-03-05"
categories: [Quantitative Finance, Option Pricing, R]
toc: true
---

## Quick Summary

In this project we investigate the properties of financial stochastic processes. We first consider the implementation of the Black-Scholes model for determining the price of European call options on stock before then utilising the Vasicek model to calculate the future price of bonds. We discuss the background, benefits and drawbacks of both models before conducting our investigation and summarising our findings.

## 1 - Introduction

The Black-Scholes model is a mathematical model developed by the economists Fischer Black, Myron Scholes and Robert Merton which is widely used in the pricing of options contacts. The model assumes that the price of heavily traded assets follows a geometric Brownian motion with constant drift and volatility. When applied to a stock option, the model incorporates the constant price variation of the stock, the time value of money, the option’s strike price, and the time to the option’s expiry.

The Vasicek model is a mathematical model used in financial economics to estimate potential pathways for future interest rate changes. The model states that the movement of interest rates is affected only by random (stochastic) market movements and models interest rate movements as a factor composed of market risk, time, and equilibrium value - where the rate tends to revert towards the mean of those factors over time.

We will first investigate how the price of a European call option - as given by the Black- Scholes model - varies with changes in time, interest rates, strike price and volatility. We will then simulate an Ornstein-Uhlenbeck process and use this to simulate the price of a bond - using the Vasicek model - over a given time period before evaluating the distribution of the simulated prices.

We conduct this project using the programming language R along with the ggplot2, reshape, tidyr and gridExtra packages.

```{r}
#| message: false

# load libraries
library(ggplot2)
library(reshape)
library(tidyr)
library(gridExtra)
```

## 2 - The Black-Scholes Model

The price at time $t_0=0$  of a European call option (‘ECO’) on a stock with strike price $c$, expiry time $t_0$, initial stock price $S_0$, interest rate $\rho$ and volatility $\sigma$ is given by the Black-Scholes (‘BS’) formula. This is given below in Equation 1




