---
title: Affine Function
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Affine Function

In geometry and **affine function** (**affine transformation**, **affine map**)
between two vector spaces consist of a [[linear-algebra|linear transformation]]
followed by a translation. In a geometric setting, these are precisely the
functions that map straight lines to straight lines.

A function $f:\mathbb{R}^m\to \mathbb{R}^n$ is **linear** if for any vectors
$\vec{x}$ and $\vec{y}$ in $\mathbb{R}^m$
$$
f(a \vec{x}+\vec{ y})=af(\vec{x})+f(\vec{y}).
$$
From results discussed in our notes on [[linear-algebra]] we have that if
$f:\mathbb{R}^m\to \mathbb{R}^n$ is linear, then there exists vectors
$\vec{a}_{1}, \dots, \vec{a}_{n}\in \mathbb{R}^m$ such that for all
$\vec{ x}\in \mathbb{R}^m$ we have
$$
f(\vec{x})=\begin{pmatrix}\vec{a}_{1}\cdot \vec{x}  \\
\vdots \\
 \vec{a}_{n} \vec{x}\end{pmatrix}.
$$
In matrix notation we can write a linear function as
$$
f(\vec{x})=A_{1}x_{1}+\dots+A_{n}x_{n},
$$
where $A_{1}, \dots, A_{n}$ can be scalars, dense or sparse matrices. 

:::{.definition data-title="Affine Function"}

A function $g:\mathbb{R}^m\to \mathbb{R}^n$ is **affine** if there exists a
linear function $f:\mathbb{R}^m \to \mathbb{R}^n$ and a vector
$\vec{c}\in \mathbb{R}^n$ such that for all $\vec{ x}\in \mathbb{R}^m$ we have
$$
g(\vec{ x})=f(\vec{ x})+\vec{ c}.
$$

:::

