---
title: Asymptotic Expansion
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Asymptotic Expansion

An **asymptotic expansion** (Poincaré expansion) is a formal series of
functions such that truncating the series after a finite number of terms
provides an approximation to a given function as the argument of the function
tends towards a particular (often infinite) point.

The most common type of asymptotic expansion is a [[power-series]] in either
positive or negative powers. Methods of generating expansions include the
**Euler-Maclaurin Summation Formula**, and integral transforms such as the
**Laplace Transform** or the **Mellin Transform**. Additionally, repeated
integration by parts will often lead to an asymptotic expansion.

## Asymptotic Expansion
Let $\varphi_{n}$ is a sequence of continuous functions on some domain and let
$L$ be a limit point of the domain. Then the sequence constitutes an asymptotic
scale if for every $n$
$$
\varphi_{n+1}(x)=o(\varphi_{n}(x));\quad x \to L,
$$
where $L$ can be taken to be $\infty$. In other words, each function in the
sequence grows strictly slower (as $x \to L$) than the preceding function.