---
id: borel-measure
aliases: []
tags: []
author: "John Robin Inston"
date: 2026-09-25
number-sections: true
title: "Borel Measure"
title-block-banner: true
---

## Borel Measure

($\star$) **Definition (Borel Measure):** A measure
$\mu:\mathcal{B}_{\mathbb{R}}\to[0,+\infty]$ mapping from the *Borel set* on
$\mathbb{R}$ $\mathcal{B}_{\mathbb{R}}$ are named Borel measures on
$\mathbb{R}$.

Our aim for this section is to construct the family of *Borel measures*. Our
procedure will be to construct a measure $\mu$ starting from an increasing,
right-continuous function $F$ using the building blocks of left-open,
right-closed intervals in $\mathbb{R}$ i.e. sets of the form $(a,b]$ or
$(a,\infty)$ or $\emptyset$ where $-\infty \leq a<b<\infty$, referred to as
**$h$-intervals** (half-open intervals).

Some preliminary observations, clearly the intersection of two $h$-intervals is
a $h$-interval and the complement of a $h$-interval is either a $h$-interval or
the disjoint union of two $h$-intervals. Further, the collection $\mathcal{A}$
if finite disjoint unions of $h$-intervals is an algebra and the
$\sigma$-algebra generated by $\mathcal{A}$ is $\mathcal{B}_{\mathbb{R}}$.

**Proposition:** Let $F:\mathbb{R} \to \mathbb{R}$ be increasing and
right-continuous. If $(a_{j}, b_{j}]$ for $j=1,\dots,n$ are disjoint
$h$-intervals, define
$$
\mu_{0}\left( \bigcup_{j=1}^n (a_{j}, b_{j}] \right)=\sum_{j=1}^n (F(b_{j})-F(a_{j})),
$$
and $\mu_{0}(\emptyset)=0$. Then $\mu_{0}$ is a premeasure on the algebra
$\mathcal{A}$.

($\star$) **Theorem:** For increasing, right continuous function
$F:\mathbb{R} \to \mathbb{R}$ there is a unique Borel measure $\mu_{F}$ on
$\mathbb{R}$ such that $\mu_{F}((a,b])=F(b)-F(a)$ for all $a,b$ known as the
*Lebesgue-Stieltjes measure*. If $G$ is another such function, we have
$\mu_{F}=\mu_{G}$ if and only if $F-G$ is constant. Conversely, if $\mu$ is a
Borel measure on $\mathbb{R}$ that is finite on all bounded Borel sets and we
define
$$
F(x)=\begin{cases}
\mu((0,x]) & \text{if }x>0 \\
0 & \text{if }x = 0 \\
-\mu((-x,0]) & \text{if }x<0,
\end{cases}
$$
then $F$ is increasing and right continuous, and $\mu=\mu_{F}$. 

Note that this theorem could equally well be developed by using intervals of
the form $[a,b)$ and left continuous function $F$. Also note that $\mu$ is a
finite Borel measure on $\mathbb{R}$ then $\mu=\mu_{F}$ where
$F(x)=\mu((-\infty,x])$ is the *cumulative distribution function* of $\mu$.  

Furthermore, the theory of outer measures gives, for each increasing and right
continuous $F$, not only the Borel measure $\mu_{F}$ but a complete measure
$\overline{\mu}_{F}$ whose domain includes $\mathcal{B}_{\mathbb{R}}$. In fact,
$\overline{\mu}_{F}$ is just the completion of $\mu_{F}$ and one can show that
its domain is always strictly larger than $\mathcal{B}_{\mathbb{R}}$. This
complete measure is often also denoted $\mu_{F}$ and is called the
*Lebesgue-Stieltjes measure*.  

:::{.definition data-title="Lebesgue Measure"}

The Lebesgue measure is the Lebesgue-Stieltjes measure $\lambda=\lambda_{F}$
associated to the function $F(x)=x$. The domain of $\lambda$ is the class of
Lebesgue measurable sets

:::

**UPDATE NOTES FROM END OF FOLLAND CHAPTER 1**
