---
title: Borel σ-Algebra
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Borel σ-Algebra

To construct a measure for the real numbers $\mathbb{R}$ we need to first
construct a suitable $\sigma$-algebra, known informally as the **Borel
σ-algebra** (of the real numbers). First, we recall the following definition of
a [[topology]].

:::{.definition data-title="Topology"}

A **topology** $\mathcal{T}$ on $X$ is a collection of subsets of $X$ that is
closed under arbitrary unions and finite intersections. The elements of
$\mathcal{T}$ are **open sets**. The pair $(X,\mathcal{T})$ is a **topological
space**.

:::

:::{.definition data-title="Borel σ-Algebra"}

Let $(X,\mathcal{T})$ be a topological space. The **Borel σ-algebra** of $X$,
$\mathcal{B}_{X}$ is the $\sigma$-algebra generated by $\mathcal{T}$. Its
members are known as **Borel sets**.

:::

To gain a deeper understanding of what the Borel sets look like we briefly
consider the Borel hierarchy. In mathematical logic, the Borel hierarchy is a
stratification of the Borel algebra. A countable intersection of open sets is
called a $G_{\delta}$ set; a countable union of closed sets is called an
$F_{\sigma}$ set; a countable union of $G_{\delta}$ sets is called a
$G_{\delta\sigma}$ set; a countable intersection of $F_{\sigma}$ sets is called
an $F_{\sigma\delta}$ set; and so forth.

*Note:* In mathematical etymology the $\delta$ and $\sigma$ stand for the
German Durchschnitt and Summe, that is, intersection and union.

:::{.theorem data-title="Borel σ-Algebra Generating Sets"}

The Borel $\sigma$-algebra of $\mathbb{R}$, $\mathcal{B}_{\mathbb{R}}$ is
generated by:
1. Open intervals $\mathcal{E}_{1}:=\{ (a,b):a<b \}$;
2. Closed intervals $\mathcal{E}_{2}:=\{ [a,b]:a<b \}$;
3. Half-open intervals $\mathcal{E}_{3}:=\{ (a,b]:a<b \}$;
4. Open rays $\mathcal{E}_{4}:=\{ (a, \infty):a\in \mathbb{R} \}$;
5. Closed rays $\mathcal{E}_{5}:=\{ [a,\infty):a\in \mathbb{R} \}$.

:::

*PROOF:*
The Borel $\sigma$-algebra $\mathcal{B}_{\mathbb{R}}:=\sigma(\mathcal{E}_{1})$
is generated from the set of open intervals
$$
\mathcal{E}_{1}:=\{ (a,b):a<b \}.
$$
(1) Considering arbitrary $(a,b]\in\mathcal{E}_{3}$ we note that since open
sets are in $\mathcal{B}_{\mathbb{R}}$ and $\sigma$-algebra are closed under
countable intersection we have that
$$
(a,b]=\bigcap_{n=1}^\infty \left( a,b+\frac{1}{n} \right)\in\mathcal{B}_{\mathbb{R}}\implies \mathcal{E}_{3}\subseteq\mathcal{B}_{\mathbb{R}\implies}\sigma(\mathcal{E}_{3})\subseteq \mathcal{B}_{\mathbb{R}}.
$$
Similarly, considering arbitrary $(a,b)\in\mathcal{E}_{1}$  
$$
(a,b)=\bigcup_{n=1}^\infty \left(a,b-\frac{1}{n}\right]\in \sigma(\mathcal{E}_{3})\implies\mathcal{E}_{1}\subseteq \sigma(\mathcal{E}_{3})\implies\mathcal{B}_{\mathbb{R}}\subseteq \mathcal{E}_{3}.
$$
(2) Considering arbitrary $(a,+\infty)\in \mathcal{E}_{5}$ we note that
$$
(a,+\infty)=\bigcup_{n=1}^\infty (a,n)\in \mathcal{B}_{\mathbb{R}}\implies\mathcal{E}_{5}\subseteq\mathcal{B}_{\mathbb{R}}\implies \sigma(\mathcal{E}_{5})\subseteq\mathcal{B}_{\mathbb{R}}.
$$
Similarly, considering arbitrary $(a,b)\in\mathcal{E}_{1}$ since
$\sigma$-algebra are closed under countable intersections
$$
\begin{align}
(a,b)&=(a,+\infty)\cap[b,+\infty)=(a,+\infty)\cap \bigcap_{n=1}^\infty \left( b-\frac{1}{n},+\infty \right)\in\sigma(\mathcal{E}_{5}) \\
\implies & \mathcal{E}_{1}\subseteq \sigma(\mathcal{E}_{5})\implies \mathcal{B}_{\mathbb{R}}\subseteq \sigma(\mathcal{E}_{5}).
\end{align}
$$
(3) Considering arbitrary $[a,+\infty)\in\mathcal{E}_{7}$ we note that
$$
\begin{align}
[a,+\infty)&=\bigcap_{n=1}^\infty[a,n)=\bigcap_{n=1}^\infty \bigcap_{m=1}^\infty\left( a-\frac{1}{m}, n \right)\in \mathcal{B}_{\mathbb{R}} \\
\implies & \mathcal{E}_{7}\subseteq \mathcal{B}_{\mathbb{R}}\implies \sigma(\mathcal{E}_{7})\subseteq\mathcal{B}_{\mathbb{R}}.
\end{align}
$$
Similarly, considering arbitrary $(a,b)\in \mathcal{E}_{1}$, since
$\sigma$-algebra are closed under countable unions and complements we have that
$$
\begin{align}
(a,b)&=(-\infty,b)\cap(-\infty,a)=([b,+\infty)^c\cup[a,+\infty)^c)^c\subseteq \sigma(\mathcal{E}_{7}) \\
\implies & \mathcal{E}_{1}\subseteq \sigma(\mathcal{E}_{7})\implies\mathcal{B}_{\mathbb{R}}\subseteq \sigma(\mathcal{E}_{7}).
\end{align}
$$
$\square$
