---
id: brownian-motion
aliases: []
tags: []
author: "John Robin Inston"
date: 2026-09-25
number-sections: true
title: "Brownian Motion"
title-block-banner: true
---

# Brownian Motion

## What is Brownian Motion?

Consider a continuous-time and continuous state stochastic process
$B:=(B_{t})_{t>0}$ taking values in $\mathbb{R}$ with initial value $B_{0}=0$
almost surely (i.e. $\mathbb{P}(B_{0}\neq 0)=0$).  

We define general $n$-increments for $0\leq t<t+n$ by

$$
\Delta_{n}B_{t}=B_{t+n}-B_{t}.
$$

We define the **increments** for subsequence of times $0<t_{1}<\dots<t_{n}$ by

$$
\Delta B_{t_{i}}=B_{t_{i+1}}-B_{t_{i}}.
$$

:::{.definition data-title="Independent Increments"}

The process $B$ is said have independent increments if for a sequence of times
$0 < t_{1}< \dots < t_{n}$ the increments $\Delta B_{t_{i}}$ are **mutually
independent** random variables, that is, for any $i\neq j$
$$
\Delta B_{t_{j}}\perp \Delta B_{t_{i}}.
$$

:::

> ***Note:*** The joint distribution factors into a product of distributions.  The key point to understand is that intervals that do not overlap contain no information about each other.

:::{.definition data-title="Normal Stationary Increments"}

The process $B$ has normal stationary increments if for all $0\leq s < t$ we
have that
$$
\Delta_{n} B_{t}\sim \text{Normal}(0, n\sigma^2).
$$

:::

:::{.definition data-title="Continuous Paths"}

The process $B$ is said to have continuous paths if
$\omega \mapsto B_{t}(\omega)$ is a continuous function of $t$ on $\mathbb{R}$
almost surely.

:::




:::{.definition data-title="Brownian Motion"}

The process $B$ is said to be a **Wiener process** (follow a **Brownian
motion**) if it satisfies the following:

1. $B$ has independent increments.
2. $B$ has normal stationary increments.
3. $B$ has continuous paths almost surely.

:::


## Properties of Brownian Motion






:::{.definition data-title="Brownian Motion"}

A **Brownian motion** (BM) or a **Wiener process** with variance parameter
$\sigma^2>0$ is a stochastic process $(B_{t})_{t \geq 0}$ taking values in
$\mathbb{R}$ that satisfies:
4. $B_{0}=0~a.s.$ (starts at zero);
5. $\forall~0 < t_{1}<\dots<t_{n},~B_{t_{1}}-B_{0}, B_{t_{2}}-B_{t_{1}}, \dots, B_{t_{n}}-B_{t_{n-1}}$
   are independent (independent increments);
6. $\forall s < t, B_{t}-B_{s}\sim\mathcal{N}(0,\sigma^2(t-s))$ (normal
   stationary increments);
7. $\omega\mapsto B_{t}(\omega)$ is a continuous function of $t$ on
   $\mathbb{R}_{+}$ almost surely (continuous paths no jumps).

:::


