---
title: Calculus of Variations
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Calculus of Variations

## Calculus of Variations
The **calculus of variations** is a field of mathematical analysis that uses
variations (small changes in functions and functionals) to mind maxima and
minima of functionals (mappings from a set of functions to the real numbers).
Functionals are often expressed as definite integrals involving functions and
their derivatives. Functions that maximize or minimize functionals may be found
using the Euler-Lagrange equation of the calculus of variations.

The calculus of variations is concerned with the maxima or minima (collectively
called **extrema**) of functionals. Recall the following definition of a
[[functional]].

:::{.definition data-title="Functional"}

A **functional** is a mapping $\mathscr{F}:Y^X\to Z$ where
$$
Y^X\ni f(x)\mapsto \mathscr{F}[f(x)]\in Z
$$
where $Y^X$ denotes the function space of mappings from $X$ to $Y$ and $Z$ is a
scalar field.

:::

A functional $\mathscr{F}$ is said to have an **extremum** at the function $f$
if
$$
\Delta \mathscr{F} = \mathscr{F}[y]-\mathscr{F}[f]
$$
has the same sign for all $y$ in an arbitrarily small neighborhood of $f$. Here
the function $f$ is called an **extremal function** or an **extremal**. The
extremum $\mathscr{F}[f]$ is called a **local maximum** if
$\Delta \mathscr{F}\leq 0$ everywhere in an arbitrarily small neighborhood of
$f$, and a **local minimum** if $\Delta \mathscr{F}\geq 0$ there,

For a function space of continuous functions, extrema of corresponding
functionals are called **strong extrema** and **weak extrema**, depending on
whether the first derivatives of the continuous functions are respectively all
continuous or not.

## Euler-Lagrange Equation

[[euler-lagrange-equation]]