---
title: Canonical Decomposition Theorem
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

The idea of the canonical decomposition theorem is that, since
intercommunication is an [[equivalence-relation]] we can use sets of
intercommunicative states to partition the state space $C$ into disjoint
equivalence classes.
#### Canonical Decomposition Theorem

Specifically, the state space $S$ may be decomposed uniquely as
$S=T \cup C_{1} \cup C_{2} \cup \dots$ where:

1. $T$ is the set of [[markov-chain-state-classification|transient states]];
   and
2. $C_\alpha$ are closed disjoint irreducible classes of
   [[markov-chain-state-classification|persistent states]].
 
To put the transition matrix into *canonical form*, for each class $C_{\alpha}$
obtain a transition matrix $P_{\alpha}$ by only considering rows and columns
from states in $C_{\alpha}$, then after reordering the states the transition
matrix $P$ can be rewritten as
$$
P=\begin{pmatrix}P_{1} & 0 & 0 & 0 & \cdots \\ 0 & P_{2} & 0 & 0 & \cdots  \\ 0 & 0 & P_{3} & 0 & \cdots \\ \vdots & \vdots & \vdots & \vdots & \\ Q_{1} & Q_{2} & Q_{3} & Q_{4} & \cdots\end{pmatrix}
$$
where $Q_{\alpha}$ govern transitions for states in $T$.

