---
title: Carathéodory Extension Theorem
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## What is the Carathéodory Extension Theorem?

The **Carathéodory extension theorem** is a fundamental result in
[[measure-theory-notes|measure theory]] which gives the procedure by which any
[[pre-measure|pre-measure]] defined on a given [[ring|ring]]
([[algebra|algebra]]) $R$ of a given set $X$ can be extended to a
[[measure|measure]] on a [[ring|σ-ring]] ([[algebra|σ-algebra]]) generated by
$R$, and this extension is **unique** if the pre-measure is $\sigma$-finite.

:::{.theorem data-title="Carathéodory Extension Theorem"}

Given and outer measure $\mu^*$ then
1. $\mathcal{F}_{\mu^*}$ is a $\sigma$-algebra; and
2. $\mu^*$ is a measure on $\mathcal{F}_{\mu^*}$.

:::

*Note:* We can show that this is in general not the largest $\sigma$-algebra on
which $\mu^*$ is a measure.

*Proof:*
Since $\mu^*(\emptyset)=0\implies \emptyset \in \mathcal{F}_{\mu^*}$ by the
proposition above, hence $\mathcal{F}_{\mu^*}$ is non-empty; and by definition
of an outer-measurable set $\mathcal{F}_{\mu^*}$ is closed under compliments.
Next, if $A,B \in \mathcal{F}_{\mu^*}$ and $E\subset X$ we have that
$$
\begin{align}
\mu^*(E) & = \mu^*(E \cap A)+\mu^*(E \cap A^c) \\
& = \mu^*(E \cap A \cap B)+\mu^*(E \cap A \cap B^c)+\mu^*(E \cap A^c \cap B)+\mu^*(E \cap A^c \cap B^c) \\
 & \geq  \mu^*(E \cap(A\cup B))+\mu^*(E \cap(A \cup B)^c),
\end{align}
$$
where the final inequality holds from subadditivity since
$A\cup B=(A \cap B)\cup(A \cap B^c)\cup (A^c\cap B)$. It follows that
$A \cup B\in \mathcal{F}_{\mu^*}$ and so it is an algebra. Moreover, if
$A,B \in \mathcal{F}_{\mu^*}$ and $A \cap B=\emptyset$ then
$$
\mu^*(A \cup B)=\mu^*((A\cup B)\cap A)+\mu^*((A \cup B)\cap A^c)=\mu^*(A)+\mu^*(B),
$$
hence $\mu^*$ is finitely additive on $\mathcal{F}_{\mu^*}$. To prove
$\mathcal{F}_{\mu^*}$ is a $\sigma$-algebra it suffices to show
$\mathcal{F}_{\mu^*}$ is closed under countable disjoint unions. If we consider
disjoint $\{ A_{j} \}_{j=1}^\infty \subseteq \mathcal{F}_{\mu^*}$ and define
$B_{n}:=\bigcup_{j=1}^nA_{{j}}$ and $B :=\bigcup_{j=1}^\infty A_{j}$. Then, for
any $E \subset X$ we have
$$
\mu^*(E \cap B_{n})=\mu^*(E \cap B_{n}\cap A_{n})+\mu^*(E \cap B_{n}\cap A_{n}^c)=\mu^*(E \cap A_{n})+\mu^*(E \cap B_{n-1}),
$$
hence, by induction we have that
$\mu^*(E \cap B_{n})=\sum_{j=1}^n\mu^*(E \cap A_{j})$. Therefore
$$
\begin{align}
\mu^*(E) & =\mu^*(E \cap B_{n})+\mu^*(E \cap B_{n}^c)\geq  \sum_{j=1}^n\mu^*(E\cap A_{j})+\mu^*(E \cap B^c) \\
& \stackrel{n \to \infty}{\geq }\sum_{j=1}^\infty \mu^*(E \cap A_{j})+\mu^*(E \cap B^c)\geq \mu^*\left( \bigcup_{j=1}^\infty (E\cap A_{j}) \right)+\mu^*(E \cap B^c) \\
& = \mu^*(E \cap B)+\mu^*(E\cap B^c)\geq  \mu^*(E),
\end{align}
$$
and so all the inequalities become equalities thus $B\in \mathcal{F}_{\mu^*}$
as required. Furthermore, taking $E=B$ we have
$\mu^*(B)=\sum_{j=1}^\infty \mu^*(A_{j})$ and so $\mu^*$ is countable additive
on $\mathcal{F}_{\mu^*}$. Finally, if $\mu^*(A)=0$, for any $E \subset X$
$$
\mu^*(E)\leq  \mu^*(E \cap A)+\mu^*(E \cap A^c)=\mu^*(E \cap A^c)\leq \mu^*(E),
$$
so that $A \in \mathcal{F}_{\mu^*}$, hence $\mu^*$ is a complete measure on
$\mathcal{F}_{\mu^*}$.
$\square$