---
title: Classical Mechanics
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

#### References

- Classical Mechanics - *Goldstein*
- [Caltech Lecture Notes on Classical Mechanics for Physics 106ab - Sunil Golwala](https://sites.astro.caltech.edu/~golwala/ph106ab/ph106ab_notes.pdf)

#### Contents

```table-of-contents
title: 
style: nestedOrderedList # TOC style (nestedList|nestedOrderedList|inlineFirstLevel)
minLevel: 0 # Include headings from the specified level
maxLevel: 3 # Include headings up to the specified level
includeLinks: true # Make headings clickable
hideWhenEmpty: false # Hide TOC if no headings are found
debugInConsole: false # Print debug info in Obsidian console
```

## Elementary Mechanics

### Newton's Second Law

We define the following functions of time for a particle: (1) the **position**
$\vec{r}(t)$; (2) the **velocity** $\vec{v}(t)= \frac{d}{dt}\vec{r}(t)$ (the
**speed** is $\lvert \vec{v} \rvert$); (3) the **acceleration**
$\vec{a}(t)=\frac{d}{dt}\vec{v}(t)=\frac{d^2}{dt^2}\vec{r}(t)$; and (4) the
**momentum** $\vec{p}(t)=m(t)\vec{v}(t)$ where $m(t)$ denotes the mass of the
particle.

:::{.definition data-title="Newton's Second Law"}

In inertial frames it holds that the force $\vec{F}(t)$ acting on a particle is
given by
$$
\vec{F}(t)= \frac{d}{dt}\vec{p}(t)=\frac{d}{dt}(m(t)\vec{v}(t)).
$$
If the mass is not time-dependent then we obtain the familiar
$$
\vec{F}(t)=m \frac{d}{dt}\vec{v}(t)=m\vec{a}.
$$

:::

From Newton's Second Law we also **Law of Conservation of Linear Momentum**.
Supposing the force on a particle is $\vec{F}$ and that there is a vector
$\vec{s}$ such that the force has no component along $\vec{s}$, that is
$$
\vec{F}\cdot \vec{s}=0.
$$
Then, from Newton's Second Law we have that 
$$
\frac{d}{dt}\vec{p}\cdot \vec{s}=0 \implies \vec{p}\cdot  \vec{s}=\alpha,
$$
where $\alpha$ is constant, that is there is conservation of the component of
linear momentum along the direction $\vec{s}$ in which there is no force.

**Example (Atwood's Machine Problem):**

```tikz
\usepackage{tikz}
\usetikzlibrary{arrows.meta}
\begin{document}

\begin{tikzpicture}[>=Latex]
   \draw[thick] (0,0) circle (10mm);
   \draw[thick,->](-1,0)--++(0,-2)node[below]{$T_2$};
   \draw[thick,->](1,0)--++(0,-2)node[below]{$T_2$};
   \draw[thick,->](0,0)--++(0,2)node[above]{$T_1$};
\end{tikzpicture}

\end{document}
```

### Retarding Forces

We introduce forces that are not static but rather depend on the velocity of
the moving object. Such a force can frequently be written as a **power law** in
the velocity
$$
\vec{F}_{r}=\vec{F}_{r}(v)=-kv^n \frac{\vec{v}}{v},
$$
where $k$ is a constant that dependent on the details of the problem. We note
that the force is always directed opposite to the velocity of the object.

**Example (Retarding Forces):**


### Angular Motion

Next we derive analogues of linear momentum, force and Newton's Second Law for
angular motion. The **angular velocity** of a particle as a function of time
with respect to a particular origin
$$
\vec{v}(t)=\vec{\omega}(t) \times \vec{r}(t).
$$
This can be written mathematically as
$$
\partial  \vec{r}= \partial  \vec{\theta} \times \vec{r}
$$
where $\partial \vec{\theta}$ points along the axis of the motion and $\times$
indicates a vector cross-product. The cross-product gives the correct direction
for displacement $\partial \vec{r}$ (perpendicular to the axis and $\vec{r}$)
and the correct amplitude
($\lvert \partial  \vec{r} \rvert = R \partial \theta = r \partial \theta \sin \alpha$).
If we then divide by the time $\partial t$ required to make this displacement
we have
$$
\frac{\partial\vec{r}}{\partial t} = \frac{\partial\vec{\theta}}{ \partial t} \times \vec{r} \implies \vec{v} = \vec{\omega} \times \vec{r}.
$$


