---
title: Climate Teleconnection
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Climate Teleconnection

Teleconnections are significant relationships or links between weather
phenomena at widely separated locations on earth, which typically entail
climate patters that span thousands of miles. Many teleconnection patterns
behave like a seesaw, with atmospheric mass/pressure shifting back and forth
between two distant locations—an increase in, say, atmospheric pressure in one
location results in a decrease in pressure somewhere far, far away.

<!-- TODO: image "Pasted image 20241012220410.png" not found in vault -->

*Figure 1: Late winter temperatures compared to the 1981-2010 average when the
North Atlantic Oscillation (NAO) was strongly negative (top, Jan-March 2010)
and when it was strongly positive (bottom, January-March 1990). Winters are
often cooler than average across the mid-latitudes when the NAO is negative,
and warmer than average when it is positive. NOAA Climate.gov image, based on
data from the Physical Sciences Lab.*

One of the most famous drivers of teleconnection patterns is our good buddy
ENSO (perhaps we are a little biased) a.k.a the El Niño/Southern Oscillation.
The “Southern Oscillation” refers to changes in sea-level pressures that are
centered over the eastern tropical Pacific and over Indonesia (learn more
[here](https://www.climate.gov/news-features/blogs/enso/what-el-ni%C3%B1o%E2%80%93southern-oscillation-enso-nutshell)
and [here](https://seasonedchaos.github.io/Round-1-ENSO-is-King/)). Followed
closely in notoriety is the
[Pacific-North American pattern,](https://www.climate.gov/news-features/understanding-climate/climate-variability-pacific%E2%80%93north-american-pattern)
an oscillatory pressure pattern over the Pacific Ocean and North America, which
influences North American and European temperature and precipitation.

