---
title: Completeness
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Completeness

The [[rational-numbers|rational numbers]] $\mathbb{Q}$ and
[[real-numbers|real numbers]] $\mathbb{R}$ have similar algebraic and
[[order|order]] properties (they are both
[[dense-order|densely ordered fields]]). The crucial property that
distinguishes $\mathbb{R}$ from $\mathbb{Q}$ is its **completeness**.

There are two main ways to define the completeness of $\mathbb{R}$, one based
on the [[order|order]] properties of $\mathbb{R}$ and the existence of suprema.
The other is based on the [[metric|metric]] properties of $\mathbb{R}$ and the
convergence of [[cauchy-sequence|Cauchy sequences]].

### Completeness from Order and Suprema

The following axiomatic property of the [[real-numbers|real numbers]] is called
**Dedekind Completeness**. Dedekind (1872) showed that the real numbers are
characterized by the condition that they are a **complete ordered field**.

:::{.definition data-title="Dedekind's Completeness"}

Every nonempty set of real numbers that is bounded from above has a supremum.

:::

**Example:**  Define $A\subset \mathbb{Q}$ by 
$$
A:= \{  x \in \mathbb{Q}: x^{2}<2 \}.
$$
Then $A$ is bounded from above by every $M\in \mathbb{Q}^+$ such that $M^2>2$.
Nevertheless, $A$ has no supremum in $\mathbb{Q}$ because $\sqrt{2 }$ is
[[rational-numbers|irrational]].

