---
title: Continuous Mapping Theorem
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

#### [[continuous-mapping-theorem]]

In probability theory, the **continuous mapping theorem** states that
continuous functions preserve limits even if their arguments are sequences of
random variables.

:::{.theorem data-title="Continuous Mapping Theorem"}

Let $\{  X_{n} \}$ be a sequence of random variables and $g$ some continuous
function. Then
- $X_n\stackrel{\mathcal{D}}{\to}X_n\implies g(X_n)\stackrel{\mathcal{D}}{\to}g(X)$
- $X_n\stackrel{\mathbb{P}}{\to}X_n\implies g(X_n)\stackrel{\mathbb{P}}{\to}g(X)$
- $X_n\stackrel{a.s.}{\to}X_n\implies g(X_n)\stackrel{a.s.}{\to}g(X)$

:::

The intuition behind the result is clear, since Heine's definition of a
continuous function is one that maps convergent sequences onto convergent
sequences.
### Continuous Mapping Theorem (Detailed)

:::{.theorem data-title="Continuous Mapping Theorem"}

Let $\{  X_{n} \}$ be a sequence of r.v.s such that
$X_{n}\stackrel{\mathcal{D}}{\to}X$. Let $g:\mathbb{R}\to \mathbb{R}$ be a
function with discontinuity set
$D(g):=(C(g))^c=\{  x:g\text{ is not continuous at }x \}$. Let
$\mathbb{P}(X \in D(g))=0.$ Then $g(X_{n})\stackrel{\mathcal{D}}{\to} g(X)$.  
If, in addition, $g$ is bounded, the dominated convergence theorem implies that
$$
\int g(x) dF_{n}(x)\to \int g(x)dF(x)\implies \mathbb{E}[g(X_{n})]\to \mathbb{E}[g(X)].
$$

:::

