---
title: Convex Set
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

In geometry, a subset of a Euclidean space, or more generally an
[[affine-space|affine space]] over all the reals, is convex if, given any two
points in the subset, the subset contains the whole line segment that joins
them.

Equivalently, a convex set (region) is a subset that intersects every line into
a single line segment (possibly empty). For example, a cube is convex but
anything that is hollow or has an indent, for example a crescent shape, is not
convex.

<!-- TODO: image "Pasted image 20240330152023.png" not found in vault --><!-- TODO: image "Pasted image 20240330152122.png" not found in vault -->

*Figure: Convex shape (left) and non-convex shape (right).*

The boundary of a convex set is always a **convex curve**. The intersection of
all convex sets that contain a given subset $A$ of Euclidean space is called
the **convex hull** of $A$. It is the smallest convex set containing $A$
(related to generated $\sigma$-algebra).

### Convex Set

Let $S$ be a [[vector-space-linear-space|vector space]] or an
[[affine-space|affine space]] over the real numbers or, more generally, over
some ordered field (this includes Euclidean spaces, which are affine spaces). A
subset $C$ of $S$ is **convex** id, for all $x$ and $y$ in $X$, the line
segment connecting $x$ and $y$ is included in $C$.

This means that the [[affine-combination|affine combination]]
$$
(1-t)x+ty\in C
$$
for all $x,y\in C$ and $t\in[0,1]$.

A set $C$ is **strictly convex** if every point on the line segment connecting
$x$ and $y$ other than the endpoints is inside the
[[topological-interior|topological interior]] of $C$. A closed convex subset is
strictly convex if and only if every one of its
[[boundary-points|boundary points]] is an [[extreme-point|extreme point]].

A set $C$ is **absolutely convex** if it is convex and
[[balanced-set|balanced]].