---
title: Cox's Proportional Hazards Model
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

Suppose we wish to estimate an unknown function, e.g. a survival function. We
can take several approaches:

- Non-parametric using [[kaplan-meier]]
	- Advantage: no assumption regarding type of distribution.
	- Disadvantage: requires i.i.d. observations
- Parametric
	- Advantage: (1) We only need to estimate a few parameters that completely
   characterize distribution (e.g. Exponential or Weibull); (2) gives low
   variance of estimates; (3) can be extended to non-iid observations using
   regression on covariates.
	- Disadvantages: assumed model class may be (or always is) incorrect leading
   to model error or in other words, bias.
- Semi-Parametric
	- Cox's Proportional Hazards Model

Cox proposed the following model for the hazard function given covariates
$z\in \mathbb{R}^p$
$$
h(t;z) = h_{0}(t)\exp(z^T \beta ),\quad \beta \in \mathbb{R}^p.
$$
Here $h_{0}$ completely unspecified function except that it must be
non-negative.

Thus model combines great flexibility via non-parametric





**References**
- [[lecture-notes-waagepetersen-2022-pdf]]
- [[stat331-stanford-lecture-notes-pdf]]