---
title: ESM226 Presentation
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Background

- **Introduce the area**

- History
- Geography & Climate
	- 
	- https://www.weather.gov/vef/ClimateofLasVegas



	- Aquifer system (geology, flow, add an image of a cross section if one is
   available)
		- *Geology*
			- [[galloway-et-al-1999]]
				- Las Vegas Valley is bounded on the west by several mountain ranges and
      drains a 1.564-square-mile watershed southeastward through Las Vegas Wash
      into Lake Mead
				- Las Vegas Valley is a sediment-filled structural trough that has formed
      over many millions of years through compression, extension, and faulting
      of the original flat-lying marine sediments that form the bedrock.
      Sediment eroded by wind and water from the surrounding bedrock highlands
      began filling the trough with gravel, sand, silt and clay.
				- During some of the wetter periods in the past 1 million years or so,
      extensive playa lakes and spring-fed marshes covered the lower parts of
      the valley floor, depositing variably thick sequences of fine-grained
      sediment (Mifflin and Wheat, 1979 and Quade et al.,1995). Coarse-grained
      sand and gravel tend to rim the valley, forming alluvial fans and
      terraces, especially in the northern, western , and southern parts.The
      deposits generally thicken and become finer- textured toward the central
      and eastern part of the valley, where their total thickness exceeds 5,000
      feet (Plume, 1989) .
		- *Groundwater Flow*
			- [[galloway-et-al-1999]]
				- Groundwater is generally pumped from the upper 2,000 feet of
      unconsolidated sediments that constitute the aquifer system in the
      central part of the valley. The deeper aquifers, generally below 300
      feet, are capable of transmitting significant quantities of groundwater,
      and have been referred to variously as the principle aquifers. In places,
      these principle aquifers are more than 1,000 feet thick and consist
      mainly of sands and gravels beneath the terraces along the margins of the
      valley. In the central and eastern parts, clays and silts predominate (
      Plume, 1989).
				- Overlying the principal aquifers , in most places, is a 100- to - 300
      foot-thick section ofextensive clay, sand, and gravel deposits known as
      the"near-surface reservoir." The principal aquifers and the near- surface
      reservoir are separated by a variably- thick, laterally discontinuous
      aquitard, or confining unit.
				- Much of the ground water found in the aquifer system originates as rain
      or snow falling on the Spring Mountains to the west or on the Sheep and
      Las Vegas Ranges to the northwest. Some of the precipitation infiltrates
      into the underlying bedrock through faults and fractures, eventually
      moving into the deposits comprising the principal aquifers. The remainder
      of the precipitation runs off onto the sloping alluvial terraces and
      rapidly enters the sand and gravel deposits, where it either recharges
      the underlying principal aquifers or is evaporated or transpired into the
      atmosphere.
				- Near the margins of the valley, ground water moves freely through the
      coarse-grained sand and gravel deposits, but as it moves basinward it
      begins to encounter increasingly greater percentages of lower
      permeability, fine- grained clay and silt. The increasing proportion of
      fine-grained deposits retards lateral flow, and the low- permeability
      deposits effectively impede the vertical flow of ground water. As ground
      water recharges the aquifer system from the higher elevations, fluid
      pressures in the principal aquifers can buildto create artesian
      conditions at lower elevations in the basin.
				- 
	- Land uses and climate conditions
	- Groundwater demand
		- Las Vegas Valley was the fastest growing metropolitan area in the US circa
    1999 and the accelerated demand for water was being met with imported water
    from the Colorado river and local groundwater, which lead to the depletion
    of one-plentiful groundwater supplies, land subsidence (around 6ft) and
    ground failures.
- At the time, the current water supplies were expected not to satisfy the
  anticipated water demand with the federally mandated limit placed on imported
  water. supplied from Lake Mead, likely to force a continued reliance on
  ground water.
	- Groundwater level changes
		- Include plot of groundwater level changes over time
### Intervention

- Describe the intervention(s) that took place,
- Introduce key concepts and, if relevant, locations of projects within the
  study area
- Examples of interventions may be managed aquifer recharge projects, new
  policies, changes to groundwater market conditions, development of an
  alternate water source
- Where possible, be quantitative (e.g., if groundwater pumping declined, show
  a graph highlighting the change in pumping over time)
### Outcomes

- Describe the consequences (good and/or bad) of the intervention
- Show a plot of groundwater level changes over time, and mark the year(s) that
  the intervention took place
### Summary

- Summarize your main findings.
- State the one big take away from your work (i.e., if there was just one thing
  your audience should learn from your work, what is it)



## Script

- Las Vegas initially contained several artisan wells supporting extensive
  green areas (hence the same where 'vegas' is spanish for 'meadows').
- 