---
title: Euler-Lagrange Equation
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Euler-Lagrange Equation

In [[calculus-of-variations]] and [[newtonian-mechanics]] the **Euler-Lagrange
equation** are a system of second-order [[ordinary-differential-equations]]
whose solutions are *stationary points* of a given action
[[functional|functional]]. A differentiable functional is stationary (i.e. the
[[functional-derivative|functional derivative]] is zero ) at its local extrema
(minimum, maximum, inflection points) thus, the Euler-Lagrange equation is
useful for solving [[control-theory|optimization problems]] in which, given
some functional, one seeks the function minimizing or maximizing it. This leads
to solving the **Euler-Lagrange equation**.

In [[lagrangian-mechanics]], from Hamilton's principle of stationary action,
the evolution of a physical system is described by the solutions to the Euler
equation for the action of the system. This is equivalent to Newton's laws of
motion with the added advantage that it takes the same form in any system of
generalized coordinates.

## Euler-Lagrange Equation
Suppose that we are given the (action) functional 
$$
\mathscr{A}[x(t)]=\int_{0}^{T}{\mathcal{L}(\dot{\boldsymbol{x}}, \boldsymbol{x},t)}~d{t}
$$
where we assume $\boldsymbol{x}\in C^d$ is a $d$-times continuously
differentiable function that maps time $t\in[0,T]$ to $\mathbb{R}^n$, and
$\mathcal{L}(\dot{\boldsymbol{x}},\boldsymbol{x},t):=\mathbb{R}^n\times \mathbb{R}^n\times [0,T]\mapsto \mathbb{R}$
is the [[lagrangian]]. If we want to find the extremal (maximum, minimum or
inflection point) of a classical real value function with finite dimensional
domain, we typically calculate the derivatives and find where they equal zero.
The following can be thought of intuitively as the infinite dimensional case.
Note that in the following theorem that this is a system of $n$-equations.

:::{.theorem data-title="Euler-Lagrange Equations"}

Suppose $\mathcal{L}\in C^2$ and $\boldsymbol{x}:[0,T]\to \mathbb{R}^n$. Then
if $\boldsymbol{x}(t)$ is an extremal of $\mathscr{A}$ we evaluate
$$
- \frac{d}{dt}[\nabla_{\dot{x}}\mathcal{L}(\dot{\boldsymbol{x}}, \boldsymbol{x},t)]+\nabla_{x}L(\dot{\boldsymbol{x}}, \boldsymbol{x},t)=0,
$$
where $\nabla$ denotes the [[gradient]].

:::

*PROOF:*
Suppose we have a smooth test function $\phi(t)\in C^\infty$ where
$\phi(0)=\phi(T)=0$. Because $\boldsymbol{x}$ is a local extrema of
$\mathscr{A}$ then if we perturb $\boldsymbol{x}$ by function $k\phi$ with
small $k$ the resulting functional $\mathscr{A}(\boldsymbol{x}+k\phi)$ should
be roughly unchanged, that is
$$
\frac{d}{dk}[\mathscr{A}(\boldsymbol{x}+k\phi)]\Big|_{k=0}=0.
$$
Computing the derivative by [[leibniz-integral-rule]] for each coordinate
$\boldsymbol{x}$ we have
$$
\int_{0}^{T}{\frac{d\mathcal{L}(\dot{\boldsymbol{x}}_{i}+k \dot{\phi}_{i},\boldsymbol{x}_{i}+k\phi_{i},t)}{dk}}~d{t=0;\quad \forall i}.
$$
COMPLETE THE PROOF!

- Gateaux Derivative

  
### Example: Diving
*References:*
[Functionals and Functional Derivatives](https://www.youtube.com/watch?v=6VvmMkAx5Jc&t=593s)
Suppose we drop a weight suspended from a height. In cartesian coordinates we
let the ground be at $0$ and our weight at $y$. Assume that the weight has mass
$m=2$ and assume that the gravitational constant $g=2$. The potential and
kinetic energy of the weight is given by
$$
\begin{cases}
K = mgh = 2 \cdot 2 \cdot y =4y  \\
E = \frac{1}{2}mv^2=\dot{y}^2.
\end{cases}
$$

