---
title: European Options
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## European Options

**European options** are the simplest kind of financial derivatives after
forwards and futures. Options have become a standard tool in modern finance
allowing investors to construct contracts to hedge portfolio risk, take
advantage of perceived arbitrage and leverage risk.

:::{.definition data-title="European Option"}

A **European put/call option** is a contract giving its holder the right but
not the obligation to sell/purchase an underlying asset for some specified
strike price $K$ at some future maturity time $T$.

:::

## Pricing European Options

### Risk-Free Measure Approach

Introducing typical mathematical notation, for underlying asset with price $S$
the payoff function $\Phi$ of a European call option with strike price $K$ at
maturity time $T$ is given by
$$
\Phi(T,S)=(S_{T}-K)_{+}.
$$
<!-- TODO: image "Pasted image 20250602123056.png" not found in vault -->
Therefore from [[derivatives-pricing|risk-neutral pricing]] we have that the
price of the European call option at present time $t$ is given by the expected
payoff of the option adjusted for the time-value of money
$$
P(t, \Phi) = \mathbb{E}[D_{t}\Phi(T,S)],
$$
where $D_{t}$ represents the discounting factor. The specific form of this
discount depends on the assumed underlying model.



