---
title: Exploration - Lebesgue Measure
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

A key component of constructing the [[lebesgue-integral]] is the **Lebesgue
measure** which is a type of [[measure|measure]] on the
[[real-numbers|real numbers]].  
#### Generated $\sigma$-Algebra

Consider a set $\Omega$ and a collection $\mathcal{A}$ of subsets of $\Omega$.
We denote all [[sigma-algebra|$\sigma$-algebra]] containing $\mathcal{A}$ by
$\mathcal{F}_{i},~i \in I$ where $I$ is some index set. There exists a
**smallest $\sigma$-algebra containing $\mathcal{A}$** denoted
$\sigma(\mathcal{A})$ - known as the
[[generated-sigma-algebra|$\sigma$-algebra generated by $\mathcal{A}$]] - which
is the intersection of all other $\sigma$-algebra containing $\mathcal{A}$,
i.e.
$$
\sigma(\mathcal{A}) := \bigcap_{i\in I}\mathcal{F}_{i}.
$$
`\begin{proof}`
To show that $\sigma(\mathcal{A})$ is a $\sigma$-algebra we simply note each of
the following:
1. $\forall i,\Omega \in\mathcal{F}_{i} \implies\Omega \in\cap_{i}\mathcal{F}_{i}$.
2. Let
   $A\in\cap_{i}\mathcal{F}_{i}\implies \forall i, A\in\mathcal{F}_{i}\implies \forall i,A^c\in\mathcal{F}_{i}\implies A^c\in\cap_{i}\mathcal{F}_{i}$.
3. Let
   $\{ A_{n} \}_{n\in\mathbb{N}}\subseteq \cap_{i}\mathcal{F}_{i}\implies \{ A_{n} \}_{n\in \mathbb{N}}\in \mathcal{F}_{i},~\forall i\in I\implies \bigcup_{n\in \mathbb{N}}A_{n}\in \mathcal{F}_{i},~ \forall i\in I\implies \bigcup_{n\in \mathbb{N}}A_{n}\in \bigcap_{i \in I}\mathcal{F}_{i}$.
Hence $\sigma(\mathcal{A})$ is a $\sigma$-algebra and since it is the
intersection of all possible $\sigma$-algebra containing $\mathcal{A}$ it is
the smallest.`\end{proof}`

#### Measures on the Real Numbers

To construct measures on the real numbers $\mathbb{R}$ we have to construct a
$\sigma$-algebra $\mathcal{R}$ containing all measurable subsets of the reals.  

The [[borel-sigma-algebra|Borel $\sigma$-Algebra]] on the real numbers
$\mathcal{R}$ is the $\sigma$-algebra generated by the open sets (or
equivalently the closed sets) of $\mathbb{R}$.

One the [[measurable-space|measurable space]] $(\mathbb{R},\mathcal{R})$ we can
define measures by first giving a **Stieltjes measure function** which is a
function $F:\mathbb{R} \to \mathbb{R}$ that is:
1. $F(b) \geq F(a)$ for all $b > a$ *(non-decreasing)*;
2. $\lim_{y \downarrow x}F(y) = F(x)$ *(right-continuous)*.

Associated with each Stieltjes measure function $F$ there is a unique measure
$\mu$ on $(\mathbb{R}, \mathcal{R})$ with
$$
\mu((a,b])=F(b) - F(a).
$$
When $F(x)=x$ the resulting measure is called the **Lebesgue measure**.

