---
title: Feynman-Kac Formula
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Feynman-Kac Formula
References: [Wikipedia](https://en.wikipedia.org/wiki/Feynman–Kac_formula).

The **Feynman-Kac Formula** establishes a link between
[[parabolic-partial-differential-equations]] and
[[knowledge-mathematics-analysis-probability-theory-stochastic-processes-stochastic-processes|Stochastic Processes]].
It offers a method of solving certain PDEs by simulating random paths of a
stochastic process. Conversely, an important class of expectations of random
processes can be computed by deterministic methods.

:::{.theorem data-title="Feynman-Kac Formula"}

Consider the PDE $$u_{t}(x,t)+\mu(x,t)u_{x}(x,t)+\frac{1}{2}\sigma^2(x,t)u_{xx}(x,t)-V(x,t)u(x,t)+f(x,t)=0,$$defined for all $x \in \mathbb{R}$ and $t \in [0,T]$ subject to the terminal condition $$u(x,T)=\psi (x)$$where $\mu,\sigma,\psi,V,f$ are known functions, $T$ is a parameter, and $u:\mathbb{R}\times[0,T]\to \mathbb{R}$ is the unknown.  The the Feyman-Kac formula expresses $u(x,t)$ as a conditional expectation under probability measure $\mathbb{Q}$ $$u(x,t)=\mathbb{E}^\mathbb{Q}\left[ g_{\tau}(t,T)\psi(X_{T})+\int_{t}^{T}{g_{s}(t,\tau)f(X_{\tau, \tau})}~d{\tau}\middle| X_{t}=x \right], $$where $X$ is an [[ito-process]] satisfying $$dX_{t}=\mu(X_{t},t)dt+\sigma(X_{t},t)dW_{t}^\mathbb{Q},$$ $g_{\tau}.g_{s}$ are functions defined by $$g_{\kappa}(a,b)=\exp \left( -\int_{a}^{b}{V(X_{\kappa}, \kappa)}~d{\kappa} \right) $$ for $\kappa=\tau,s$ and $W_{t}^\mathbb{Q}$ is [[brownian-motion]] under $\mathbb{Q}$.

:::



