---
title: Fields
author: John Inston
date: 2026-09-06
title-block-banner: true
number-sections: true
---

## Field

We are used to dealing with the **operations** addition and multiplication in
sets such as the real numbers $\mathbb{R}$ or the complex numbers $\mathbb{C}$
which we are told follow certain rules such as commutativity and associativity.
Generally, these are examples of **fields** $F$ and the rules that addition 
and multiplication follow are **field axioms**.

:::{.definition data-title="Field"}

A **field** $F$ is a set of elements upon which is defined operations of 
addition and subtraction that satisfy the **field axioms**.

:::

The **field axioms** are defined as follows:

1. $x,y \in F \implies x + y \in F$ (addition is a binary operation); 
2. $x,y \in F \implies xy \in F$ (multiplication is a binary operation);
3. $x,y \in F \implies x + y = y + x$ (addition is commutative);
4. $x,y \in F \implies xy = yx$ (multiplication is commutative);
5. $x,y,z \in F\implies (x+y)+z=x+(y+z)$ (addition is associative);
6. $x,y,z \in F \implies (xy)z=x(yz)$ (multiplication is associative);
7. $\exists 0 \in F:\forall x \in F,~x + 0=x$ (additive identity);
8. $\exists 1 \in F:\forall x \in F,~x \times 1=x$ (multiplicative identity);
9. $\forall x \in F,~ \exists y \in F:x+y=0$ (additive inverses);
10. $\forall x \in F,~\exists y\in F:x \times y=1$ (multiplicative inverses);
11. $\forall x, y,z \in F,~x\times(y+z)=(x \times y)+(x \times z)$
    (multiplication distributes over addition).

The rational numbers $\mathbb{Q}$, real numbers $\mathbb{R}$ and complex 
numbers $\mathbb{C}$ are all examples of fields.
