---
title: Introduction to Financial Mathematics
description: 
  "Financial derivatives, payoff functions and the time value of money."
author: John Inston
date: 2026-09-27
title-block-banner: true
---

## Introduction

Financial mathematics is a branch of applied mathematics that focuses on 
financial markets, instruments, and the mathematical models used to 
analyze them.  To understand financial mathematics, it is first important 
to understand the basic concepts and terminology of finance, starting with 
financial derivatives.

## Derivatives

A financial asset is a tradable resource that has value and can be bought, 
sold, or exchanged.

:::{.definition data-title="Financial Derivative"}
A **financial derivative** is a financial instrument whose value 
is derived from some underlying asset, index, or rate.  
:::

Think of a derivative as a **contract** between two parties that 
specifies the terms notinf a financial transation based on the performance of 
the underlying asset.

:::{.definition data-title="Forwards, Futures, Options, and Swaps"}

Below we define some common types of financial derivatives:

1. **Forwards**: A forward contract is a customized agreement between two parties to buy or sell an asset at a specified price on a future date. Forwards are traded over-the-counter (OTC) and are not standardized.

2. **Futures**: A futures contract is a standardized agreement to buy or sell an asset at a predetermined price on a specified future date. Futures are traded on organized exchanges and are subject to daily settlement.

3. **Options**: An option is a contract that gives the holder the right, but not the obligation, to buy (call option) or sell (put option) an asset at a specified price (strike price) on or before a specified date (expiration date).

4. **Swaps**: A swap is a derivative contract in which two parties agree to exchange cash flows or other financial instruments over a specified period. Common types of swaps include interest rate swaps and currency swaps.

:::

## Payoff Functions

We can represent the value of an underlying asset over time 
using a [[stochastic-processes.qmd|stochastic processes]].  For example, 
let $S_t$ denote the price of one share of Company XYZ stock at time $t$. 





