---
title: Folland 1
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

##### Problem

A family of sets $\mathcal{R}\subset 2^X$ is called a [[ring|ring]] if it is
closed under finite unions and differences (i.e. if
$E_{1}, \dots, E_{n}\in\mathcal{R}$ then $\bigcup_{i=1}^nE_{j}\in\mathcal{R}$
and if $E,F \in\mathcal{R}$ then $E \setminus F:=E \cap F^c\in \mathcal{R}$). A
ring that is closed under countable unions is called a $\sigma$-ring.

Prove the following results:

1. Rings ($\sigma$-rings) are closed under finite (countable) intersections.
2. Rings ($\sigma$-rings) are algebras ($\sigma$-algebras) when
   $X\in\mathcal{R}$.
3. For $\sigma$-ring $\mathcal{R}$ then
   $\mathcal{F}_{1}:=\{  E \subset X:E \in \mathcal{R}~\text{or}~E^c\in\mathcal{R} \}$
   is a $\sigma$-algebra.
4. For $\sigma$-ring $\mathcal{R}$ then
   $\mathcal{F}_{2}:=\{ E \subset X: E \cap F \in\mathcal{R},~\forall F \in\mathcal{R} \}$
   is a $\sigma$-algebra.

##### Solution

`\begin{proof}[Proof (1).]`
Assuming that $E_{1},E_{2} \in\mathcal{R}$ for $\sigma$-ring $\mathcal{R}$ we
have that
$$
E_{1}\cap E_{2}=(E_{1}\cup E_{2})\setminus \left\{ (E_{1}\setminus E_{2})\cup(E_{2}\setminus E_{1}) \right\} \in\mathcal{R},
$$
since $\mathcal{R}$ is closed under countable unions and differences.
Inductively we can expand this to the $n$ set case (and onwards to countably
many sets) since intersections are associative, i.e.
$$
\bigcap_{j=1}^n E_{j}=\bigcup_{j=1}^nE_{j}\setminus \bigcup_{(i,j)\in \{ 1, \dots , n \}^2}E_{i}\setminus E_{j}.
$$
`\end{proof}`
`\begin{proof}[Proof (2).]`
We need only show that $\mathcal{R}$ is closed under complements. Assuming
$X \in\mathcal{R}$ we have that $X^c=\emptyset=X\setminus X\in\mathcal{R}$. For
all other sets $E \in \mathcal{R}$ we therefore have
$E^c=X\setminus E\in\mathcal{R}$.`\end{proof}`

`\begin{proof}[Proof (3).]`

Since $\mathcal{R}$ is a $\sigma$-ring it is non-empty hence neither is
$\mathcal{F}_1$. Furthermore clearly $\mathcal{F}_{1}$ is closed under
compliments hence all we need is to show $F_{1}$ is closed under countable
unions. Assuming $\{ E_{j} \}_{j=1}^\infty \subseteq \mathcal{F}_{1}$ then
$\forall j$ either $E_{j}\in\mathcal{R}$ or $E_{j}^c\in\mathcal{R}$.  

`\end{proof}`