---
title: Fundamentals of Probability Spaces
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Probability Spaces

A **sample space** $\Omega$ is the set of outcomes of a random experiment.  

:::{.definition data-title="$\sigma$-Algebra"}

A **$\sigma$-algebra** $\mathcal{F}$ is a collection of subspaces of $\Omega$
satisfying the following properties:
1. $\Omega \in\mathcal{F}$
2. $A\in\mathcal{F} \implies A^c\in\mathcal{F}$ (closed under compliments)
3. $A_{i}\in\mathcal{F}$ for countable $i$
   $\implies \cup_{i}A_{i}\in\mathcal{F}$ (closed under countable unions)

:::

A $\sigma$-algebra is the collection of all **measurable** subsets of $\Omega$
hence why we say the combination of $(\Omega,\mathcal{F})$ is a **measurable
space**.  

:::{.definition data-title="[[probability-measure]]"}

A **probability measure** $\mathbb{P}$ is a mapping
$\mathbb{P}:\mathcal{F}\mapsto [0,1]$ satisfying the following properties:
1. $\mathbb{P}(A)\geq \mathbb{P}(\emptyset)=0$;
2. $\mathbb{P}(\Omega)=1$;
3. For countable disjoint $A_{i}\in\mathcal{F}$ then
   $\mathbb{P}(\cup_{i}A_{i})=\sum_{i}\mathbb{P}(A_{i})$.

:::

A probability measure is a mapping assigning a measure on the interval $[0,1]$
for each measurable set. For measure $\mathbb{P}$ on probability space
$(\Omega, \mathcal{F}, \mathbb{P})$ we have the following results:

1. **Monotonicity:** $A\subset B\implies \mathbb{P}(A)\leq \mathbb{P}(B)$;
2. **Subadditivity:**
   $A\subset \cup_{m=1}^\infty A_{m}\implies P(A)\leq \sum_{m=1}^\infty \mathbb{P}(A_{m})$;
3. **Continuity from below:**
   $A_{i}\uparrow A\implies \mathbb{P}(A_{i})\uparrow \mathbb{P}(A)$;
4. **Continuity from above:**
   $A_{i}\downarrow A\implies \mathbb{P}(A_{i})\downarrow \mathbb{P}(A)$.

### Borel $\sigma$-Algebra

Given any set $A \in \mathcal{F}$ we can construct a $\sigma$-algebra by taking
the intersection of all $\sigma$-algebra's containing the set $A$
$$
\sigma(A)=\bigcap_{\{\mathcal{F}:A\in \mathcal{F}\}}\mathcal{F},
$$
which itself must also be a $\sigma$-algebra.

The B
