---
title: General Equilibrium Theory
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

```table-of-contents
title: ## Contents
style: nestedOrderedList # TOC style (nestedList|nestedOrderedList|inlineFirstLevel)
minLevel: 0 # Include headings from the specified level
maxLevel: 3 # Include headings up to the specified level
includeLinks: true # Make headings clickable
hideWhenEmpty: false # Hide TOC if no headings are found
debugInConsole: false # Print debug info in Obsidian console
```

## Preliminary Material

The term **preference relation** is used to refer to orderings that describe
human preferences for one thing over an other.

## Consumer Theory

Consumer theory is a branch of microeconomics that studies _how people decide
what to spend their money on_ based on their preferences and budget
constraints.

:::{.definition data-title="Consumer"}

A **consumer** is a pair $(X,\succeq)$ consisting of **consumption space** $X$
and a **preference relation** $\succeq$ on $X$.  

:::

The set $X$ represents all the possible consumption bundles that the consumer
can choose. The preference relation $\succeq$ represents a description of the
consumers choice behavior (i.e. specifies what the consumer chooses from each
pair of alternative bundles in $X$). We assume throughout that
$X=\mathbb{R}_{+}^L$ where the consumer can choose any non-negative continuous
quantity of $L$ goods.

:::{.definition data-title="Budget Set"}

Letting $p \in X$ and $W\geq 0$ the budget set for a consumer when prices are
$p$ and income is $W$ is
$$
B(p,W):=\{ y \in \mathbb{R}_{+}^L:p \cdot y \leq W \}.
$$

:::

Given a preference relation $\succeq$, the optimal choices of the consumer are
$$
x^*(p,W)=\{  x \in B(p,W):\forall y \in B(p,W),~x \succeq y \}.
$$
The mapping from $(p,W)$ into $x^*(p,W)$ is the consumer's **demand
correspondence**. The theory of the consumer predicts that demand (choices made
from budget sets) are optimal choices according to an underlying (rational)
preference relation.


