---
title: Generated Sigma Algebra
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

:::{.definition data-title="Generated $\sigma$-Algebra"}

Consider a set $\Omega$ and a collection $\mathcal{A}$ of subsets of $\Omega$.
We denote all [[sigma-algebra|$\sigma$-algebra]] containing $\mathcal{A}$ by
$\mathcal{F}_{i},~i \in I$ where $I$ is some index set. There exists a
**smallest $\sigma$-algebra containing $\mathcal{A}$** denoted
$\sigma(\mathcal{A})$ - known as the
[[generated-sigma-algebra|$\sigma$-algebra generated by $\mathcal{A}$]] - which
is the intersection of all other $\sigma$-algebra containing $\mathcal{A}$,
i.e.
$$
\sigma(\mathcal{A}) := \bigcap_{i\in I}\mathcal{F}_{i}.
$$

:::

`\begin{proof}`
To show that $\sigma(\mathcal{A})$ is a $\sigma$-algebra we simply note each of
the following:
1. $\forall i,\Omega \in\mathcal{F}_{i} \implies\Omega \in\cap_{i}\mathcal{F}_{i}$.
2. Let
   $A\in\cap_{i}\mathcal{F}_{i}\implies \forall i, A\in\mathcal{F}_{i}\implies \forall i,A^c\in\mathcal{F}_{i}\implies A^c\in\cap_{i}\mathcal{F}_{i}$.
3. Let
   $\{ A_{n} \}_{n\in\mathbb{N}}\subseteq \cap_{i}\mathcal{F}_{i}\implies \{ A_{n} \}_{n\in \mathbb{N}}\in \mathcal{F}_{i},~\forall i\in I\implies \bigcup_{n\in \mathbb{N}}A_{n}\in \mathcal{F}_{i},~ \forall i\in I\implies \bigcup_{n\in \mathbb{N}}A_{n}\in \bigcap_{i \in I}\mathcal{F}_{i}$.
Hence $\sigma(\mathcal{A})$ is a $\sigma$-algebra and since it is the
intersection of all possible $\sigma$-algebra containing $\mathcal{A}$ it is
the smallest.`\end{proof}`


