---
title: Groundwater Markets - Meeting Notes
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

#### Thursday April 10th 2025

**Notes:**

- Could not find helpful reading from Ulrich Horst.
- Scheduling weekly study sessions with Haosheng to understand MFG.

#### Wednesday April 2nd 2025

**Notes:**

- It is currently too dense but eventually aim to read *Learning Discrete Time
  Major-Minor MF Games*.
- Reading topics:
	- *Ulrich Horst* - Equilibrium in financial markets MF limit order book papers
   (also check similar authors and suggested articles);
	- Fictitious play algorithm (finitely many agents) for solving finite
   equilibrium problems (Ruimeng has papers on this)
   [[handeepfictitiousplay2020]];
	- Dynamic Noncooperative Game Theory textbook

**Action Points:**

- Continue reading into stochastic games by sequentially working through the
  following topics:
	- [[stochastic-calculus|SDE and Itô Calculus]];
	- [[markov-decision-process|Markov Decision Processes (MDP)]] (Single Player
   Discrete Time Games);
	- [[stochastic-control]] (Single Player Continuous Time Games);
	- [[stochastic-games]] (Multiple Player Continuous Time Games);
	- [[mean-field-games]] (Infinite Player Continuous Time Games).

