---
title: Heat Equation
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Heat Equation
*References:*
[Stanford Notes](https://web.stanford.edu/class/math220b/handouts/heateqn.pdf)

The (homogeneous) **heat equation** describes the diffusion of heat in general
$n$-dimensional continuous medium.

:::{.definition data-title="Heat Equation"}

Denoting the heat of material at location $\boldsymbol{x}$ at time $t$ by
$u(t,x)$ the **heat equation** (**diffusion equation**) gives the heat
diffusion dynamics as
$$
u_{t}-\Delta u=0,
$$
where $\Delta$ denotes the [[laplace-operator]].

:::

The **non-homogeneous heat equation** is
$$
u_{t}-\Delta u=f,
$$
subject to appropriate initial boundary conditions. Considering the
1-dimensional case for intuition we have
$$
u_{t}-ku_{xx}=0;~~k>0,
$$
where $u(x, t)$ represents the temperature at point $x$ and time $t$ in a long,
thin, perfectly insulated bar of material. Some of the elementary properties of
the diffusion equation are:

1. **Linearity:** If $u_{1}$ and $u_{2}$ are solutions, then so to is
   $c_{1}u_{1}+c_{2}u_{2}$ for any constants $c_{1}$ and $c_{2}$;
2. **Second Order Equation**;
3. **Parabolic Equation:** Characteristics are given by $\tau=\text{constant}$
   thus information propagates along these lines in $(x,\tau)$ spaces, and if
   change is made to $u$ at some point, its effect is felt instantaneously
   everywhere else;
4. **Analytic Function Solutions.**

To derive the heat (diffusion) equation consider the diffusion of dye through a
liquid, where the dye moves from high concentration to low concentration. Let
$u(x,t)$ be the concentration (mass per unit length) of th dye at position $x$
in the pipe at time $t$. The total mass of dye in the pipe from $x_{0}$ to
$x_{1}$ at time $t$ is given by
$$
M(t)=\int_{x_{0}}^{x_{1}}{u(x,t)}~d{x} \implies \frac{\partial M}{\partial t}=\int_{x_{0}}^{x_{1}}{u_{t}(x,t)}~d{x}.
$$


