---
title: Helly's Selection Theorem
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Helly's Selection Theorem

**Helly's Selection Theorem** is the first of several results (including
[[tightness]] and its resulting theorems) forming a sort of **compactness**
result for certain families of [[probability-measure|probability measures]].
The theorem essentially states that any sequence of distribution functions
contains a subsequence that converges to a right-continuous non-decreasing
function.  

:::{.theorem data-title="Helly's Selection Theorem"}

Any sequence of distribution functions $\{ F_{n} \}$ contains a convergent
subsequence $\{ F_{n} \}$ contains a convergent subsequence
$\{  F_{n_{k}} \}: F_{n_{k}}(x) \to F(x)$ as $k \to \infty$ for some
right-continuous non-decreasing function $F$. Convergence holds
$\forall x \in C(F)$.

:::

##### Helly's Selection Theorem & Weak Convergence

The limit $F$ of a sequence of distribution function $\{  F_{n} \}$ is itself a
distribution function when the sequence $\{  F_{n} \}$ is [[tightness|tight]].
This is helpful as we then have that any sequence of random variables
$\{  X_{n} \}$ whose distribution functions $\{ F_{n} \}$ contain a subsequence
$\{  X_{n_{k}} \}$ who [[convergence-in-law|converge weakly]].  