---
title: Hölder Inequality
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Hölder Inequality
In mathematical analysis, the **Hölder inequality** is a fundamental inequality
between integrals and an indispensable tool for the study of
[[lebesgue-space]].

:::{.theorem data-title="Hölder's Inquality"}

For measure space $(S,\Sigma,\mu)$ let $p,q\in[1,\infty]$ with $\frac{1}{p}+\frac{1}{q}=1$ (known as Hölder conjugates).  Then, for all measurable real or complex valued functions $f$ and $g$ on $S$ we have that $$\|fg\|_{1}\leq \|f\|_{p}\cdot\|g\|_{q}.$$Additionally, if $p,q\in(1,\infty)$ and $f\in L^p(\mu)$, $g \in L^q(\mu)$ then we obtain equality iff $|f|^p$ and $|g|^q$ are linearly dependent in $L^1(\mu)$.

:::

By considering the $L_{p}(\Omega, \mathcal{F}, \mathbb{P})$ space of random
variables $X:\Omega \to \mathbb{R}$ where we use the $L_{p}$ norm
$$
\lVert X \rVert _{p}:=(\mathbb{E}{\lvert X \rvert ^p})^{1/p},
$$
we obtain the equivalent result detailed below.

:::{.theorem data-title="Hölder's Inequality in Probability Space"}

Let $X$ and $Y$ be random variables, $p,q \in (1,\infty)$ and $\frac{1}{p}+\frac{1}{q}=1$.  We have that $$|\mathbb{E}[XY]|\leq \mathbb{E}|XY|\leq (\mathbb{E}|X|^p)^{1/p}\cdot (\mathbb{E}|Y|^q)^{1/q}.$$

:::

*PROOF:*
First assume $X,Y$ are non-negative (extension to negative by taking modulus).
Since $p,q>1$ we have that $x \mapsto x^p$ is convex thus by
[[jensen-inequality]]
$$
\begin{align}
\int_{}^{}{XY}~d{\mathbb{P}}  & = \left( \int_{}^{}{Y^q}~d{\mathbb{P}} \right)\int_{}^{}{XY^{1-q}\cdot \frac{Y^q}{\int_{}^{}{Y^q}~d{\mathbb{P}}}}~d{\mathbb{P}}  \\
 & \leq \left( \int_{}^{}{Y^q}~d{\mathbb{P}} \right)\left( \int_{}^{}{X^pY^{p(1-q)}\cdot \frac{Y^q}{\int_{}^{}{Y^q}~d{\mathbb{P}}}}~d{\mathbb{P}} \right)^{\frac{1}{p}}  \\
 & =\left( \int_{}^{}{Y^q}~d{\mathbb{P}} \right)\left( \int_{}^{}{\frac{X^p}{\int_{}^{}{Y^q}~d{\mathbb{P}}}}~d{\mathbb{P}} \right) ^{\frac{1}{p}}.
\end{align}
$$
Thus we obtain
$$
\int_{}^{}{XY}~d{\mathbb{P}}\leq \left( \int_{}^{}{X^p}~d{\mathbb{P}} \right)^{\frac{1}{p}}\left( \int_{}^{}{Y^q}~d{\mathbb{P}} \right)^{\frac{1}{q}}.
$$
$\square$

