---
title: Infimum and Supremum
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Infimum and Supremum

## Extended Real Sequences

### Boundedness of Real Sequences

Consider the extended real sequence
$\{ x_{n} \}_{n \in \mathbb{N}}\subseteq\overline{\mathbb{R}}=:\mathbb{R}\cup \{ \pm \infty \}$.
The number $u \in \mathbb{R}$ is said to be an **upper bound** of the sequence
if $x_{n}\leq u$ for all $n \in \mathbb{N}$. We say that the sequence is
**bounded above**. Similarly, the number $l \in \overline{\mathbb{R}}$ is said
to be **lower bound** of the sequence if $x_{n}\geq l$ for all
$n \in \mathbb{N}$. We say that the sequence is **bounded below**. A sequence
is **bounded** if it is both bounded above and below.
### Supremum and Infimum of Real Sequences

:::{.definition data-title="Supremum of Real Sequences"}

The **supremum** $\sup_{n\in \mathbb{N}}{x_{n}}$ of extended real sequence
$x_{n}$ is the unique **least upper bound**, that is it satisfies
1. $\sup_{n \in \mathbb{N}}{x_{n}}$ is an upper bound of sequence $x_{n}$; and
2. For set of upper bounds $U$ we have that
   $\sup_{n \in \mathbb{N}}x_{n}\leq u$ for all $u \in U$.

:::

:::{.definition data-title="Infimum of Real Sequences"}

The **infimum** $\sup_{n\in \mathbb{N}}{x_{n}}$ of extended real sequence
$x_{n}$ is the unique **greatest lower bound**, that is it satisfies
1. $\inf_{n \in \mathbb{N}}{x_{n}}$ is a lower bound of sequence $x_{n}$; and
2. For set of lower bounds $L$ we have that
   $\inf_{n \in \mathbb{N}}x_{n}\geq l$ for all $l \in L$.

:::

These are fundamental definitions in [[measure-theory-notes]] and
[[real-analysis]] where they form the bases for defining limits, continuity and
integrals.  

:::{.theorem data-title="Infimum and Supremum Inequality"}

For a extended real sequence $\{ x_{n} \}_{n \in \mathbb{N}}$ we have that
$$
\inf_{n \in \mathbb{N}}{x_{n}}\leq x_{n}\leq \sup_{n \in \mathbb{N}}{x_{n}};~~\forall n.
$$

:::

*PROOF:*
Assuming the result is false then $\inf_{}x_{n}>\sup{x_{n}}$. However since the
infimum is a lower bound and the supremum is an upper bound we have
$\inf_{}{x_{n}}\leq x_{n}$ and $\sup{x_{n}}\geq x_{n}{}$ for all
$n \in \mathbb{N}$, thus
$$
\inf_{}{x_{n}}\leq x_{n}\leq \sup_{}{x_{n}}<\inf_{}{x_{n}},
$$
which is a contradiction $\rightarrow\leftarrow$.
$\square$

:::{.theorem data-title="Order Preservation"}

For sequences where $x_{n}\leq y_{n}$ for all $n$ we have
$$
\begin{align}\inf_{}{x_{n}}&\leq \inf_{}{y_{n}}\\ \sup_{}{x_{n}}&\leq \sup_{}{y_{n}}.\end{align}
$$

:::

*PROOF:*
Suppose this is not the case. Let $m$ be index such that
$y_{m}=\inf_{}{y_{n}}$. Then
$$
\inf_{}{x_{n}}\leq x_{m}\leq y_{m}=\inf_{}{y_{n}},
$$
which is a contradiction $\rightarrow\leftarrow$. A similar result holds for
the supremum.
$\square$

:::{.theorem data-title="Inequalities of Sums"}

For sequences $\{ x_{n} \},\{ y_{n} \}$ we have
$$
\begin{align}\sup(x_{n}+y_{n}) & \leq \sup_{}{x_{n}}+\sup_{}{y_{n}} \\ \inf_{}{(x_{n}+y_{n})} & \geq \inf_{}{x_{n}}+\inf_{}{y_{n}}.\end{align}
$$

:::

*PROOF:*
Let $m$ be index such that $\sup_{}{(x_{n}+y_{n})}=x_{m}+y_{m}$ then
$$
\sup_{}{(x_{n}+y_{n})}= x_{m}+y_{m}\leq \sup_{}{x_{n}}+\sup_{}{y_{n}}.
$$
Similarly, let $m$ be index such that $\inf_{}{(x_{n}+y_{n})}=x_{m}+y_{m}$ then
$$
\inf_{}{(x_{n}+y_{n})}=x_{m}+y_{m}\geq \inf_{}{x_{n}}+\inf_{}{y_{n}}.
$$
$\square$

:::{.theorem data-title="Inequalities of Product"}

For sequences $\{ x_{n} \}, \{ y_{n} \}$ we have
$$
\begin{align}\sup_{}{(x_{n}\cdot y_{n})}\leq \sup_{}{x_{n}}\cdot \sup_{}{y_{n}}\\ \inf_{}{(x_{n}\cdot y_{n})}\geq \inf_{}{x_{n}}\cdot \inf_{}{y_{n}}.\end{align}
$$

:::

*PROOF:*
The proof is similar to the proposition of inequalities of sums.
$\square$

## Sets

### Supremum and Infimum of Sets



## Limit Supremum and Limit Infimum

The **limit supremum** $\limsup_{n \to \infty}{x_{n}}$ of extended real
sequence $x_{n}$ is defined as
$$
\limsup_{n \to \infty}{x_{n}}=\lim_{ n \to \infty } \sup_{k \geq n}{x_{k}}.
$$
The **limit infimum** $\liminf_{n \to \infty}{x_{n}}$ of extended real sequence
$x_{n}$ is defined as
$$
\liminf_{n \to \infty}{x_{n}}=\lim_{ n \to \infty } \inf_{k \geq n}{x_{k}}.
$$
Intuitively, we are considering the supremum and infimum of the tail
$\{ x_{k} \}_{k \geq n}$ for each step $n$ and looking at the limit of the
supremum and infimum as $n \to \infty$. They are the largest and smallest
numbers respectively that the sequence gets arbitrarily close to **infinitely
often**.

:::{.theorem data-title="Limsup and Liminf Existence"}

The limit supremum and limit infimum always exist for extended real sequences.

:::

Since the sequences $\{ \sup_{k \geq n}{x_{k}} \}_{n\in \mathbb{N}}$ and
$\{ \inf_{k \geq n}{x_k} \}_{n \in \mathbb{N}}$ are non-increasing and
non-decreasing respectively in $n$ we can introduce the following extension to
the definitions above
$$
\begin{align}
\limsup_{n \to \infty}{x_{n}} & =\inf_{n\in \mathbb{N}}\sup_{k \geq n}{x_{k}} \\
\liminf_{n \to \infty}{x_{n}} & =\sup_{n\in \mathbb{N}}\inf_{k \geq n}{x_{k}}.
\end{align}
$$

:::{.theorem data-title="Limsup and Liminf Inequality"}

For an extended real sequence $\{  x_{n} \}\subseteq\overline{\mathbb{R}}$ the
following inequality always holds
$$
\liminf_{n \to \infty}{x_{n}}\leq \limsup_{n \to \infty}{x_{n}}.
$$

:::

*PROOF:*
We define $i_{n}=\inf_{k \geq n}{x_{k}}$ and $s_{n}=\sup_{k \geq n}{x_{k}}$.
Since $\{ i_{n} \}$ is increasing we have that
$\lim_{ n \to \infty }i_{n}=\sup_{n}{i_{n}}$. Similarly, since $\{ s_{n} \}$ is
decreasing we have that $\lim_{ n \to \infty }s_{n}=\inf_{n}{s_{n}}$ and from
[[|previous results]] we have that
$\lim_{ n \to \infty }i_n=\sup_{n}{i_{n}}\leq \inf_{n}{s_{n}}=\lim_{ n \to \infty }s_{n}$,
which gives the result.
$\square$

:::{.theorem data-title="Convergence Criterion $(\star)$"}

For an extended real sequence $\{  x_{n} \}\subseteq\overline{\mathbb{R}}$
assume that $\liminf_{}{x_{n}}=\limsup_{}{x_{n}}$. Then the limit
$\lim_{ n \to \infty }x_{n}$ exists in $\overline{\mathbb{R}}$ and
$$
\limsup_{}{x_{n}}=\liminf_{}{x_{n}}=\lim_{ }x_{n}.
$$

:::

*PROOF:*


:::{.theorem data-title="Limsup and Liminf under Inequalities"}

For extended real sequences $\{ x_{n} \}, \{ y_{n} \}$ where one is dominated
by the other, that is $x_{n}\leq y_{n}$ for all $n$ then
$$
\begin{align}\liminf_{}{x_{n}}\leq \liminf_{}{y_{n}} \\ \limsup_{}{x_{n}}\leq \limsup_{}{y_{n}}\end{align}.
$$

:::

*PROOF:*
For all $n$ defining $m_{n}$ such that $y_{m_{n}}:=\inf_{k\geq n}{y_{n}}$ we
have that
$$
i_{n}^x:=\inf_{k \geq n}{x_{k}}\leq x_{m_{n}}\leq y_{m_{n}}=\inf_{k \geq n}{y_{n}}=:i_{n}^y.
$$
Similarly, defining $k_{n}$ such that $\sup_{k \geq n}i_{n}^x=:i_{k_{n}}$ we
have that
$$
\sup_{k \geq n}i_{n}^x=i_{k_{n}}^x\leq i_{k_{n}}^y\leq \sup_{k \geq n}{i_{n}^y},
$$
giving the first result.  A similar procedure gives the second result.
$\square$

:::{.theorem data-title="Limsup and Liminf of Sums and Product"}

For extended real sequences $\{ x_{n} \}, \{ y_{n} \}$ the following
inequalities hold
$$
\begin{align}\limsup_{}{(x_{n}+y_{n})}\leq \limsup_{}{x_{n}}+\limsup_{}{y_{n}} \\ \liminf{(x_{n}+y_{n})}\geq \liminf_{}{x_{n}}+\liminf_{}{y_{n}}.\end{align}
$$

:::

*PROOF:*




:::{.theorem data-title="Negation Equality"}

For extended real sequence $\{ x_{n} \}$ we have that
$$
\limsup_{}{-x_{n}}=-\liminf_{}{x_{n}}.
$$

:::

*PROOF:*


## Sequences of Sets

Consider a sequence of sets $\{ A_{n} \}_{n\in \mathbb{N}}$. In the context of
the limsup and liminf of sets, the supremum of the sequence
$\{ A_{n} \}_{n\in \mathbb{N}}$ is the smallest possible upper bound for every
element (set) of the sequence, i.e the smallest set containing each $A_{n}$
which by definition is
$$
\sup_{n \geq1}A_n= \bigcup_{n=1}^\infty A_n.
$$
Similarly, the infimum of the sequence $\{ A_{n} \}_{n\in\mathbb{N}}$ is the
largest possible lower bound of every element (set) of the sequence, i.e. the
smallest collection of elements in each $A_{n}$ which by definition is
$$
\inf_{n \geq 1} A_{n}=\bigcap_{n=1}^\infty A_n.
$$

### Set Theoretic Limit Supremum & Infimum

Generally the limit supremum and limit infimum consider what happens to the
supremum and the infimum as you disregard an increasingly larger finite
collection of sets at the start of the sequence. So for the supremum we
consider the union as we increase the lower bound
$$
\limsup_{ n \to \infty } A_{n}=\lim_{ n \to \infty } \bigcup_{m=n}^\infty A_{m}.
$$
However, since the sequence $\{ B_{n} \}_{n \in \mathbb{N}}$ where
$B_{n}=\bigcup_{m=n}^\infty A_{m}$ is monotone decreasing, this limit is
equivalent to the intersection and so
$$
\limsup_{ n \to \infty } A_{n}=\lim_{ n \to \infty } \bigcup_{m=n}^\infty A_{m}=\bigcap_{n=1}^\infty \bigcup_{m=n}^\infty A_{m}.
$$
Similarly, for the infimum we consider the intersection as we increase the
lower bound
$$
\liminf_{ n \to \infty } A_{n}=\lim_{ n \to \infty } \bigcap_{m=n}^\infty A_{m}.
$$
Again, since the sequence $\{ B_{n} \}_{n \in \mathbb{N}}$ where
$B_{n}:=\bigcap_{m=n}^\infty A_{m}$ is monotone increasing, this limit is
equivalent to the unions as so
$$
\liminf_{ n \to \infty } A_{n} = \lim_{ n \to \infty } \bigcap_{m=n}^\infty A_{m}=\bigcup_{n=1}^\infty \bigcap _{m=n}^\infty A_{m}.
$$

## Probability Theory

### Limsup and Liminf of Probability

An important notion in [[probability-theory|probability theory]], specifically
in the [[convergence-of-random-variables|convergence of random variables]] and
the [[borel-cantelli-lemma|Borel-Cantelli lemma]] is the notion of events
occurring infinitely often which, somewhat counterintuitively, is equivalent to
the notion of even limit supremum, i.e. for sequence of events $A_{n}$, we have
that
$$
\mathbb{P}(\{ A_{n}\text{ occurs }i.o \}) = \mathbb{P}\left(\limsup_{ n \to \infty } A_{n}\right).
$$
A powerful tool for constructing proofs that events occur i.o. is the following
theorem.

:::{.theorem data-title="Probability and Limsup / Liminf Relations"}

For a sequence of events $\{ A_{n} \}_{n \in \mathbb{N}}$ we have that
$$
\mathbb{P}\left(\liminf_{ n \to \infty }  A_{n}\right) \leq \liminf_{ n \to \infty } \mathbb{P}(A_{n})\leq \limsup_{ n \to \infty }\mathbb{P}(A_{n})\leq \mathbb{P}\left( \limsup_{ n \to \infty } A_{n} \right).
$$

:::

*PROOF:*
The second inequality is clear by definition hence we show the first (i) and
third (iii) inequalities.
For (iii) we have that
$$
\begin{align}
\limsup_{ n \to \infty } \mathbb{P}(A_{n}) & =\inf_{n\geq 1} \sup_{m \geq n}\mathbb{P}(A_{m})\stackrel{(\star)}{\leq} \inf_{n\geq 1}\sup_{m \geq n}\mathbb{P}\left( \bigcup_{k=m}^\infty A_{k} \right) \\
 & =\inf_{n \geq 1}\mathbb{P}\left( \bigcup _{k=n}^\infty A_{k} \right)=\mathbb{P}\left( \bigcap_{n=1}^\infty \bigcup_{k=n}^\infty A_{k} \right)=\mathbb{P}\left( \limsup_{ n \to \infty }A_{n} \right) ,
\end{align}
$$
where for $(\star)$ we used the monotonicity of measure and making use of the
fact that $\bigcup_{k=n}^\infty A_{k}\downarrow$ as $n\uparrow$.
For (i) we simply replace $A_{n}$ with its complement
$$
\limsup_{ n \to \infty } \mathbb{P}(A_{n}^c) \leq \mathbb{P}\left( \limsup_{ n \to \infty } A_{n}^c \right),
$$
and then we obtain the result since
$$
\mathbb{P}\left( \liminf_{ n \to \infty } A_{n} \right) =1-\mathbb{P}\left( \limsup_{ n \to \infty } A_{n}^c \right) \leq 1-\limsup_{ n \to \infty } \mathbb{P}(A_{n}^c)=\liminf_{ n \to \infty } (1-\mathbb{P}(A_{n}^c))=\liminf_{ n \to \infty } \mathbb{P}(A_{n}).
$$
`\end{proof}`
