---
title: Inner Product Space
author: John Robin Inston
date: 2026-09-06
number-sections: true
---

## Inner Product

:::{.definition data-title="Inner Product"}

Given [[vector-spaces|linear vector space]] $\mathcal{V}$ an 
**inner product** $\left< \cdot, \cdot \right>:\mathcal{V}\times\mathcal{V} 
\to \mathbb{R}$ is a mapping satisfying the following properties for all 
$v_{1}, v_{2}, v_{3} \in \mathcal{V}$:

1. Symmetry: $\left< v_{1}, v_{2} \right> = \left< v_{2}, v_{1} \right>$;
2. Non-negativity: $\left< v_{1}, v_{1} \right> \geq 0$;
3. Non-Degeneracy: $\left< v_{1}, v_{1} \right> =0 \iff v_{1}=0$; and
4. Linearity: $\left<  \alpha v_{1}, v_{2} + v_{3} \right> = 
   \alpha \left<  v_{1}, v_{2} \right> + \alpha \left< v_{1}, v_{3} \right> = 
   \alpha \left<  v_{1}, v_{2} + v_{3} \right>.$

:::

**Note:** Every **inner product** creates a **norm** satisfying: 
$\lVert v \rVert = \sqrt{ \left< v, v \right> }.$

## Inner Product Space

:::{.definition data-title="Inner Product Space"}

A vector space with a corresponding inner product is known as an 
**Inner Product Space**.

:::

:::{.definition data-title="Complete Inner Product Space"}

An inner product space is said to be **complete** if every [[cauchy-sequence]] 
$\{v_{n}\}$ in the inner product space, there exists a limit $v \in \mathcal{V}$ such that $\lim_{n \to \infty} v_{n} = v$.

:::

A complete inner product space is known as a [[hilbert-space]].

### Inner Product Space Results

Some important inner-product space results include:

1. The [[cauchy-schwartz-inequality]]: $\lvert \left< v_{1}, v_{2} \right> 
   \rvert\leq \lVert v_{1} \rVert \cdot \lVert v_{2} \rVert$.
2. The [[triangle-inequality]]: $\lVert  v_{1}+v_{2} \rVert \leq \lVert v_{1} 
   \rVert + \lVert  v_{2} \rVert$.
