---
title: Instantaneous Rates
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Instantaneous Forward Rate
The **instantaneous forward rate** $f(t,T)$ describes the forward rate in
$[T,T+d]$ contracted at $t$ when $dt$ is small enough. All instantaneous rates
are built upon the continuously compounded interest model. From the definition
we hav that
$$
f(t,t)=\lim_{ dt \to 0 }R(t,T, T+dt)=\lim_{ dt \to 0 }\frac{1}{dt} \log\left(  \frac{p(t,T)}{p(t,T+dt)} \right)=- \frac{{\partial \log p(t,T)}}{\partial T} .
$$
### Instantaneous Short Rate
The **instantaneous short rate** $r(t)$ describes the spot rate in $[t,t+dt]$
contracted at $t$ when $dt$ is small enough. Clearly plugging $T=t$ into the
instantaneous forward rate $f(t,T)$ gives
$$
r(t)=f(t,t).
$$
We can interpret this as the spot interest rate in a future infinitesimal time
interval, so it is exactly the risk-free interest rate $r$ we refer to in the
context of options pricing.

When one opens a savings account, denote the amount of money in the account at
time $t$ as $S_{t}^0$, then it is clear that
$$
dS_{t}^0=r_{t}S_{t}^0dt,
$$
where $r_{t}=r(t)$ is the short rate. As a result, $S_{t}^0$ can be represented
in terms of the short rate as
$$
S_{t}^0=\exp\left( \int _{0}^tr_{s} \, ds  \right),
$$
which tells us how to discount using the short rate.
