---
title: Itô Process
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Itô Process
## Motivation
References: [[oksendal-pdf]]

Consider the probability space $(\Omega, \mathcal{F}, \mathbb{P})$ and let
$(\boldsymbol{B}(t))=(B_{1}(t), \dots, B_{n}(t))$ be $n$-dimensional (standard)
[[brownian-motion]]. Define
$\boldsymbol{\mathcal{F}}(t)=\boldsymbol{\mathcal{F}}^{(n)}(t)$ to be the
[[filtration|filtration]] generated by
$(B_{i}(s))_{{1\leq i \leq n}, 0 \leq s \leq t}$. Recall that we call the
**natural filtration** of $(\boldsymbol{B}(t))$ and interpret as the history of
the process $\boldsymbol{B}(t)$ up to time $t$.  

Our aim is to construct the integral $I(f)=\int_{S}^{T}{f_{t}}~d{B_{t}}$ for a
general process $f_{t}$ in order to define an Itô process however this is
somewhat challenging since $B_{t}$ can be shown to be nowhere differentiable
and have infinite variation meaning that we cannot use a [[riemann-integral]]
or [[lebesgue-integral]]. Instead we construct the **Itô integral** as the
limit in mean square (or probability) of simple processes (akin to Riemann
sums) where the integrand is evaluated at the left endpoint of each
subinterval. This ensures the process is **non-anticipating** (adapted to the
filtration) which preserves [[martingale-theory|martingale]] properties.

## Itô Integral Construction

We begin by defining the space of all **measurable (actually progressive),
adapted and $\mathcal{L}_{2}$ processes** for which we can define the Itô
integral. Let $\mathcal{V}=\mathcal{V}(S,T)$ be the class of functions
$$
\mathcal{V}(S,T):=\{f(t,\omega):[0,\infty) \times \Omega \to \mathbb{R}\},
$$
such that:
1. $(t, \omega)\to f(t, \omega)$ is
   $\mathcal{B}\times\mathcal{F}$-[[measurable-function|measurable]], where
   $\mathcal{B}$ denotes the [[borel-sigma-algebra]] on $[0,\infty)$;
2. $f(t,\omega)$ is $\mathcal{F}_{t}$-[[filtration|adapted]];
3. $\mathbb{E}[\int_{S}^T f(t,\omega)^2dt]<\infty$.

For (3) say $f \in \mathcal{L}_{2}([S,T]\times \Omega)$ since
$\left< f_{t},g_{t} \right> = \mathbb{E}\left[ \int_{S}^T f_{t}g_{t} ~dt \right]$
is the inner product on such a space. Our goal is to define the **stochastic
integral** $I(f)=\int_{S}^T f_{t}dB_{t}$ for a general process $f$ in such a
[[hilbert-spaces|Hilbert space]].

Our construction process is as follows, first consider defining such an
integral for an elementary process and then extend it to general processes in
$\mathcal{V}$. The main thought is to find a **dense subset** of the Hilbert
space and define the stochastic integral on it to prove that it is actually an
[[isometry|isometry]]. We are then able to **extend** it as the isometry to the
whole Hilbert space.

:::{.definition data-title="Elementary Processes"}

A process $(X_{t})$ is called an **elementary adapted process** if it can be
written in the form
$$
\varphi_{t}(\omega)=\sum_{j \geq 0} e_{j}\mathbb{1}_{\left[\frac{j}{2^n}, \frac{{j+1}}{2^n}\right)}(t),
$$
where $n\in \mathbb{N}$ and each $e_{j}\in \mathcal{F}_{t}$ and
$e_{j}\in\mathcal{L}_{2}$.

:::

This is a slightly changed step function where $e_j$ are now a collection of
$\mathcal{F}$ measurable random variables with finite over the
[[dyadic-number|dyadic number]] partition. For elementary functions we can
define the stochastic integral
$$
\int_{S}^T \varphi_{t}~dB_{t}=\sum_{j \geq 0}e_{j}[B_{t_{j+1}}-B_{t_{j}}],
$$
where we specify
$$
t_{k}=t_{k}^{(n)}=\begin{cases}
\frac{k}{2^n} & \text{if }S\leq \frac{k}{2^n}\leq T \\
S & \text{if } \frac{k}{2^n} < S \\
T & \text{if } \frac{k}{2^n}>T.
\end{cases}
$$
At this point it is natural to approximate a given function $f(t,\omega)$ by
$$
\sum_{j}f_{t_{j}^*}(\omega)\cdot \mathbb{1}_{[t_{j},t_{j+1})}(t),
$$
where the points $t_{j}^*\in[t_{j}, t_{j+1}]$ allowing us to define the
integral $\int_{S}^T f_{t}(\omega)dB_{t}(\omega)$ as the limit (in
$\mathcal{L}_{2}$) of
$\sum_{j}f_{t_{j}^*}(\omega)[B_{t_{j+1}}-B_{t_{j}}](\omega)$ as $n \to \infty$.
However, unlike with the Riemann-Stieltjes Integral our choice of $t_{j}^*$
impacts our final result, as shown with the following example.

**Example (Choice of $t^*$ on interval)**
We define
$$
\varphi^{(1)}_{t}(\omega)=\sum_{j \geq 0} B_{\frac{j}{2^n}}(\omega)\mathbb{1}_{[\frac{j}{2^n}, \frac{{j+1}}{2^n})}(t)\quad \& \quad \varphi_{t}^{(2)}(\omega) = \sum_{j \geq 0} B_{\frac{j+1}{2^n}}(\omega)\mathbb{1}_{[\frac{j}{2^n}, \frac{{j+1}}{2^n})}(t).
$$
Then from independent increments we have
$$
\mathbb{E}\left[ \int_{0}^T \varphi _{t}^{(1)}(\omega)~dB_{t}(\omega)\right]=\sum_{j \geq 0 }\mathbb{E}[B_{t_{j}}(B_{t_{j+1}}-B_{t_{j}})]=0.
$$
However
$$
\mathbb{E}\left[ \int_{0}^T \varphi^{(2)}_{t}(\omega)~dB_{t}(\omega) \right]=\sum_{j \geq 0 }\mathbb{E}[B_{t_{j+1}}\cdot(B_{t_{j+1}}-B_{t_{j}})]=T.
$$
The two most useful choices have been found to be the *left end point*
$t_{j}^* = t_{j}$ leading to the Itô integral (the primary consideration in
this note and throughout this topic) and the *mid point*
$t_{j}^*=(t_{j}+t_{j+1})/2$ leading to the *Stratonovich integral*.  

To begin our extension from the elementary functions we make the following
important observation.

:::{.theorem data-title="Itô Isometry (Elementary Functions)"}

If $\varphi_{t}(\omega)$ is bounded and elementary then we have
$$
\mathbb{E}\left[ \left( \int_{S}^T \varphi_{t}(\omega )dB_{t} \right) ^2 \right] =\mathbb{E}\left[ \int_{S}^T \varphi_{t}^2(\omega )dt \right].
$$

:::

*PROOF:*
Define $\Delta B_{j}=B_{t_{j+1}}-B_{t_{j}}$ and then note that
$$
\mathbb{E}[e_{i}e_{j}\Delta B_{i}\Delta B_{j}]=\begin{cases}0 & \text{if }i \neq j \\ \mathbb{E}[e_{j}^2]\cdot(t_{j+1}-t_{j}) & \text{if }i = j, \end{cases}
$$
from independent increments. Thus we have
$$
\begin{align}\mathbb{E}\left[ \int_{S}^T \varphi_{t}~dB_{t} \right]=\sum_{i,j}\mathbb{E}[e_{i}e_{j}\Delta B_{i}\Delta B_{j}]=\sum_{j}\mathbb{E}[e_{j}^2]\cdot(t_{j+1}-t_{j})=\mathbb{E}\left[ \int_{S}^T \varphi_{t}^2~dt \right],\end{align}
$$
completing the proof.
$\square$

### Step 1: Bounded Continuous Processes

Letting $g \in \mathcal{V}$ be bounded and $g_{\cdot}(\omega)$ continuous for
each $\omega$. Then there exist elementary functions
$\varphi^{(n)}\in \mathcal{V}$ such that
$$
\mathbb{E}\left[ \int_{S}^T (g_{t} - \varphi_{t})^2dt \right]\to 0\quad \text{as}\quad n \to \infty.
$$
To see this define
$\varphi_{t}^{(n)}(\omega)=\sum_{j}g_{t_{j}}(\omega)\cdot \mathbb{1}_{[t_{j},t_{j+1})}(t)$
which is elementary since $g \in\mathcal{V}$ and
$$
\int_{S}^T(g-\varphi_{n})^2dt\to 0\quad \text{as}\quad n \to \infty,
$$
for each $\omega$ (pointwise) since $g_{\cdot}(\omega)$ is pointwise
continuous. Hence the result follows by bounded convergence.

### Step 2: Bounded Processes

Let $h \in \mathcal{V}$ be bounded. Then there exist bounded functions
$g^{(n)} \in \mathcal{V}$ such that $g_{t}^{(n)}(\omega)$ is continuous for all
$\omega$ and $n$, and
$$
\mathbb{E}\left[ \int_{S}^T (h_{t} - g_{t}^{(n)})^2dt \right]\to 0.
$$
To see this suppose $\lvert h_{t}(\omega) \rvert\leq M$ for all $(t, \omega)$.
For each $n$ let $\phi^{(n)}$ be a non-negative, continuous function on
$\mathbb{R}$ such that:
1. $\phi^{(n)}(x)=0$ for $x \leq -\frac{1}{n}$ and $x \geq 0$; and
2. $\int_{\mathbb{R}}\phi^{(n)}(x)~dx =1.$
Define
$$
g_{t}^{(n)}(\omega)=\int_{0}^t\phi^{(n)}_{t}(s-t)h_{s}(\omega)ds.
$$
Then $g_{\cdot}^{(n)}(\omega)$ is continuous for each $\omega$ (pointwise) and
$\lvert g_{t}^{(n)}(\omega) \rvert\leq M$. Since $h \in \mathcal{V}$ we show
that $g^{(n)}_{t}(\cdot)$ is adapted (e.g. Karatzas and Shreve (1991); pg 133).
Moreover
$$
\int_{S}^T(g^{(n)}_{s}(\omega)-h_{s}(\omega))^2ds\to 0 \quad \text{pointwise as}\quad n\to \infty,
$$
since $\{ \phi_{n} \}$ constitutes an approximate identity (e.g. Hoffman
(1962); pg 22). Hence, by bounded convergence we obtain the result.

### Step 3: General Process

Let $f \in\mathcal{V}$. Then there exists a sequence
$\{ h^{(n)} \}\subset\mathcal{V}$ such that $h_{n}$ is bounded for each $n$ and
$$
\mathbb{E}
\left[ \int_{S}^T(f-h^{(n)})^2 dt \right]\to 0 ~~\text{as}~~ n \to \infty.
$$
To see this we simply put
$$
h^{(n)}_{t}(\omega) = \begin{cases}
-n & \text{if } f_{t}(\omega)<-n \\
f_{t}(\omega) & \text{if } -n \leq f_{t}(\omega)\leq n \\
n & \text{if } f_{t}(\omega)>n,
\end{cases}
$$
and the conclusion follows by
[[dominated-convergence-theorem|dominated convergence]].

## Itô Integral
### Itô Integral

:::{.definition data-title="Itô Integral"}

For $f\in\mathcal{V}(S,T)$ the Itô integral from $S$ to $T$ is defined by
$$
\int_{S}^Tf(t, \omega)dB_{t}(\omega) =\lim_{ n \to \infty } \int_{S}^T \phi_{n}(t, \omega)dB_{t}(\omega),
$$
where the limit is taken in $L^2$ and $\{ \phi_{n} \}$ is a sequence of
elementary functions such that
$$
\mathbb{E}\left[ \int_{S}^T (f(t, \omega)-\phi_{n}(t, \omega))^2dt \right] \to 0,
$$
as $n \to \infty$.

:::

### Itô Isometry

:::{.theorem data-title="Itô's Isometry"}

For $f \in\mathcal{V}(S,T)$ we have that
$$
\mathbb{E}\left[ \left( \int_{S}^T f(t,\omega )dB_{t} \right) ^2 \right] =\mathbb{E}\left[ \int_{S}^T f^2(t,\omega )dt \right].
$$

:::

### Itô Integral Properties

## Itô Process




A **Stochastic Differential Equation (SDE)** written in differential form is
$$
dX_{t}=\mu(t, X_{t})dt + \sigma(t, X_{t})dB_{t},
$$
with initial value $X_{0}=x$. This is not rigorous since we have not formally
defined $dB_{t}$. Instead this expression derives its meaning from the integral
form of the SDE which is
$$
X_{t}=x+\int_{0}^{t}{\mu(s, X_{s})}~d{s} + \int_{0}^{t}{\sigma(s,X_{s})}~d{B_{s}},
$$
where we say that $\mu$ is the **drift coefficient** (controls the growth of
the process) and $\sigma$ is the **diffusion coefficient** (controls the size
of the noise).  