---
title: Jensen Inequality
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Jensen Inequality

**Jensen's inequality** gives a lower bound on expectations of convex functions
(such as linear functions, quadratic functions, exponential functions, modulus
etc.).

 
:::{.theorem data-title="Jensen's Inequality"}

For [[convex-function|convex function]] $\varphi$ and
[[random-variables-and-distribution-functions|random variable]] $X$ on a
probability space $(\Omega, \mathcal{F}, \mathbb{P})$ we have
$$
\varphi(\mathbb{E} X)\leq\mathbb{E}\varphi(X)~.
$$
Rewriting the expectation in its integral form we get the probability measure
theoretic form of the result
$$
\varphi\left(\int_{\Omega}Xd\mathbb{P}\right)\leq \int_{\Omega}\varphi(X)d\mathbb{P}.
$$

:::

*PROOF:*
Since $\varphi$ is convex, at each real number $x$ we have a nonempty set of
sub-derivatives (which may be thought of as lines touching the graph of
$\varphi$ at $x$, but which are below the graph of $\varphi$ at all points
(support lines of the graph). If we define
$$
x_0:=\int_{\Omega}X~d\mathbb{P}
$$
then from the existence of sub-derivatives for convex functions we may choose
$a$ and $b$ such that
$$
ax+b\leq \varphi(x)
$$
for all $x\in\mathbb{R}$ and $ax_0+b=\varphi(x_0)$. Then we have that
$$
\varphi(X)\geq aX+b
$$
for almost all $\omega\in\Omega$. From the monotonicity of the integral with
respect to the probability measure we obtain the result since
$$
\mathbb{E}\varphi(X)\geq a\mathbb{E}X+b=\varphi(\mathbb{E}X). 
$$
$\square$
