---
title: Lagrangian
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Lagrangian

## Lagrangian Equation
The **Lagrangian equation** is a **scalar representation** of a physical
system's position in phase space, with units of energy, and changes in the
Lagrangian reflect the movement of the system in phase space. To expand upon
this initial statement, the idea of Lagrangian mechanics is to convert the
state of the system into **generalized coordinates** $\boldsymbol{q}$ and
changes in those coordinates $\dot{\boldsymbol{q}}$. These coordinates
represent a simplified **phase space** for the system.  

For a system of $N$ particles in $\mathbb{R}^3$ the **configuration space** of
the system is a smooth manifold $Q\subseteq\mathbb{R}^{3N}$ where each
configuration $q(t):=(q_{1}(t), \dots, q_{N}(t))\in Q$ specifies the admissible
spacial positions of each of the particles at a given instant of time. A
**trajectory** of the system is a smooth function $q:[t_{0},t_{1}]\to Q$
describing the evolution of the configuration over time. The **tangent bundle**
$TQ\subseteq \mathbb{R}^{6N}$ of the configuration space contains tuples
$(q,\dot{q})\in TQ$ representing the particle positions and velocities.  

:::{.definition data-title="Lagrangian Equation"}

The **Lagrangian equation** is a smooth function
$\mathcal{L}:TQ\times \mathbb{R}\to \mathbb{R}$.

:::

The **action [[functional|functional]]** of the trajectory can therefore be
defined as the integral of the Lagrangian along the path
$$
\mathscr{A}[q]=\int_{t_{0}}^{t_{1}}{\mathcal{L}(q(t), \dot{q}(t),t)}~d{t}.
$$
The laws of motion in [[lagrangian-mechanics]] are derived form the postulate
that among all trajectories between two given configurations, the actual one
that will be taken by the system must be a critical point (often but not
necessarily a local minimum) of the action functional. This leads to the
[[euler-lagrange-equation]].

