---
title: Lagrangian Mechanics
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Lagrangian Mechanics

**Lagrangian mechanics** is a mathematical framework for studying mechanical
systems similar to [[newtonian-mechanics]] and [[hamiltonian-mechanics]]. The
foundational idea underpinning Lagrangian mechanics is the simplification of
problems to a scalar representation of a physical system's position in phase
space.  
## Motivation
To motivate this idea recall from [[newtonian-mechanics]] that we can describe
a system of $N$ point masses $m_{1}, \dots, m_{N}$ with 3-dimensional Cartesian
coordinates $\vec{r}_{i}:=(x_{i},y_{i},z_{i})$ for $i=1, \dots, N$ requiring
$3N$ coordinates. The velocity of each particle is given by the time derivative
$\vec{v}_{i}=\dot{\vec{r}}_{i}=d\vec{r}_{i} /dt$. From Newton's second law we
have
$$
F=m \vec{a}=m\ddot{ \vec{r}},
$$
thus for an $N$-particle system in 3-dimensions we have $3N$ second order
[[ordinary-differential-equations]] in the positions of the particles to solve
for. Lagrangian mechanics avoids forces and instead considers energies in the
system with the [[lagrangian]] *summarizing the dynamics* of the entire system.
Since, in the absence of an electromagnetic field, the *non-relativistic*
Lagrangian equation is given by the difference of kinetic energy $K$ and
potential energy $U$
$$
\mathcal{L}=K-U.
$$
We note that kinetic energy is given by
$$
K=\frac{1}{2}\sum_{k=1}^{N}m_{k}v^2_{k}
$$
where $v_{k}^2=\vec{v}_{k}\cdot \vec{v}_{k}$ and is therefore a function of
only velocities and not positions. Similarly, potential energy $U$ is only a
function of position for conservative forces (e.g. Newton's gravity).

### Intuitive Example - Defining the Lagrangian
To gain intuition for the system let us consider the introductory example of a
pendulum on a string with no resistance.
<!-- TODO: image "Pasted image 20250720175254.png" not found in vault -->
*Figure: Diagram of a swinging pendulum with no friction.*

The kinetic and potential energy of the system are
$$
\begin{align}
K & =\frac{1}{2}mv^2=\frac{1}{2}m\dot{s}^2=\frac{1}{2}ml^2\dot{\theta}^2 \\
U  & = mgy= mgl\cos\theta,
\end{align}
$$
where we have used $\theta=\frac{s}{l}$ to rewrite our derivatives in terms of
angle $\theta$, thus the Lagrangian $\mathcal{L}$ is
$$
\mathcal{L}=\frac{1}{2}ml^2\dot{\theta}^2+mgl\cos \theta.
$$
[[lagrangian]]
[[euler-lagrange-equation]]


We are thus able to write the **Euler-Lagrange equation** which is given by
$$
\frac{d}{dt} \frac{\partial\mathcal{L}}{\partial \dot{\theta}}= \frac{{\partial L}}{\partial \theta}.
$$
We can compute 
$$
\begin{align}
\frac{{\partial \mathcal{L}}}{\partial \theta} & =-mgl\sin \theta =\mathcal{F}\\
\frac{\partial\mathcal{L}}{\partial \dot{\theta}} & =ml^2\dot{\theta}=\mathcal{P}\implies \frac{d}{dt} \frac{\partial\mathcal{L}}{\partial \dot{\theta}} =ml^2\ddot{\theta},
\end{align}
$$
where $\mathcal{P}$ is *generalized momentum* at the point and $\mathcal{F}$
the *generalized force*, thus we see that the Euler-Lagrange equation gives the
familiar Newtonian force is equal to change in momentum.

