---
title: Laplace Operator
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Laplace Operator

The **Laplace Operator (Laplacian)** $\Delta$ is a **differential operator**
given by the **divergence** of the gradient of a scalar function on Euclidean
space. In a Cartesian coordinate system the Laplacian is given by the sum of
second partial derivatives of the function with respect to each independent
variable. Informally, the laplacian $\Delta f(p)$ of a function $f$ at a point
$p$ measures by how much the average value of $f$ over small balls centered at
$p$ deviates from $f(p)$.

The Laplacian occurs in many
[[ordinary-differential-equations|differential equations]] describing physical
phenomena including:

1. [[poisson-equation]] - describing electric and gravitational potentials;
2. [[diffusion-equation]] - describing heat and fluid flow;
3. [[wave-equation]] - describing wave propagation; and 
4. [[schrodinger-equation]] - describing the wave function in quantum
   mechanics.

:::{.definition data-title="Laplace Operator"}

The **Laplace operator (Laplacian)** is a second-order differential operator in
the $n$-dimensional Euclidean space, defined as the [[divergence]]
$(\nabla \cdot)$ of the [[gradient]] $(\nabla f)$. This if $f$ is a
twice-differentiable real function, then the Laplacian is the real-valued
function defined by
$$
\Delta f = \nabla^2f = \nabla \cdot \nabla f,
$$
where the latter notations derive from formally writing
$$
\nabla=\left( \frac{\partial}{\partial x_{1}}, \dots, \frac{\partial}{\partial x_{n}} \right).
$$

:::

