---
title: Las Vegas Valley Aquifer System
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

###### November 30th, 2024
~~John Robin Inston~~

## Background

A wealth of underground water helped to create the United States, its bountiful
farmland and expansive cities, but throughout its history Americans have been
squandering this incredible resource. According to the New York Times in an
article from 2023 in which they monitored tens of thousands of wells and
groundwater monitoring sites, nearly half of the sites they considered show
evidence that water levels have declined significantly over the last 40 years
as more water has been pumped out than is replenished naturally. Since the
inception of the Arizona Groundwater Act of 1980 there has been an increasing
urgency to take steps to halt this decline, and even hopefully reverting
groundwater storage levels to their past volumes. Through the implementation of
measures such as stricter water management laws, improved consumption
efficiency, exploration of alternate water sources and artificial recharge,
there has been some instances of successful groundwater recovery. The aim of
this project is to explore one of these instances, for which we chose the Las
Vegas Valley aquifer system in Nevada.

The Las Vegas Valley is a major metropolitan area located in southern Nevada.
The area is home to the three largest incorporated cities in Nevada: (the
fabulous) Las Vegas, Henderson, and North Las Vegas, which together have a
combined population of approximately 3 million people at the end of 2024. The
valley lies within both the Great Basin and Mojave desert sections of the Basin
and Range physiographic province, and is nestled in between the Spring
mountains to the West and the Sierra Nevada mountains to the East.
[[pavelkovegasnevadagambling1999]]

<!-- TODO: image "Screenshot 2024-12-04 at 8.36.04 PM.png" not found in vault -->
~~*Figure 1: Las Vegas Valley Map*~~

### Climate Conditions

The surrounding mountain ranges act as moisture barriers. Although more than 24
inches of precipitation fall annually in the Spring mountains, annual rainfall
on the valley floor (on average) is less than 4 inches with measurable amounts
(greater than 0.01 inches) seldom occurring for more than 30 days each year.
Temperatures in the valley often climb above 120°F. On average the region
experiences more than 125 days per year where temperatures climb above 90°F.
This coupled with the low precipitation results in dry and arid climate
conditions. Figure 2 below includes a plot provided by the U.S. Climate Data
website displaying the monthly precipitation layered with temperature highs and
lows in Las Vegas specifically averaged over the last 20 years. We see that on
average no month experiences more than 1 inch of rainfall per year, and that
temperatures in the summer months regularly reach over 100°F.
<!-- TODO: image "Screenshot 2024-12-04 at 8.38.06 PM.png" not found in vault -->
~~*Figure 2: Topological Map of Las Vegas Valley (Source: topographic-map.com)
and Average Annual Precipitation and Temperatures (Source: U.S. Climate
Data).*~~
### Land Use

Prior to settlement, the region was known for its plentiful water resources and
grassy meadows (*Las Vegas* translated from Spanish meaning *The Meadows*)
which were present due to an abundance of groundwater which fueled numerous
artesian wells. The presence of this oasis in the desert is what attracted
settlers to the valley, with the subsequent development of the Salt Lake and
Los Angeles railroad resulting in rapid population growth. Since the 1930's Las
Vegas has grown into one of the largest and most famous gaming centers and
adult resort destinations in the world. This economic expansion has come a
population explosion, resulting in an accelerated demand for water which was
historically met with imported water from the Colorado River (sourced from the
nearby Lake Mead) and with local groundwater.

<!-- TODO: image "Pasted image 20241204210336.png" not found in vault -->
~~*Figure 3: Las Vegas Valley Population Growth.*~~
### Aquifer System Characteristics

The water in the aforementioned artesian wells was flowing from the Las Vegas
Valley aquifer system that is present under the basin. The valley is a
structural trough filled with unconsolidated sediment such as sand and gravel.
Scattered throughout the aquifer are pockets of consolidated and
low-permeability materials such as slits and clays which increase in frequency
as you approach the basin. Overlying the principal aquifers in most places is a
100-300 foot thick section of extensive clay, sand, and gravel deposits known
as the near-surface reservoir. The principal aquifers and the near-surface
reservoir are separated by a variably-thick, laterally discontinuous aquitard.  

<!-- TODO: image "Pasted image 20241130194630.png" not found in vault -->
~~*Figure 4: Las Vegas Valley Aquifer Hydrogeological Cross-Section.*~~

### Groundwater Conditions

The aquifer is naturally replenished by the in-flow of precipitation from the
surrounding mountains. Near the margins of the valley groundwater moves freely
through the course-grained sand and gravel deposits, however as the water moves
further into the basin it encounters greater percentages of the
lower-permeability fine-grained silts and clays which retard lateral
groundwater flow. The natural recharge rate of the aquifer is around 33,000
acre-feet per year. As the valley's population (and therefore water
requirements) increased, so too did pumping rates which quickly overtook the
natural recharge of the aquifer leading to a decline in water storage. Using
data from the U.S. Geological Survey Online Database we constructed a plot of
depth-to-water over time for a well site near the Harry Reid International
Airport, shown below in Figure 2, from which we see a decline in depth-to-water
(and therefore water levels) since their records began in the late 1930s.

<!-- TODO: image "Screen Shot 2024-11-30 at 19.55.55 PM.png" not found in vault -->
~~*Figure 5: Depth-to-water time series prior to intervention (Source: U.S.G.S.
Online Database).*~~
## Intervention

To arrest impacts of groundwater depletion the district opted to implement an
artificial recharge program in 1988 whereby any surplus imported surface water
would be injected back into the aquifer system during low water demand periods
in the winter months. To assess the feasibility of conducting artificial
recharge the district first conducted a pilot project in 1987 which used an
existing unused production well to pump 525,000 gallons of imported water back
into the aquifer. The major concern of water managers regarding artificial
recharge was the resulting water chemistry. Since both the existing groundwater
and the injected water from Lake Mead were high in calcium it was hypothesized
to have potential for high calcite precipitation. If true, this could clog
perforations in the water well casing and could potentially reduce aquifer
permeability by clogging the pore space in the flow media. Fortunately, the
results of this pilot program as detailed in @katzerArtificialRechargeVegas1989
found no imbalance with regard to calcium or any other chemical constituent
post recharge and they concluded that artificial recharge is a feasible and
viable technique for the valley to meet their increasing water demand. This was
followed by a larger demonstration project whereby 1,153 acre-feet of treated
Colorado River water was injected into the aquifer through existing pumps with
minimal retrofitting and the results detailed in
@brothersWaterBankingArtificial1990 concluded similarly that negligible calcite
precipitated during recharge and recovery.

Following this successful demonstration the valley decided to expand their
artificial recharge program to include 15 retrofitted existing cable-tooled
drilled production wells between 1989 and 1991. From 1992 to 1993 a further 10
wells were added to the program, 7 of which were retrofitted like previous
wells with the remaining 3 being newly drilled using reverse circulation
drilling methods and gravel packing. However, close observation of the wells
and their resulting recharge indicated that these newly constructed wells were
experiencing near well bore clogging. Further evidence of this came to light
when the wells were pumped during the following summer production season with
flow rate declines and production capacity reductions from 30 to 60 percent.
Following these findings construction of both injection-only and dual-use wells
began in late 1996 using the original cable-tooled drilling methods.  

In addition to the artificial recharge efforts the district began shifting away
from their reliance on groundwater. As noted by the Las Vegas Valley Water
District, following a historic drought in the early 2000's the Colorado River
experienced its lowest flows on record. That same year, Southern Nevada used
more water than it ever had before. Recognizing the need to reduce water use
the community embraced and implemented the most progressive and comprehensive
water conservation program in the nation. The district adopted mandatory
conservation measures including seasonal water restrictions, golf course water
budgets, a grass replacement program, water waste penalties and changes to
municipal codes that significantly reduce the impact of new development on
water supply.

<!-- TODO: image "Screenshot 2024-12-04 at 9.21.44 PM.png" not found in vault -->
~~*Figure 6: Las Vegas Valley Water Sources Cumulative Plot (Source: PannState
InTeGrate - A Familiar History of Water and Population Growth).*~~
## Outcomes

The Las Vegas Valley artificial recharge program is widely regarded as one of
the most significant water conservation success stories involving groundwater
replenishment in the United States. Examining our own data for confirmation we
reproduce Figure 5, this time indicating the date that the artificial recharge
program commenced as well as depth-to-water measurements since the
intervention, shown below in Figure 7. We see clear evidence of not only a
halting of the downwards trend but a rebounding with water levels in our given
location recovering back to levels last seen in the 1960's. Further, the
current increasing trend indicating there is still further recovery on the way.

<!-- TODO: image "Screen Shot 2024-12-01 at 17.18.50 PM.png" not found in vault -->
~~*Figure 7: Depth-to-water time series in well site ID: 360349115100001 post
intervention (Source: U.S. Geological Survey Online Database).*~~

Furthermore, the districts water conservation program has been highly
successful in increasing the regions water-use efficiency which has reduced
their dependence on groundwater as a water source. According to the Southern
Nevada Water Authority, in the 21 years between 2002 and 2023 the region
experience a population growth of 52%, but in that same time period per-capita
water use is down 58% and their Colorado River water consumption is down 42%.
The district has also successfully transitioned away from groundwater and, per
the Las Vegas Valley Water District 2024 Water Quality Report, now only 10% of
the valley's water supply comes from groundwater with the 90% majority coming
from Lake Mead.

However, artificial recharge of the Las Vegas Valley reservoir ended in 2011
due the the district being unable to afford to store any of the water it
received from Lake Mead in the face of a years-long drought. Despite the
original plan of managing groundwater levels (with a combination of artificial
recharge and groundwater pumpage reduction) due to the growth in the population
groundwater pumpage levels have remained largely unchanged since the 1970's. We
produce a collection of plots using historical data provided by the Las Vegas
Valley pumpage inventory on groundwater recharge, gross groundwater pumpage
(before netting discharge) and Colorado River imports, shown below in Figure 8.  

<!-- TODO: image "Screen Shot 2024-12-01 at 17.43.46 PM.png" not found in vault -->
~~*Figure 8: Las Vegas Valley Groundwater Recharge (Plot 1), Groundwater
Pumpage (Plot 2) and Colorado River Imports (Plot 3) (Source: Las Vegas Valley
Pumpage Inventory).*~~

We see from Plot 1 in Figure 8 confirmation that groundwater artificial
recharge began in 1988 and peaked in the early 2000s - where a little over
30,000 acre-feet of water was injected into the aquifer - and ended in 2011.
However, we see from Plot 2 in Figure 8 that groundwater pumpage levels have
remained roughly constant around 70,000 acre-feet per year since the 1970's and
there is no real evidence that the total groundwater pumpage is decreasing.
This has sparked some concern among hydrologists of an impending relapse of the
problem since the 30,000 acre-feet per annum natural recharge is not sufficient
to balance pumpage. Further, we see from Plot 3 of Figure 8 that although there
has been some decrease in Colorado River consumption, the district still
imports over 400,000 acre-feet per year and as Lake Mead water levels decrease
Las Vegas will be entitled to smaller quantities. It is important to note
however that the valley's consumptive water use is down 30% in the last 20
years and that approximately 99% of all indoor water use is recycled and
returned to Lake Mead. This means that although their pumpage is high, their
consumptive water use is hovering slightly below 200,000 acre-feet, well below
their current Lake Mead quota of 300,000 acre-feet. In short, the district is
still importing large quantities of water from lake mead but is consuming a
significantly smaller portion.

## Summary

The Las Vegas Valley region of Southern Nevada implemented both an artificial
recharge program as well as an aggressive water conservation plan in an attempt
to combat the decreasing groundwater levels observed in the Las Vegas Valley
aquifer. The program was a clear success with data suggesting a significant
recovery of groundwater levels which as of 2024 have reverted back to levels
not seen historically since the 1960's. Although the problem of a growing
population and shrinking water sources persists for the region, the groundwater
problem is widely considered to be solved although some express concerns over
the continued pumpage levels. Despite the challenges presented by climate
change, Southern Nevada remains one of the most water-secure communities
reliant on the Colorado river.



###### References

1. Brothers, K., & Katzer, T. (1990). Water banking through artificial
   recharge, Las Vegas Valley, Clark County, Nevada. _Journal of Hydrology_,
   _115_(1–4), 77–103.
   [https://doi.org/10.1016/0022-1694(90)90199-8](https://doi.org/10.1016/0022-1694(90)90199-8)
2. Johnson, M., Cole, E., & Brothers, K. (n.d.). _Artificial recharge in the
   Las Vegas Valley: An Operational history_.
3. Katzer, T., & Brothers, K. (1989). Artificial Recharge in Las Vegas Valley,
   Clark County, Nevada. _Groundwater_, _27_(1), 50–56.
   [https://doi.org/10.1111/j.1745-6584.1989.tb00007.x](https://doi.org/10.1111/j.1745-6584.1989.tb00007.x)
4. Pavelko, M., Wood, D., & Laczniak, R. (1999). Las Vegas, Nevada—Gambling
   with water in the desert. _US Geological Survey_, _1182_, 49–64.
5. Ranatunga, T., Tong, S. T. Y., Sun, Y., & Yang, Y. J. (2014). A total water
   management analysis of the Las Vegas Wash watershed, Nevada. _Physical
   Geography_, _35_(3), 220–244.
   [https://doi.org/10.1080/02723646.2014.908763](https://doi.org/10.1080/02723646.2014.908763)
6. Sullivan, A. (n.d.). _LAS VEGAS VALLEY HYDROGRAPHIC BASIN 13-212_.
7. Wilson, J. W. (2021). _Discharge Data Collection and Analysis and
   Implications for Surface-Water/Groundwater Interactions in the lower Las
   Vegas Wash, Clark County, Nevada, 2016–18_ (Scientific Investigations Report
   No. 5034; Scientific Investigations Report).
8. Donovan, David & Katzer, Terry & Brothers, Kay & Cole, Erin & Johnson,
   Michael. (2002). Cost-Benefit Analysis of Artificial Recharge in Las Vegas
   Valley, Nevada. Journal of Water Resources Planning and Management-asce - J
   WATER RESOUR PLAN MAN-ASCE. 128. 10.1061/(ASCE)0733-9496(2002)128:5(356).
9. Draft Hydrogeological conceptual site model report, Avis and National
   Facilities McCarran International Airport Las Vegas, Nevada, Geo Blue
   Consulting Inc. (2018).
10. Plume, R. W. (1989). Ground-water conditions in Las Vegas Valley, Clark
    County, Nevada—Part 1 Hydrogeologic Framework. In _Water Supply Paper_
    (Nos. 2320-A). Dept. of the Interior, U.S. Geological Survey ;Books and
    Open-File Reports Section [distributor].
    [https://doi.org/10.3133/wsp2320A](https://doi.org/10.3133/wsp2320A)
11. Plume, R. W. (1996). _Ground-water Conditions in Las Vegas Valley, Clark
    County, Nevada—Part 2 Hydrology and simulation of ground-water flow_. U.S.
    Department of the Interior, U.S. Geological Survey.
 
