---
title: Likelihood Inference
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

#### Likelihood Inference

**Likelihood inference** is based upon the **likelihood principle** which is
the proposition that, given a specific statistical model, all of the evidence
in a sample relevant to model parameters is contained in the **likelihood
function**.

#### Likelihood Function

A likelihood function arises from a
[[probability-density-function|probability density function]] considered as a
function of its distributional parameterization argument. For example consider
a model which gives the probability density function $f_X(x;\theta)$ of
observable random variable $X$. For a specific value $x$ of $X$ the function
$$
\mathcal{L}(\theta;x)=f_X(x;\theta)
$$
is a likelihood function of $\theta$ as it gives a measure of how likely any
particular value of $\theta$ is given that $X$ took a value $x$. Two likelihood
functions are **equivalent** if one is a scalar multiple of the other.  

####

The **likelihood principle** is this: 

*All information from the data that is relevant to inferences about the value
of the model parameters is in the equivalence class to which the likelihood
function belongs.*

The **strong likelihood principle** applies this same criterion to cases such
as sequential experiments where the sample of data that is available results
from applying a to the observations earlier in the experiment.


