---
title: Lp Norm
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Norm Review

A [[norm|norm]] is a function defined on a
[[vector-space-linear-space|vector space]] that satisfies several properties
including non-negativity and the triangle inequality. Formally, a norm is
defined as follows.

:::{.definition data-title="Norm"}

For [[vector-space-linear-space|vector space]] $V$ on [[field|field]]
$\mathbb{R}$ a **norm** is a function $||\cdot||:V\rightarrow\mathbb{R}$
satisfying the following properties for $v,x\in V$:
1. $\Vert v\Vert \geq 0~\forall v\in V$
2. $||v||=0$ iff $v=0$
3. $\Vert\alpha v \Vert =|\alpha|\Vert v\Vert$ for $\alpha\in\mathbb{R}$
4. $\Vert v+z\Vert\leq \Vert v\Vert + \Vert x \Vert$ (triangle inequality)

:::

A norm is a very general construction and $p$-Norms are a specific type of norm
generalizing the concept of the [[euclidean-norm]].
## p Norm in Finite Dimensional Vector Space

The concept of a **[[norm|norm]]** arose from the generalization of the
Euclidean length of a vector (i.e. distance from the origin) in the $n$
dimensional real vector space $\mathbb{R}^n$ which is given by the
[[euclidean-norm]]
$$
\|x\|_{2}=(x_{1}^2+x_{2}^2+\dots +x_{n}^2)^{1/2}.
$$
The **Euclidean distance** between two points $x$ and $y$ is the length
$\|x-y\|_{2}$ of the straight line between the two points.

:::{.definition data-title="p Norm - Finite Dimension"}

Given $n$-dimensional vector space $V$ and real number $p\geq 1$, the **$p$-norm** (or **$L^p$-norm**) of $x\in V$ is the [[norm|norm]] specified by $$||x||_{p}=(|x_{1}|^p + \dots +|x_{n}|^p)^{1/p}.$$

:::

- For $p=1$ we obtain the **taxicab norm**.
- For $p=2$ we obtain the **[[euclidean-norm]]**.
- For $p\rightarrow\infty$ the $p$-norm approaches the **infinity norm**
  (**maximum norm**).

Note that the absolute value bars can be dropped when $p$ is a rational number
with an even numerator in its reduced form.

:::{.definition data-title="Maximum Norm"}

The **$L_{\infty}$-norm** or **maximum norm** is the limit of the $L_{p}$-norms for $p \to \infty$ and is given by $$\|x\|_{\infty}= \max\left\{  |x_{1}|,\dots ,|x_{n}|  \right\}.$$

:::

## Lp Norm in Function Space

Function spaces can be though of as infinite dimensional vector spaces and as
such, we are able to define norms on them.

:::{.definition data-title="$L^p$-Norm"}

Given a probability space $(X,\mathcal{F}, \mu)$ and a real number $p \in [1, \infty)$, the **$L^p$-norm** of a measurable function $f:X\to \mathbb{R}$ is defined by $$\|f\|_{p}=\left( \int_{X}|f|^p~d\mu \right)^{1/p}. $$

:::

Note that the $L^p$-norm of a function $f$ may be either finite or infinite.
The $L^p$ functions are those for which the $p$-norm is finite.

:::{.definition data-title="Lp Function"}

Let $(X, \mathcal{F}, \mu)$ be a measure space, and let $p \in [1,\infty)$.  An **$L^p$ function** on $X$ is a measurable function $f$ on $X$ for which $$\int_{X}|f|^p ~d\mu<\infty.$$

:::

- For $p\rightarrow\infty$ we obtain the **supremum norm**
  $\Vert f\Vert_{\infty}= \sup\{|f(x)|: x\in X\}$
- From this result we see the relationship between functions as infinite
  dimensional vectors.
- This norm is integral in [[probability-theory|probability theory]] as it
  defines [[lp-spaces]].

:::{.definition data-title="Supremum Norm"}

The **$L_{\infty}$-norm** or **supremum norm** is the limit of the $L_{p}$-norms for $p \to \infty$ and is given by $$\lVert f \rVert_{\infty} := \sup\{|f(x)|: x \in X\}.  $$

:::



