---
title: Lp Spaces
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

**$L^p$ spaces** (sometimes known as **Lebesgue Spaces**) are function spaces,
i.e. collections of functions that all have the same domain and codomain that
have properties in common, defined using a natural generalization of the
[[lp-norm]]. They form an important class of [[banarch-space|Banarch Spaces]]
in [[functional-analysis|functional analysis]] and of
[[topological-vector-spaces]].

:::{.definition data-title="$L_p$ Spaces"}

For any given positive real number $p>0$, let us denote be $L^p$ the family of functions $f:\Omega \to \mathbb{R}$ on the measurable space $(\Omega, \mathcal{F}, \mu)$ with $|f|^p \in L^1$, or equivalently $$\|f\|_{p}:=\left( \int _{\Omega}|f|^p \, d\mu  \right)^{1/p}<\infty.$$

:::



**Theorem:** $L^p$ space is a real vector space closed under addition and
scalar multiplication.
*Proof:*
Since $|f+g|^p\leq (2\cdot \max(|f|, |g|))^p\leq 2^p(|f|^p+|g|^p)$ we have that
$$
\|f+g\|_{p}^p\leq 2^p(\|f\|_{p}^p+\|g\|_{p}^p)
$$
for every $f,g \in L^p$. This implies that if $f,g \in L^p$, then
$f+g \in L^p$. Also, for every $c \in \mathbb{R}$ and $f \in L^p$ we have
$\|cf\|_{p}=|c|\cdot \|f\|_{p}$ and so if $f \in L^p$ then $cf \in L^p$ for
every constant $c \in \mathbb{R}$.

**Theorem (Completeness)**
The space $L^p$ is [[completeness|complete]] for any $p \in[1, \infty]$, that
is, for any Cauchy sequence $\{f_{n}, n \geq 1\}\subseteq L^p$ (i.e. with the
property that for every $\epsilon>0$ there is an integer $n_\epsilon$ such that
$\|f_{n}-f_{m}\|_{p}\leq \epsilon$ whenever $n\geq n_{\epsilon}$) there is a
unique $f \in L^p$ such that
$$
\|f_{n}-f\|_{p}\stackrel{n\to \infty}{\to}0.
$$
Moreover, there exists a subsequence
$\{f_{n_{k}},k\geq 1\}\subseteq \{f_{n},n\geq 1\}$, as well as a function
$F:\Omega \to[0,\infty)$ in $L^p$ such that for $\mu$-a.e.,
$\omega  \in \Omega$ we have
$$
|f_{n_{k}}(\omega)|\leq F(\omega);\quad \&\quad \lim_{ k \to \infty } f_{n_{k}}(\omega)=f(\omega).
$$
*Proof:*
