---
title: Markov Chain Classification
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## 

State $i$ *communicates* with state $j$ (or $j$ is *accessible* from $i$),
denoted $i \to j$ if $p_{i,j}(n)>0$ for some $n\geq 0$ that is, there is
positive probability for the chain to visit $j$ when starting from $i$.

- If $i \neq j$ this is equivalent to
  $f_{i,j}=\mathbb{P}(T_{j}<\infty|X_{0}=i)>0$.
 - If $i = j$, then $p_{i,i}(0)=1$ so that $i \to i$ but it is possible for
   $f_{i,i}=\sum_{n=1}^\infty f_{i,i}(n)=0$, that is, the chain might leave $i$
   immediately and never return to it.

States $i$ and $j$ *inter-communicate* if $i \to j$ and $j \to i$, denoted
$i\leftrightarrow j$ and we have the following results:

1. States $i$ and $j$ have the same period;
2. State $i$ is transient iff $j$ is transient; and
3. State $i$ is null persistent iff $j$ is.

A set of states $C$ is *irreducible* if for all $i,j\in C$,
$i\leftrightarrow j$, that is all states within $C$ inter-communicate.

A set of states $C$ is *closed* if for all $i \in C$, $p_{i,j}=0$ for all
$j\not\in C$, that is, the chain never leaves $C$ once it has entered. Not that
clearly the set consisting of one absorbing state is closed.