---
title: Martingale Convergence Theorems
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

References: 
- [[martingale-convergence-theorem-proof-r-isaac-pdf]]
- [[martingale-convergences-mit-pdf]]
### Martingale Convergence Theorems

The **martingale convergence theorems** give the conditions for which a
martingale converges ([[convergence-almost-surely|almost surely]] or in
[[convergence-in-norm|norm]]) to some limit $X:=\lim_{n \to \infty}X_{n}$.

:::{.theorem}

Let $(X_{n})$ be a [[martingale-theory|martingale]]. Then there is a
representation $X_{n}=U_{n}-V_{n}$ where $U_{n}$ and $V_{n}$ are non-negative
martingales if and only if $\lim_{n \to \infty}\mathbb{E}|X_{n}|< \infty$.

:::

^7e9b92

The idea is that we show that a non-negative submartingale with bounded second
moments is a mean-square Cauchy sequence. Then we show that such a
submartingale [[convergence-almost-surely|converges almost surely]]. We then
prove convergence for non-negative martingales and finally [[]] provides the
general case.

:::{.theorem data-title="Non-Negative L2 Bounded Submartingales are Mean-Square Cauchy"}

Let $(X_{n})$ be a non-negative submartingale with
$\lim_{n \to \infty }\mathbb{E}X_{n}^2<\infty$. Then
$$
\lim_{n,m\to \infty}\mathbb{E}\lvert X_{n}-X_{m} \rvert^2 = 0.
$$

:::

`\begin{proof}`
**Proof:**
[Martingale Convergence Theorem Proof (R.Isaac).pdf](app://obsidian.md/Martingale%20Convergence%20Theorem%20Proof%20(R.Isaac).pdf)

`\end{proof}`
:::{.theorem data-title="Non-Negative Submartingale Convergence"}

Let $(X_{n})$ be a non-negative submartingale with
$\lim_{n \to \infty}\mathbb{E}X_{n}^2< \infty$. Then
$$
X_{n}\stackrel{a.s.}{\to}X.
$$

:::

`\begin{proof}`
**Proof:**
[Martingale Convergence Theorem Proof (R.Isaac).pdf](app://obsidian.md/Martingale%20Convergence%20Theorem%20Proof%20(R.Isaac).pdf)
`\end{proof}`

:::{.theorem data-title="Non-Negative Martingale Convergence"}

Let $\{  X_{n} \}$ be a non-negative martingale. Then
$$
X_{n}\stackrel{a.s.}{\to}X.
$$

:::

`\begin{proof}`
**Proof:**
[Martingale Convergence Theorem Proof (R.Isaac).pdf](app://obsidian.md/Martingale%20Convergence%20Theorem%20Proof%20(R.Isaac).pdf)
`\end{proof}`

:::{.theorem data-title="Doob's Martingale Convergence"}

Let $\{  X_{n} \}$ be a martingale satisfying
$\lim_{n \to \infty}\mathbb{E}\lvert X_{n} \rvert< \infty$. Then

:::

The **Martingale Convergence Theorem** states that martingales 

:::{.theorem data-title="Martingale Convergence Theorem ($L^2$ Bounded Version)"}

If $\{ M_{n},~n\geq 1 \}$ is a martingale with respect to its own filtration $\mathcal{F}_{n}=\sigma(M_{1}, \dots, M_{n})$ and with $\mathbb{E}[M_{n}^2]<K<\infty,~n\geq 1$ for some $K>0$.  Then there exists in $\mathbb{R}$ an almost sure limit $M_{\infty}:=\lim_{n\to \infty}M_{n}$ and $$\lim_{n\to\infty}\mathbb{E}[|M_{n}-M_{\infty}|^2]=0,$$that is $M_{n}\stackrel{L^2}{\to}L^2$.

:::

**Proof:** [[martingale-convergence-theorem-proof-r-isaac-pdf]]
