---
title: Measurable Function
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Measurable Function

A core concept of measure theory is the idea of measurable functions.  

:::{.definition data-title="Measurable Function"}

For a [[measure-space|measure space]] $(X,\mathcal{M}, \mu)$, a function
$Y:\Omega\rightarrow\mathbb{R}^n$ is called **$\mathcal{F}$-measurable** if
$$
Y^{-1}(U):=\{\omega\in\Omega:Y(\omega)\in U\}\in \mathcal{F}
$$
for all [[open-sets-closed-sets-on-metric-spaces|open sets]]
$U\in\mathcal{R}^n$.

:::

Intuitively, a function between measure spaces
### What do we mean by a measurable function?

**We talk about the probability of subsets of Ω, not elements.**

Let's take probability theory as our model of reference. If you have a finite
set, $\Omega$, you can define a probability $\mu$ in $\Omega$ simply defining
the probability of each element of $\Omega$. But when you have an uncountable
set, this approach is not viable anymore as points have no probability mass.

The same reasoning applies if you are considering not probabilities, but the
length of a set. It is true that if the interval $I$ is the disjoint sum of two
other intervals $𝐽$ and $𝐾$, then the length of $𝐼$ will be the sum of the
lengths of $𝐽$ and $𝐾$. But $[0,1]$ is the disjoint union of the sets of the
form $\{𝑥\}$, whose length is $0$. Nevertheless, the length of $[0,1]$ is not
$0$. For that reason, we do not talk about the size or the probability of
points in $\Omega$. We talk about the probabilities or size of subsets of
$\Omega$.

**We know the size of certain sets (think of the intervals).**

Usually, we know the measure of certain subsets. For example, in the case of
the unit interval [0,1], one usually takes the size of an interval [𝑎,𝑏] to be
the value 𝑏−𝑎.

**The sets for which we do have a probability defined is the family
$\mathcal{B}$. Those are the "measurable" sets.**

Based on the size of this simple sets, we can manage to EXTEND our measure to
other sets. The next simpler case is when the set is the finite disjoint union
of intervals. It happens that, given the constraints we want the measure to
satisfy, not always it is possible to EXTEND the measure to the whole family of
subsets of Ω. So, we are happy to limit the domain of our measure 𝜇 to some
class  of subsets of Ω. We shall use the notation (Ω,) to indicate that we
are talking about the family  of subsets of Ω. So, the measure is a function

𝜇:→[0,1].

**Point 4. A measurable function 𝑓:Ω→𝑋 transports the probability in (Ω,) to a
probability (𝑋,).**

Now, suppose that you have a probability 𝜇:→[0,1] defined for a family of
subsets of Ω. And also, suppose that you have a function 𝑓:Ω→ℝ. Then, **you may
wish to TRANSPORT** your probability from Ω to ℝ. For example, suppose that
Ω={1,…,6} is a dice, and you are gambling. If the value of the dice is odd then
you get BRL 10, if it is even, then you lose BRL 10. This is the definition of
𝑓:Ω→{−10,10}. Now, instead of talking about a probability in Ω, we can talk
about the probability of, in one bet, getting or losing 10 Brazilian Reals. We
transported the probability in Ω to a probability in ℝ. **This is a measurable
function!** The probability of getting BRL 10 is the probability of the event
𝑓−1(10), and the probability of losing BRL 10 is the probability of 𝑓−1(−10).
The probability of losing money is the probability of the set 𝑓−1((−∞,0)).

If you think that 𝑓−1 is a function that takes subsets of ℝ to subsets of Ω,
then you can TRY to compose 𝜇 with 𝑓−1 to get 𝜇∘𝑓−1. In order for this to work,
if you want to know the probability of a set 𝐴⊂ℝ, you will need that 𝑓−1(𝐴)∈.

**Point 5. We want 𝑓−1(𝐼) to be measurable.**

Finally, since we are talking about a function 𝑓:Ω→ℝ, it might happen that we
want the probabilities to be defined at least for the intervals. That is, given
an interval 𝐼⊂ℝ, we want 𝑓−1(𝐼) to have a probability associated with it.

**Point 6. We got to a definition of "measurable function" which is easier to
state without appealing to measure theory.**

But 𝑓−1(𝐼) will be measurable for every interval 𝐼 exactly when 𝑓−1([−∞,𝑎)) is
measurable for every 𝑎.

**Point 7. We can integrate measurable functions (and get the "expected
value").**

With a function 𝑓 like this, we can calculate the mean, that is, the integral
of the function.

Now, I realise that you are not talking about probabilities, you are talking
about analysis. But then, you just have to change the terms "probability" by
measure. And for the same reason, technicalities aside, you can calculate the
integral of measurable functions. It is just a bit harder to understand because
now Ω=ℝ.
