---
title: Measure Theory Notes
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Measure Theory

Our primary aim in measure theory is to define the concept of *measurability*
and ultimately assign a *measure* to measurable sets. This will be useful when
we define the Lebesgue integral, and furthermore, this has applications in
probability theory where measurable sets may be considered as those events for
which a probability can be calculated.

## Measure Spaces

We first define a collection of subsets of $\Omega$ with certain desirable
properties.

For general set $\Omega$ a collection $\mathcal{F}\subset 2^\Omega$ is called a
**$\sigma$-algebra** in $\Omega$ iff it satisfies the following conditions:
1. Contains the whole space. $\Omega \in \mathcal{F}$.
2. Closed under compliments. $A\in\mathcal{F}\implies A^c\in \mathcal{F}$.
3. Closed under countable unions. $\{ A_{n} \}\subset \mathcal{F}$ then
   $$
   \bigcup_{n}A_{n}\in\mathcal{F}.
   $$
The tuple $(\Omega, \mathcal{F})$ consisting of a set $\Omega$ and a
$\sigma$-algebra $\mathcal{F}$ on $\Omega$ is called a **measurable space**.  

We note that this definition automatically implies:
1. Closure with respect to countable intersections via De Morgan.
2. $\emptyset \in \mathcal{F}$.

We contrast the definition of a $\sigma$-algebra with that of a topology.

For general set $X$ a collection $\mathcal{T}\subset 2^X$ is called a
**topology** on $\Omega$ iff it satisfies the following conditions:
1. Contains the whole space and the empty set.
   $\Omega, \emptyset \in \mathcal{T}$.
2. Closed under finite intersections. $\{ U_{n} \}\subset \mathcal{T}$ then
   $$
   \bigcap_{j=1}^n U_{j}\in \mathcal{T}.
   $$
3. Closed under arbitrary unions. $\{ U_{\alpha} \}\subset \mathcal{T}$ for
   $\alpha \in I$ (for potentially uncountable $I$) then
   $$
   \bigcup_{\alpha \in I}U_{\alpha} \in\mathcal{T}.
   $$
The tuple $(X, \mathcal{T})$ consisting of a set $X$ and a topology
$\mathcal{T}$ on $X$ is called a **topological space**.  

