---
title: Measurable Functions
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Measurable Functions

Measurable functions are morphisms in measurable spaces. We recall that any
mapping $f:X \to Y$ between two sets induces a mapping $f^{-1}:2^Y\to 2^X$
defined by
$$
f^{-1}(E)=\{ x \in X:f(x)\in E \},
$$
which preserves unions, intersections and complements. This, if $\mathcal{G}$
is a $\sigma$-algebra on $Y$, $\{ f^{-1}(E):E\in\mathcal{G} \}$ is a
$\sigma$-algebra on $X$.

:::{.definition data-title="Measurable Function"}

For measurable spaces $(X,\mathcal{F})$ and $(Y,\mathcal{G})$, a mapping
$f:X \to Y$ is said to be **$(\mathcal{F}, \mathcal{G})$-measurable** if
$$
\forall E \in\mathcal{G},~f^{-1}(E):=\{ x \in X:f(x) \in E \}\in\mathcal{F}.
$$

:::

Intuitively, we can *pull back* measurable sets from $Y$ to $X$. This is very
closely related to the definition of continuity of [[topological-functions]].

**Example (Measurable Functions):**
Consider the mapping $f(x)=x^2$ mapping within
$(\mathbb{R},\mathcal{B}_{\mathbb{R}})$

We say that a real function $f:\mathbb{R}\to \mathbb{R}$ is **Lebesgue
measurable** if it is
$(\mathcal{F}_{\lambda^*},\mathcal{B}_{\mathbb{R}})$-measurable. Also, given
topological spaces $X,Y$ we say that $f:X \to Y$ is **Borel measurable** if it
is $(\mathcal{B}_{X},\mathcal{B}_{Y})$-measurable. We will see that for
functions $f:\mathbb{R} \to \mathbb{R}$ we have that Borel measurability
implies Lebesgue measurability since
$\mathcal{B}_{\mathbb{R}}\subsetneq \mathcal{F}_{\lambda^*}$.

:::{.theorem data-title="$~$"}

Given measurable spaces $(X,\mathcal{F})$ and $(Y,\mathcal{G})$ where
$\mathcal{G}$ is generated by $\mathcal{E}$, then $f:X \to Y$ is
$(\mathcal{F},\mathcal{G})$-measurable if and only if
$\forall E\in \mathcal{E}$, $f^{-1}(E)\in\mathcal{F}$.

:::

*PROOF:*
The only if implication is trivial.  For the converse we observe that 
$$
\{ E \subset Y:f^{-1}(E)\in \mathcal{F} \},
$$
is a $\sigma$-algebra that contains $\mathcal{E}$; it therefore contains
$\mathcal{G}$.
$\square$

## Measurable Function Results

:::{.theorem data-title="Properties of Measurable Functions"}

For measurable space $(X,\mathcal{F})$ and function $f:X \to \mathbb{R}$ the
following are equivalent:
1. $f$ is $\mathcal{F}$-measurable;
2. $f^{-1}((a,\infty))\in \mathcal{F}$ for all $a\in \mathbb{R}$;
3. $f^{-1}([a,\infty))\in \mathcal{F}$ for all $a \in \mathbb{R}$;
4. $f^{-1}((-\infty,a))\in \mathcal{F}$ for all $a \in \mathbb{R}$;
5. $f^{-1}((-\infty,a])\in \mathcal{F}$ for all $a \in \mathbb{R}$.

:::

*PROOF:*
In our results on [[borel-sigma-algebra]] we proved that the open and closed
rays generate the Borel σ-Algebra. Thus from previous results we have the
result.
$\square$

