---
title: Monotone Class Theorem
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

The **monotone class theorem** connects [[monotone-class|monotone classes]] and
[[sigma-algebra|$\sigma$-algebra]]. The theorem generally states that the
smallest [[monotone-class|monotone class]] containing an [[algebra|algebra]] of
sets $G$ is precisely the [[generated-sigma-algebra|smallest $\sigma$-algebra]]
containing $G$.

It is used as a type of transfinite induction to prove many theorems including
[[fubinis-theorem]].
### Monotone Class Theorem for Sets

Recall that a [[monotone-class]] is a family (i.e. class) $M$ of sets that is
closed under countable monotone unions and countable monotone intersections.  

:::{.theorem data-title="Montone Class Theorem for Sets"}

Let $G$ be an [[algebra|algebra]] of sets and define $M(G)$ to be the smallest
monotone class containing $G$. Then $M(G)$ is precisely the
[[sigma-algebra|$\sigma$-algebra]] generated by $G$ $\sigma(G)=M(G).$

:::

### Monotone Class Theorem for Functions

:::{.theorem data-title="Monotone Class Theorem for Functions"}

Let $\mathcal{A}$ be a [[pi-system|$\pi$-system]] that contains $\Omega$ and
let $\mathcal{H}$ be a collection of functions from $\Omega$ to $\mathbb{R}$
with the following properties:
1. If $A\in\mathcal{A}$ then $\mathbb{1}_{A}\in \mathcal{H}$; 
2. If $f,g \in \mathcal{H}$ and $c \in \mathbb{R}$ then $f+g\in \mathcal{H}$
   and $cf \in \mathcal{H}$; and
3. If $f_{n}\in \mathcal{H}$ is a sequence of non-negative functions that
   increase to a bounded function $f$ then $f \in\mathcal{H}$.

Then $\mathcal{H}$ contains all bounded functions that are measurable with
respect to $\sigma(\mathcal{A})$ which is the
[[generated-sigma-algebra|$\sigma$-algebra generated]] by $\mathcal{A}$.

:::

