---
title: Monte-Carlo Variance Reduction
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

```table-of-contents
title: ## Contents
style: nestedOrderedList # TOC style (nestedList|nestedOrderedList|inlineFirstLevel)
minLevel: 0 # Include headings from the specified level
maxLevel: 0 # Include headings up to the specified level
includeLinks: true # Make headings clickable
hideWhenEmpty: false # Hide TOC if no headings are found
debugInConsole: false # Print debug info in Obsidian console
```
## Monte-Carlo Variance Reduction

In the theory of Monte Carlo methods, **variance reduction** is a procedure
used to increase the precision of the estimates obtained for a given simulation
or computational effort. Every output random variable from the simulation is
associated with a variance which limits the precision of the simulation
results.  

Suppose one wants to compute $z:=\mathbb{E}(Z)$ with the random variable $Z$
defined on the
[probability space](https://en.wikipedia.org/wiki/Probability_space "Probability space")
$(Ω,\mathcal{F},\mathbb{P})$. Monte Carlo does this by sampling i.i.d. copies
$Z_1,...,Z_n$ of $Z$ and then to estimate $z$ via the sample-mean estimator
$$
\bar{ z }=\frac{1}{n}\sum_{i=1}^{n}Z_{i}.
$$
Under further mild conditions such as $\text{Var}(Z)< \infty$, a central limit
theorem will apply such that for large $n→∞$, the distribution of $\bar{ z}$
converges to a normal distribution with mean $z$ and standard error
$\frac{σ}{n}$. Because the standard deviation only converges towards 0 at the
rate $\sqrt{ n }$, implying one needs to increase the number of simulations $n$
by a factor of 4 to halve the standard deviation of $\bar{z}$, variance
reduction methods are often useful for obtaining more precise estimates for $z$
without needing very large numbers of simulations.

In order to make a simulation statistically efficient, i.e., to obtain a
greater precision and smaller confidence intervals for the output random
variable of interest, variance reduction techniques can be used. The main
variance reduction methods are:

1. Common Random Numbers
2. [[antithetic-variates]]
3. [[control-variates]]
4. [[importance-sampling]]
5. Stratified Sampling
6. Moment Matching
7. Conditional Monte Carlo
8. Quasi-Random-Variables (in Quasi-Monte Carlo method)

## Antithetic Variates
[[antithetic-variates]]

## Control Variates
[[control-variates]]


## Importance Sampling
[[importance-sampling]]