---
title: Numerical Methods in Financial Mathematics
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Topics

1. [[sde-simulation]]
	1. [[euler-maruyama-method]]
	2. [[milstein-method]]
	3. [[sde-simulation|SDE Simulation Error]]
	4. SDE Simulation Examples:
		1. [[sde-simulation|Multiple Black-Scholes SDE Simulation]]
		2. [[sde-simulation|Heston Model SDE Simulation]]
		3. [[sde-simulation|Jump Diffusion SDE Simulation]]
		4. [[sde-simulation|Brownian Bridge SDE Simulation]]
2. [[monte-carlo-variance-reduction]]
	1. [[antithetic-variates]]
	2. [[control-variates]]
	3. [[importance-sampling]]
3. [[multi-level-monte-carlo-mlmc]]
4. [[derivatives-pricing|PDE Option Pricing]]
	1. [[finite-difference-fd-methods]]
		1. Explicit Scheme
		2. Implicit Scheme
			1. Solving Linear Systems
		3. Crank-Nicolson Method
		4. Boundary Conditions
		5. Convergence and Stability of Finite Difference Schemes
		6. FD Method Examples:
			1. 
	2. Multidimensional PDE
	3. Asian Options - PDE Approach
5. [[surrogate-methods]]
	1. Gaussian Process Regression
	2. Deep Galerkin Method (DGM)
6. [[american-options]]
	1. [[american-options|Finite Difference Methods for American Options]]
7. [[option-greeks]]
	1. Bump-and-Revalue
	2. Pathwise Estimation
	3. Likelihood Ratio Networks
	4. Neural Networks for SDE Simulation

## References

1. [[wilmott-howison-and-dewynne]]
2. [[higham-kloeden]]
3. [[glasserman|Monte Carlo Methods in Financial Engineering]]




