---
title: Pareto Optimal
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Pareto Optimal

In welfare economics, a Pareto improvement formalizes the idea of outcomes
being better in *every possible way*. An improvement is Pareto if at least one
person in the system is better off without anybody else being worse off.
A situation is called **Pareto optimal (efficient)** is all possible Pareto
improvements have already been made, that is all *win-win* improvements have
already been applied.  

:::{.definition data-title="Pareto Optimality"}

Formally, let $X$ be the set of all feasible allocations and define **utility
functions** $u_{i}:X \to \mathbb{R}$ of agent $i=1,\dots,n$. An allocation
$x^*\in X$ is **Pareto optimal** if there is no other allocation $x \in X$ such
that $u_{i}(x)\geq u_{i}(x^*);\quad \forall i$ and $u_{j}(x)>u_{j}(x^*)$ for at
least one $j$.  

:::

In other words, you cannot improve someones utility without lowering someone
else's.
