---
title: Point Set Topologies
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Topological Spaces

On non-empty set $X$ a **topology** $\mathcal{T}$ is a collection of subsets of
$X$ that satisfies the following:
1. $\emptyset, X \in \mathcal{T}$
2. $\{ U_{\alpha} \}_{\alpha \in A}\subset \mathcal{T}\implies \bigcup_{\alpha \in A}U_{\alpha}\in \mathcal{T}$
   (closed under arbitrary unions)
3. $\{ U_{i} \}_{i=1}^n\subset\mathcal{T}\implies \bigcap_{i=1}^n U_{i}\in\mathcal{T}$
   (closed under finite intersections)
The pair $(X,\mathcal{T})$ is known as a **topological space**.

*Some Examples:*
- If $X$ is a
  [[knowledge-mathematics-analysis-functional-analysis-metric-spaces|metric space]],
  the collection of all open sets with respect to the metric is a topology on
  $X$.
- If $(X,\mathcal{T})$ is a topological space and $Y\subset X$, then
  $\mathcal{T}_{Y}=\{ U \cap Y:U \in \mathcal{T} \}$ is a topology on $Y$,
  called the **relative topology** induced by $\mathcal{T}$.

##### Key Terminology

***Open & Closed Sets:***  
	The members of $\mathcal{T}$ are called **open sets** and their complements
 are called **closed sets**. If $Y \subset X$, the open (closed) subsets of $Y$
 in the relative topology are called **relatively open (closed)**. By
 [[de-morgans-laws]], the family of closed sets is closed under arbitrary
 intersections and finite unions.

***Interior & Closure:***
	For $A\subset X$, the union of all open sets contained in $A$ is called the
 **interior** of $A$, denoted $A^0$. The intersection of all closed sets
 containing $A$ is called the **closure** of $A$, denoted $\overline{A}$. The
 interior $A^0$ is the largest open set contained in $A$ and the closure
 $\overline{A}$ is the smallest closed set containing $A$. Furthermore, we have
 that $(A^0)^c=\overline{A^c}~~\&~~(\overline A)^c=(A^c)^0.$

**Boundary:**
	The **boundary** of $A$ is defined as the difference
 $\delta A:=\overline{A}\setminus A^0=\overline{A}\cap \overline{A^c}$.

**Density:**
	If $\overline A = X$ then $A$ is called **dense** in $X$. Alternatively, if
 $(\overline{A})^o=\emptyset$ then $A$ is called nowhere dense.

**Neighborhood:** 
	If $x \in X$ (or $E\subset X$), a **neighborhood** of $x$ or $E$ is a set
 $A\subset X$ such that $x \in A^o$ or ($E\subset A^o$). This, a set $A$ is
 open iff it is a neighborhood of itself.  

**Accumulation Point:**
	A point $x$ is called an **accumulation point** of $A$ if
 $A\cap(U \setminus \{  x \})\neq \emptyset$ for every neighborhood $U$ of $x$.



