---
title: Portmanteau Theorem
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Portmanteau Theorem

In mathematics and statistics, [[convergence-in-law|weak convergence]] is one
of many types of convergence relating to the
[[convergence-in-probability|convergence in probability]]. It depends on a
topology on the underlying space and thus is not a purely measure-theoretic
notion.

There are several equivalent definitions of weak convergence of a sequence of
measures, some of which are (apparently) more general than others. The
equivalence of these conditions is sometimes known as the Portmanteau theorem.

:::{.theorem data-title="Portmanteau Theorem"}

The following statements are equivalent:
1. $X_{n}\stackrel{\mathcal{D}}{\to}X$;
2. $\mathbb{E}[g(X_{n})]\to \mathbb{E}[g(X)]$ for all bounded and continuous
   functions $g$;
3. $\mathbb{E}[g(X_{n})]\to \mathbb{E}[g(X)]$ for all $g$ of the form
   $g(x)=f(x)\mathbb{1}_{[a,b]}(x)$, where $f$ is continuous on $[a,b]$ and
   $a,b \in C(F)$, that is, $g$ is a continuous function with finite support
   $[a,b]$ with $a,b \in C(F)$;
4. $\mathbb{E}[g(X_{n})]\to \mathbb{E}[g(X)]$ for all $g$ bounded and uniformly
   continuous;
5. If $A$ is such that $\mathbb{P}(X \in \delta A)=0$ then
   $\mathbb{P}(X_{n}\in A)\to \mathbb{P}(X\in A).$

:::

- In (5) $\delta A$ denotes the boundary of a set $A$. These are points that
  are reachable both form inside the set and outside:
  $$
  \delta A=\{ x : \exists \{  y_{n} \}\in A~s.t. y_{n}\to x~\&~ \exists \{  z_{n} \}\in A^c~s.t.~z_{n} \to x \}.
  $$
- Equivalent formulation of (5) using d.f.s $F_{n}$ and $F$:
  $$
  F(\delta A)=0\implies F_{n}(A)\to F(A).
  $$
  Here $F((a,b]):=F(b)-F(a)=\int \mathbb{1}_{(a,b]}(x)dF(x)$.