---
title: Power Series
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Power Series
## Power Series

:::{.definition data-title="Power Series"}

In mathematics, a **power series** (in one variable) is an infinite series of
the form
$$
\sum_{n=0}^\infty a_{n}(x-c)^n = a_{0} + a_{1}(x-c)+a_{2}(x-c)^2+\dots
$$
where $a_{n}$ represents the coefficient of the $n$-th term and $c$ is a
constant.

:::

Power series are useful in mathematical analysis where they arise as the
[[memory-calculus-taylor-series]] of infinitely differentiable functions. In
fact, [[borels-theorem]] implies that every power series is the Taylor Series
of some smooth function.

In many situations, $c$ (the center of the series) is equal to zero, for
instance when considering a [[memory-calculus-taylor-series|Maclaurin Series]],
in which case the power series takes the simpler form
$$
\sum_{n=0}^\infty a_{n}x^n = a_{0}+a_{1}x+a_{2}x^2 +\dots .
$$
The [[geometric-series]], [[exponential-function]] and
[[trigonometric-functions]] are all expressed as power series.

## Radius of Convergence

A power series $\sum_{n=0}^{\infty}a_{n}(x-c)^n$ is convergent for some values
of the variable $x$ (which will always include $x=c$) and diverge for other
values of $x$ (possibly all other values). If $c$ is not the only point of
convergence, then there is always a number $r$ with $0<r\leq \infty$ such that
the series converges whenever $\lvert x-c \rvert<r$ and diverges whenever
$\lvert x-c \rvert>r$. Such a number $r$ is called the **radius of
convergence** of the power series.

:::{.theorem data-title="Cauchy-Hadamard Theorem"}

In general, the radius of convergence of a power series is given by
$$
r=\liminf_{n \to \infty}{\lvert a_{n} \rvert ^{-1/n}},
$$
or equivalently by,
$$
r^{-1}=\limsup_{n \to \infty}{\lvert a_{n} \rvert ^{1/n}}.
$$

:::

The following relation is also satisfied if the limit exists
$$
r^{-1}=\liminf_{n \to \infty}{\left\lvert   \frac{a_{n+1}}{a_{n}}  \right\rvert }.
$$

