---
id: probability-theory
aliases: []
tags: []
author: "John Robin Inston"
date: 2026-08-22
date-modified: 2026-08-22
title: "Probability Theory"
title-block-banner: false
toc: true
---

## Related Topics

- [[linear-algebra]]
- [[real-analysis]]

## Topics

### Foundations 

- [[probability-theory-fundamentals]]
- [[combinatorics]]
- [[random-variable-transformations]]
- [[generating-functions]]
- [[probability-distributions]]
  - [[common-probability-distributions|Common Probability Distributions]]

### Measure Theoretic Probability

- [[probability-spaces]]
  - [[caratheodory-extension-theorem]]
- [[random-variables]]
- [[lebesgue-integral|Lebesgue Integration]]
- [[expectation|Expectation]]
- Product Measures
- Conditional Probability
  - [[conditional-expectation|Conditional Expectation]]

### Stochastic Processes

- [[stochastic-processes]]
- **Convergence Results:**
  - [[limits-of-stochastic-processes|Convergence of Stochastic Processes]]
    - [[convergence-almost-surely|Convergence Almost Surely]]
    - [[convergence-in-probability|Convergence in Probability]]
    - [[convergence-in-law|Convergence in Law]]
    - [[convergence-in-lp-norm|Convergence in Lp Norm]]
  - [[borel-cantelli-lemma|Borel-Cantelli Lemma]]
  - $L_p$ Spaces
  - [[uniform-integrability|Uniform Integrability]]
  - [[skorohod-representation-theorem|Skorohod's Representation Theorem]]
  - **Convergence Theorems:**
    - [[monotone-convergence-theorem|Monotone Convergence Theorem]]
    - [[dominated-convergence-theorem|Dominated Convergence Theorem]]
  - **Limit Theorems:**
    - [[law-of-large-numbers|Laws of Large Numbers]]
    - [[central-limit-theorem|Central Limit Theorem]]
- Large Deviations
- [[markov-chains]]
- [[gwb-branching-processes|Branching Processes]]  
- [[random-walks|Random Walks]]
- **Martingale Theory:**
  - [[martingale-theory|Martingale Theory]]
  - [[filtrations-and-adapted-processes|Filtrations & Adapted Processes]]
  - Martingales & Submartingales
  - [[martingale-convergence-theorems|Martingale Convergence Theorems]]
  - [[optional-stopping-theorem|Optional Stopping Theorem]]
  - [[stopping-times]]
  - [[doob-decomposition-theorem|Doob's Decomposition & Inequalities]]
- [[poisson-process|Poisson Processes]]
- Continuous-Time Markov Chains
  - [[infinitesimal-generator|Infinitesimal Generator]]
  - [[kolmogorov-equations|Kolmogorov Forward & Backward Equations]]
  - [[birth-death-processes|Birth-Death Processes]]


### Stochastic Calculus

- [[brownian-motion|Brownian Motion]]
- [[p-variation|p-Variation]]
- **Ito Calculus:**
  - [[ito-integral|Ito Integral]]
  - [[ito-formula|Ito Formula]]
  - [[ito-process|Ito Process]]
- [[stochastic-differential-equations|Stochastic Differential Equations]]
- **Common Stochastic Processes:**
  - [[ou-process|Ornstein-Uhlenbeck Process]]
  - [[geometric-brownian-motion|Geometric Brownian Motion]]
  - [[brownian-bridge|Brownian Bridge]]



