---
title: Product σ-Algebra
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Product σ-Algebra

A product σ-algebra is the [[measure-spaces|σ-algebra]] for the cartesian
products of sets. We begin by giving the formal definition of a **product
σ-algebra**.

:::{.definition data-title="Product σ-Algebra"}

Let $\{ X_{\alpha} \}_{\alpha \in A}$ be an indexed collection of nonempty sets
$X=\prod_{\alpha \in A}^{}X_{\alpha}$ and $\pi_{\alpha}:X \to X_{\alpha}$ the
coordinate maps. If $\mathcal{M}_{\alpha}$ is a σ-algebra on $X_{\alpha}$ for
each $\alpha$, the **product σ-algebra** on $X$ is the σ-algebra generated by
$$
\{ \pi_{\alpha}^{-1}(E_{\alpha}):E_{\alpha}\in\mathcal{M}_{\alpha},~\alpha \in A \}.
$$
We denote this σ-algebra by $\bigotimes_{\alpha \in A}\mathcal{M}_{\alpha}$. If
$A=\{ 1, \dots, n \}$ we also write $\bigotimes_{1}^n\mathcal{M}_{j}$ or
$\mathcal{M}_{1}\otimes \cdots \otimes \mathcal{M}_{n}$.

:::

 The following is an alternative, and perhaps more intuitive, characterization
 of product σ-algebras in the case of countably many factors.

:::{.theorem data-title="$~$"}

If $A$ is countable, then $\bigotimes_{\alpha \in A} \mathcal{M}_{\alpha}$ is
the $\sigma$-algebra generated by
$$
\left\{  \prod_{\alpha \in A}^{}E_{\alpha}:E_{\alpha}\in\mathcal{M}_{\alpha}  \right\}.
$$

:::

*PROOF:*
If $E_{\alpha}\in\mathcal{M}_{\alpha}$, then
$\pi_{\alpha}^{-1}(E_{\alpha})=\prod_{\beta \in A}^{}E_{\beta}$ where
$E_{\beta}=X$ for $\beta \neq \alpha$; on the other hand
$\prod_{\alpha \in A}^{}E_{\alpha}=\bigcap_{\alpha \in A}\pi_{\alpha}^{-1}(E_{\alpha})$.
The result follows from properties of σ-algebra.
$\square$

:::{.theorem data-title="$~$"}

Suppose that $\mathcal{M}_{\alpha}$ is generated by $\mathcal{E}_{\alpha}$,
$\alpha \in A$. Then $\bigotimes_{\alpha \in A}\mathcal{M}_{\alpha}$ is
generated by
$\mathcal{F}_{1}=\{ \pi_{\alpha}^{-1}(E_{\alpha}):E_{\alpha}\in\mathcal{E}_{\alpha}, \alpha \in A \}$.
If $A$ is countable and $X_{\alpha} \in \mathcal{E}_{\alpha}$ for all $\alpha$,
$\bigotimes_{\alpha \in A}\mathcal{M}_{\alpha}$ is generated by
$\mathcal{F}_{2}=\left\{  \prod_{\alpha \in A}^{}E_{\alpha}:E_{\alpha}\in \mathcal{E}_{\alpha}  \right\}.$

:::

*PROOF:*
Obviously
$\mathcal{M}(\mathcal{F}_{1})\subset \bigotimes_{\alpha \in A}\mathcal{M}_{\alpha}$.
On the other hand, for each $\alpha$, the collection
$\{ E \subset X_{\alpha}:\pi_{\alpha}^{-1}(E)\in \mathcal{M}(\mathcal{F}_{1}) \}$
is easily seen to be a $\sigma$-algebra on $X_{\alpha}$ that contains
$\mathcal{E}_{\alpha}$ and hence $\mathcal{M}_{\alpha}$. In other words
$\pi_{\alpha}^{-1}(E)\in\mathcal{M}(\mathcal{F}_{1})$ for all
$E \in \mathcal{M}_{\alpha}$, $\alpha \in A$, and hence
$\bigotimes_{\alpha \in A}\mathcal{M}_{\alpha}\subset \mathcal{M}(\mathcal{F}_{1})$.
The second assertion follows from the first as in the proof above.
$\square$

:::{.theorem data-title="$~$"}

Let $X_{1}, \dots, X_{n}$ be metric spaces and let $X=\prod_{j=1}^{n}X_{j}$
equipped with the product metric. Then
$\bigotimes_{1}^n\mathcal{B}_{X_{j}}\subset \mathcal{B}_{X}$. If the $X_{j}$'s
are separable, then $\bigotimes_{1}^n \mathcal{B}_{X_{j}}=\mathcal{B}_{X}$.

:::

*PROOF:*


:::{.theorem data-title="$~$"}

$\mathcal{B}_{\mathbb{R}^n}=\bigotimes_{1}^n \mathcal{B}_{\mathbb{R}}$.

:::






