---
title: Radius of Convergence
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Radius of Convergence

The radius of convergence of a [[power-series|power series]] is the radius of
the largest disk at the center of the series in which the series converges. It
is either a non-negative real number or $\infty$.

When it is positive, the series [[absolute-convergence|converges absolutely]]
an uniformly on compact sets inside the open disk of radius equal to the radius
of convergence, and it is the Taylor series of the analytic function to which
is converges.

:::{.definition data-title="Radius of Convergence"}

Consider a power series $f$ defined as
$$
f(z)=\sum_{n=0}^\infty c_{n}(z-a)^n,
$$
where: $a$ is a complex constant (the center of the disk of convergence); $c_n$
is the $n$-th complex coefficient; and $z$ is a complex variable.  

The **radius of convergence** $r$ is a non-negative real number of $\infty$
such that the series converges if $|z-a|<r$ and diverges if $|z-a|>r$.

:::


