---
title: Radon-Nikodym Derivative
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

## Radon-Nikodym Derivative

The **Radon-Nikodym derivative** is a measurable function relating two
probability measures defined on the same measurable space. Specifically, the
Radon–Nikodym derivative tells us how to reweight probabilities from measure
$\mathbb{P}$ to measure $\mathbb{Q}$.

:::{.definition data-title="Radon-Nikodym Derivative"}

For probability measures $\mathbb{P}$ and $\mathbb{Q}$ defined on measurable
space $(\Omega, \mathcal{F})$ assume absolute continuity
$\mathbb{Q}\ll \mathbb{P}$. The **Radon-Nikodym Theorem** guarantees the
existence of a measurable function $Z:\Omega \to[0,\infty)$ known as the
**Radon-Nikodym (RN) derivative** denoted
$$
Z= \frac{d\mathbb{Q}}{d\mathbb{P}}
$$
such that
$$
\mathbb{Q}(A)=\int_{A}^{}{Z}~d{\mathbb{P}},\quad \forall A \in \mathcal{F}.
$$

:::

*Recall that two measures $\mathbb{P}$ and $\mathbb{Q}$ are said to be
absolutely continuous, denoted $\mathbb{Q}\ll \mathbb{P}$ if
$\mathbb{P}(A)=0 \implies \mathbb{Q}(A)=0$ for all $A\in \mathcal{F}$.*

To gain an intuitive understanding of the role of the RN derivative note how we
can rewrite the expectation of a random variable $X$ under $\mathbb{Q}$ and
then $\mathbb{P}$
$$
\mathbb{E}^{\mathbb{Q}}[X]= \int_{\Omega}^{}{X}~d{\mathbb{Q}}=\int_{\Omega}^{}{X\cdot Z}~d{\mathbb{P}}=\mathbb{E}^{\mathbb{P}}[X].
$$
The main application of the RN derivative is in
[[financial-mathematics|mathematical finance]] where it is used to derive the
risk-free measure used to price derivatives.