---
title: Real Numbers
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Real Number Axioms

The **real numbers** $\mathbb{R}$ are any decimal i.e. the set of both
[[rational-numbers|rational numbers]] and
[[rational-numbers|irrational numbers]]. The algebraic properties of
$\mathbb{R}$ are summarized in the following axioms, which state that
$\mathbb{R}$ is a [[field|field]].

:::{.definition data-title="Real Number Field Axioms"}

There exists binary operations
$$
a,m:\mathbb{R} \times \mathbb{R} \to \mathbb{R},
$$
written $a(x,y)=x+y$ and $m(x,y)=x \cdot y = xy$ and elements
$0,1 \in \mathbb{R}$ such that $\forall x,y,z \in \mathbb{R}$:
1. $x+0=x$  (existence of additive identity 0)
2. $\forall x \in \mathbb{R}, \exists y \in R:x+y=0$ (existence of additive
   inverse)
3. $x+(y+z)=(x+y)+z$ (addition is associative)
4. $x+y=y+x$ (addition is commutative)
5. $x 1=x$ (existence of multiplicative identity)
6. $\forall x \in \mathbb{R} \setminus \{  0 \}, \exists y \in \mathbb{R}:xy=1$
   (existence of multiplicative inverse)
7. $x(yz)=(xy)z$ (multiplication if associative)
8. $xy=yx$ (multiplication is commutative)
9. $(x+y)z=xz+yz$ (multiplication is distributive over addition)

:::

Axioms 1 $\to$ 4 state that $\mathbb{R}$ is a commutative group with respect to
addition, 5 $\to$ 8 state that $\mathbb{R} \setminus \{  0 \}$ is a commutative
group with resect to multiplication and 9 that addition and multiplication are
compatible.

### Ordering Properties

The real numbers have a [[order|natural order relation]] that is compatible
with their algebraic structure. We visualize the real numbers as the real line,
with smaller numbers to the left and larger numbers to the right.

:::{.definition data-title="Real Number Order"}

There is a strict linear order $<$ on $\mathbb{R}$ such that for all
$x,y,z \in \mathbb{R}$:
1. either $x<y$, $x=y$ or $x>y$;
2. if $x<y$ then $x+z<y+z$;
3. if $x<y$ and $z>0$, then $xz<yz$.

:::

### Open & Closed Intervals

For any $a,b \in \mathbb{R}$ with $a \leq b$ we define the **open intervals**:
$$
\begin{align}
(-\infty, b) & :=\{  x \in \mathbb{R} : x < b \} \\
(a,b) & := \{  x \in \mathbb{R}: a<x<b \} \\
(a,\infty) & := \{  x \in \mathbb{R}: a<x \},
\end{align}
$$
the **closed intervals**:
$$
\begin{align}
(-\infty,b] & := \{  x \in \mathbb{R}:x \leq  b \} \\
[a,b] & := \{  x \in \mathbb{R}:a \leq  x \leq  b \} \\
[a,\infty) & := \{  x \in \mathbb{R} : a \leq  x \},
\end{align}
$$
and the **half-open intervals**:
$$
\begin{align}
(a,b] & := \{ x \in \mathbb{R}:a<x\leq  b\} \\
[a,b) & := \{  x \in \mathbb{R}:a \leq  x < b \}. \\
\end{align}
$$

All standard properties of inequalities follow from the previous axioms.
[[archimedean-property]]


:::{.theorem data-title="Uncountability of $\mathbb{R}$"}

The set $\mathbb{R}$ of real numbers is uncountable.

:::

`\begin{proof}`

`\end{proof}`

