---
title: Regression Analysis
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

Regression analysis is the statistical processes for estimating the
relationships between a dependent variable (response, outcome) and one or more
independent variables (predictors, covariates, explanatory variables,
features).
#### Models
- Linear Regression
	- Simple Regression
	- Polynomial Regression
	- General Linear Model
- Generalized Linear Model
	- Vector Generalized Model
	- Discrete Choice
	- Binomial Regression
	- Binary Regression 
	- Logistic Regression
	- Multinomial Logistic Regression
	- Mixed Logit
	- Probit
	- Multinomial Probit
	- Ordered Logit
	- Ordered Probit
	- Poisson Multilevel Model
	- Fixed Effects
	- Random Effects
	- Linear Mixed Effects Model
	- Nonlinear Mixed Effects Model
- Non-Linear Regression
	- Non-Parametric Regression
	- Semi-Parametric Regression
	- Robust Regression
	- Quantile Regression
	- Isotonic Regression
#### Estimation
- Least Squares Estimation
	- Linear Least Squares Estimation
	- Non-Linear Least Squares Estimation
	- Ordinary Least Squares Estimation
	- Weighted Least Squares Estimation