---
title: Research
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Aims
- To conduct cutting edge academic research into topics including: (1)
  stochastic differential equations; (2) stochastic partial differential
  equations; (3) stochastic control; (4) stochastic games.
	- Focus on study in these specific areas.
	- Further, focus on specific topics that are linked to the department, Mike or
   that are of interest to industry.
- To obtain a research focussed roll in academia or industry.
### Reading
- [[article-database]]
- [[academic-journals]]
### Projects
- [[mutual-fund-stress-project]]
- [[groundwater-markets-project-old]]

*Potential future projects:*
- Crowd searching software for lifeguards at busy beaches
- Butterfly counting app

### Topics
- Prabhanjan Ananth <- Read into!
- [[ordinary-differential-equations]]
- Partial Differential Equations
- [[latest-meeting-notes]]
- General Equilibrium / Radner Equilibrium
- Price Impact
- Rupert Maddison Financial Statistics with R

