---
title: Sequences
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Sequences

## Sequences

:::{.definition data-title="Sequence"}

A **sequence** is an ordered indexed collection of elements or terms
$\{x_{n}\}_{n\in \mathcal{N}}$ where $\mathcal{N}$ is some at most countably
infinite **index set**. In [[functional-analysis]] this is equivalent to a
function whose domain is an interval of integers.

:::

A sequence is said to be **finite** if $\mathcal{N}$ is finite, otherwise the
sequence is said to be **infinite**. A finite sequence of length $n$ is known
as an **$n$-tuple**. Sometimes we specify that a sequence is
**singly-infinite**, that is, infinite in only one direction (e.g.
$0,1,2,3,4,\dots$), or **bi-infinite**, infinite in both directions
$(e.g. \dots,-2,-1,0,1,2,\dots)$.

In general we can always replace any index set $\mathcal{N}$ with the set of
natural numbers $\mathbb{N}$.

### Monotonicity

A sequence $\{ x_{n} \}$ is said to be **monotonically increasing** if each
term is greater than or equal to the one before it, that is
$$
x_{n+1}\geq x_{n};~~\forall n.
$$
If we can drop the equality $x_{n+1}>x_{n}$ for all $n$ we say that the
sequence is **strictly monotonically increasing.**

Similarly, a sequence $\{ x_{n} \}$ is said to be **monotonically decreasing**
if each term is less than or equal to the one before it, that is
$$
x_{n+1}\leq x_{n};~~\forall n.
$$
If we can drop the equality $x_{n+1}<x_{n}$ for all $n$ we say that the
sequence is strictly monotonically decreasing.

If a sequence is either increasing or decreasing it is known as a monotone
sequence. This is a special can of the more general [[monotone-functions]].

*Note:* Sometimes we replace the terminology increasing with non-decreasing and
decreasing with non-increasing to help avoid any possible confusion with
strictly increasing and strictly decreasing.

A subsequence of $\{ x_{n} \}_{n\in \mathbb{N}}$ is any sequence of the form
$\{ x_{n_{k}} \}_{k \in \mathbb{N}}$ where $\{ n_{k} \}_{k \in \mathbb{N}}$ is
a strictly increasing sequence of positive integers.

### Boundedness

Consider a sequence $\{ x_{n} \}$ on some ordered set such as the extended real
numbers $\overline{\mathbb{R}}:=\mathbb{R}\cup \{ \pm \infty \}$. The number
$u \in \mathbb{R}$ is said to be an **upper bound** of the sequence if
$x_{n}\leq u$ for all $n \in \mathbb{N}$. We say that the sequence is **bounded
above**. Similarly, the number $l \in \overline{\mathbb{R}}$ is said to be
**lower bound** of the sequence if $x_{n}\geq l$ for all $n \in \mathbb{N}$. We
say that the sequence is **bounded below**. A sequence is **bounded** if it is
both bounded above and below.