---
title: Skorohod's Representation Theorem
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Skorohod's Representation Theorem

**Skorohod's Representation Theorem** is a result showing that a
[[convergence-in-law|convergent in law]] sequence of probability measures whose
limit measure is sufficiently well-behaved can be represented as the
distribution / law of a pointwise convergent sequence of random variables
defined on a common probability space.

:::{.theorem data-title="Skorohod's Representation Theorem"}

Suppose that $X_{n}\stackrel{\mathcal{D}}{\to}X$ as $n \to \infty$ with
$F_{n}(x):=\mathbb{P}(X_{n} \leq x)$ and $F(x):=\mathbb{P}(X\leq x)$ for
$x \in \mathbb{R}$. Then, there exists a probability space
$(\Omega', \mathcal{F}',\mathbb{P}')$ and random variables $\{Y_{n}, n\geq 1\}$
and $Y$ such that
$$
Y_{n}\stackrel{\mathcal{D}}{=}X_{n},\quad Y\stackrel{\mathcal{D}}{=X},
$$
for every $n$ and $Y_{n}\stackrel{a.s.}{\to}Y$ as $n \to \infty$.

:::

### Skorohod's Construction

We take $\Omega'=[0,1]$, $\mathcal{F}'=\mathcal{B}([0,1])$ and $\mathbb{P}'=$
the Lebesgue measure on $[0,1]$
$$
\mathbb{P}'((a,b])=b-a,~\forall a<b\in[0,1].
$$
For each $\omega \in \Omega'$ we define
$Y_n(\omega):= \inf\{  x: \omega \leq F_{n}(x)\}$ and
$Y(\omega):= \inf\{  x: \omega \leq F(x) \}$.

<!-- TODO: image "Screenshot 2024-08-25 at 6.22.20 PM.png" not found in vault -->

Note that
$$
\begin{align}
\omega \leq  F_{n}(x) &~ \iff Y_{n}(\omega)\leq  x  \\
\omega \leq  F(x) & ~ \iff Y(\omega)\leq  x,
\end{align}
$$
hence we have 
$$
\begin{align}
\mathbb{P}'(Y_{n}(\omega)\leq  y)  =\mathbb{P}'(\omega \leq  F_{n}(y)) & =\mathbb{P}'([0,F_{n}(y)])=F_{n}(y) \\
\mathbb{P}'(Y(\omega)\leq  y)& = F(y).
\end{align}
$$

:::{.theorem}

For a bounded continuous function $\varphi(\cdot)$, if $X_{n}$, $n \geq 1$
conveges to $X$ in distribution, as $n\to \infty$, then
$$
\lim_{n\to \infty}\mathbb{E}[\varphi(X_{n})]=\mathbb{E}[\varphi(X)].
$$

:::

