---
title: Span and Bases
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Span and Basis

## Span
:::{.definition data-title="Definition (Span)"}

The **span** of a collection of vectors
$\vec{v}_{1}, \dots, \vec{v}_{n}\in \mathcal{V}$ is defined as
$$
\text{span}_{F}(\vec{v}_{1}, \dots, \vec{v}_{n}):=\{ \alpha_{1}\vec{v}_{1}+\dots+\alpha_{n}\vec{v}_{n}; \alpha_{1}, \dots, \alpha_{n}\in F \},
$$
i.e. the set of all possible linear combinations.  

:::

More generally, if $S \subset \mathcal{V}$ is any subset of vectors, then the
span of $S$ is the smallest subspace of $\mathcal{V}$ containing $S$. The span
of a set of vectors is always a subspace, and if
$W=\text{span}_{F}(\vec{v}_{1}, \dots, \vec{v}_{n})$ then we say $W$ is
**spanned** by vectors $\vec{v}_{1}, \dots, \vec{v}_{n}\in \mathcal{V}$.

For vectors $\vec{v}_{1}, \dots, \vec{v}_{n}\in\mathcal{V}$, if one of them
$\vec{v}_{i}$ can be written as a linear combination of the others, then we say
the whole sequence is **linearly dependent**. Otherwise, we call the sequence
**linear independent**.

## Basis
:::{.definition data-title="Definition (Basis)"}

Let $\mathcal{B}:=(\vec{v}_{1}, \dots, \vec{v}_{n})$ be a finite sequence of
vectors $\vec{v}_{i}\in\mathcal{V}$ . We say $\mathcal{B}$ forms a **basis**
when:
1. $\mathcal{B}$ spans $\mathcal{V}$;
2. $\mathcal{B}$ is linearly independent.

:::

A sequence $\mathcal{B}:=(\vec{v}_{1}, \dots, \vec{v}_{n})$ of vectors in
$\mathcal{V}$ forms a basis if and only if every vector $\vec{v}\in\mathcal{V}$
can be written uniquely as a linear combination of the vectors in
$\mathcal{B}$.

If a vector space $(\mathcal{V},F)$ has a basis
$\mathcal{B}:=(\vec{v}_{1}, \dots, \vec{v}_{n})$ with $n$ elements, then we say
$V$ has **dimension** $n$, and we write $\text{dim}_{F}(\mathcal{V})=n$.
Clearly, if $\mathcal{V}$ has two bases $\mathcal{B}_{1}$ and $\mathcal{B}_{2}$
then they must be of the same length. If a vector space $(\mathcal{V}, F)$ has
finite basis $\mathcal{B}$ then we say $(\mathcal{V}, F)$ is
**finite-dimensional**, otherwise we say it is **infinite-dimensional**.

Let $(\mathcal{V},F)$ be a finite-dimensional vector space, and assume $S$ is a
set of vectors that spans $\mathcal{V}$. Then there is a sequence of vectors in
$S$ that forms a basis of $\mathcal{V}$. We construct basis iteratively by
selecting vectors not currently in the span of the collection until the
collection spans $\mathcal{V}$.

If $\vec{v}_{1}, \dots, \vec{v}_{r}$ is a linearly independent sequence in a
finite-dimensional vector space $\mathcal{V}$, then it can be extended to a
basis of $\mathcal{V}$, in other words we can find
$\vec{v}_{r+1},\dots,\vec{v}_{n}$ such that $\vec{v}_{1}, \dots, \vec{v}_{n}$
is a basis of $\mathcal{V}$.

:::{.definition data-title="Definition (Basis Test)"}

Let $\vec{v}_{1}, \dots, \vec{v}_{n}$ be $n$ vectors in an $n$-dimensional
vector space $\mathcal{V}$. These vectors form a basis of $\mathcal{V}$ if
either:
1. $\vec{v}_{1}, \dots, \vec{v}_{n}$ are linearly independent;
2. $\vec{v}_{1}, \dots, \vec{v}_{n}$ span $\mathcal{V}$.

:::

For basis $\mathcal{B}=(\vec{v}_{1}, \dots, \vec{v}_{n})$ of vector space
$(\mathcal{V}, F)$ we can write any vector $\vec{v}\in\mathcal{V}$ as
$$
\vec{v}=\alpha_{1}\vec{v}_{1}+\dots+\alpha_{n}\vec{v}_{n},
$$
where the scalars $\alpha_{i}\in F$ are called the **coordinates** of $\vec{v}$
with respect to basis $\mathcal{B}$. The **coordinate vector / matrix** of
$\vec{v}$ with respect to $\mathcal{B}$ is
$$
[\vec{v}]_{\mathcal{B}}=\begin{bmatrix}
\alpha_{1} & \cdots & \alpha_{n}
\end{bmatrix}^T.
$$
Some common vector spaces, for example the Euclidean spaces, have standard
coordinate systems which are defined with respect to the standard bases. For
$\mathbb{R}^2$ for example these are
$$
\vec{v}_{1}:=\begin{bmatrix}
1 & 0
\end{bmatrix}^T\quad\&\quad\vec{v}_{2}=\begin{bmatrix}
0 & 1
\end{bmatrix}^T.
$$

In the following definition, the symbol $[\vec{x}]$ denotes the coordinates of
$\vec{x}$ in the standard basis $F^n$. Let
$S:=(\vec{x}_{1}, \dots, \vec{x}_{n})$ be a sequence of vectors in $F^m$. The
**matrix of column vectors** of $S$ is the $M_{m \times n}(F)$ matrix with
columns $[\vec{x}_{i}]$. The **matrix of row vectors** of $S$ is the
$M_{n \times m}(F)$ matrix with rows $[\vec{x}_{i}]^T$.

For $A \in M_{n \times m}(F)$ the **row space** of $A$ is the subspace in $F^m$
spanned by its rows. The **row rank** of $A$ is the dimension of the row space.
The **column space** of $A$ is the subspace in $F^n$ spanned by its columns.
The **column rank** of $A$ is the dimension of the column space. Row operations
do not change the row space of $A$ and column operations do not change the
column space of $A$.  
For $A,B \in M_{n \times m}(F)$ the following statements are equivalent:

1. $A$ and $B$ are row-equivalent to each other;
2. The row space of $A$ is equal to the row space of $B$.