---
title: Spectral Distributions
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

:::{.definition data-title="Spectrum and Spectral Density"}

The **spectrum** of $X$ is the set of
$$
\{ x: F(x+\varepsilon)-F(x-\varepsilon)>0; \quad\forall \varepsilon>0 \}.
$$
If $F(\cdot)$ is absolutely continuous with respect to the
[[lebesgue-measure|Lebesgue measure]], i.e.
$F(\cdot)=\int_{-\infty}^\cdot (\frac{dF(s)}{ds})ds$ then its
[[radon-nikodym-derivative]] is called the **spectral density**.

:::

:::{.theorem data-title="Spectral Theorem"}

Suppose that $\{ X_{t}, t \in \mathbb{R} \}$ is
[[stationary-processes|weakly stationary]] with mean $0$ and variance $1$ and
with spectral distribution $F(\cdot)$. Then we have the spectral representation
$$
X_{t}=\int _{\mathbb{R}}e^{itu}dZ(u),
$$
where the RHS is the [[convergence-in-norm|limit in mean square]] of a sequence
of approximating Riemann-Stieltjes sums and the spectral process
$\{ Z(u),u \in \mathbb{R} \}$ is a complex-valued process of orthogonal
increments, i.e.
$$
\mathbb{E}[(Z(u_{4})-Z(u_{3})(\overline{Z(u_{2})-Z(u_{1})})]=0;\quad u_{1}<u_{2}\leq  u_{3}<u_{4},
$$
with
$$
\mathbb{E}[(Z(u_{2})-Z(u_{1}))(\overline{Z(u_{2})-Z(u_{1})})]=F(u_{2}-F(u_{1})),\quad u_{1}<u_{2}.
$$
Moreover, we have for every $u_{1}<u_{2}$ the inversion formulae
$$
\begin{align}F(u_{2})-F(u_{1})&=\lim_{T \to \infty} \frac{1}{2 \pi}\int_{-T}^T \frac{e^{-iu_{2}t}-e^{-iu_{1}t}}{-it}\cdot \rho(t)\;dt,\\ Z(u_{2})-Z(u_{1})&=\text{l.i.m.}_{T \to \infty} \frac{1}{2\pi}\int_{-T}^T \frac{e^{-iu_{2}t}-e^{-iu_{1}t}}{-it}\cdot X_{t}\;dt,\end{align}
$$
where $\text{l.i.m}$ is the limit in mean square of the sequence of random
variables.

:::

:::{.theorem data-title="Spectral Density Function"}

If $\{ X_{n},n \in \mathbb{Z} \}$ is a complex-valued, discrete-time
[[stationary-processes|weakly stationary]] process with zero mean and unit
variance and with the autocorrelation function $\rho(n),~n \in \mathbb{Z}$.
There exists the spectral distribution function $F:(-\pi,\pi] \to [0,1]$ such
that
$$
\rho(n)=\int_{-\pi}^\pi e^{inu}dF(u);\quad n \in \mathbb{Z}.
$$
If it has the spectral density function $f(\cdot)$, then
$$
f(u)= \frac{1}{2\pi}\sum_{n=-\infty}^\infty e^{-i\nu}\rho(n);\quad u \in [-\pi,\pi).
$$

:::

