---
title: Stopping Time
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Stopping Time

In probability theory, a **stopping time** is a specific type of random
variable whose value is interpreted as the **time at which a given stochastic
process exhibits a certain behavior of interest**.  

A stopping time is often defined by a **stopping rule**, which determines
whether to continue or stop a process on the basis of the present position and
past events, and which will almost always lead to a decision to stop at some
finite time.

The key property of a stopping rule is that is must be measurable with respect
to the filtration i.e. we must know whether the rule is satisfied or not with
information available at the present time $n$.

**Examples:**
- *Turn off the freeway at the exit after the airport* - This is a stopping
  time because the rule is based on information available at present time $t$.
- *Turn off the freeway at the exit before the airport* - This is not a
  stopping time because the rule is based on future information, we only know
  the exit was before the airport when we get to the airport exit.

:::{.definition data-title="Stopping Time"}

Let $\tau$ be a [[random-variables-and-distribution-functions|random variable]]
which is defined on the
[[knowledge-mathematics-analysis-probability-theory-probability-spaces|probability space]]
$(\Omega, \mathcal{F}, \mathbb{P})$ with [[filtration|filtration]]
$(\mathcal{F}_{t})_{t \in T}$ with values in $T$ (where in most cases
$T=[0,+\infty)$). Then $\tau$ is a **stopping time with respect to filtration
$\mathbb{F}=(\mathcal{F}_{t})_{t \in T}$** if the following condition holds
$$
\{ \tau\leq t \}\in\mathcal{F}_{t},
$$
for all $t \in T$.

:::

Intuitively, we know whether or not the stopping time $\tau$ has occurred
before or at $t$ using only the information available at $t$.

:::{.definition data-title="$\sigma$-Algebra for Stopping Times"}

The $\sigma$-algebra for a stopping time $T$ is defined by
$$
\mathcal{F}_{T}=\left\{   A:A \cap \{  T \leq  n \}~\forall n  \right\}.
$$

:::

