---
title: Strong Law of Large Numbers
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

The **Strong Law of Large Numbers (SLLN)** is a deeper and stronger result than
the weak law. It states that the sample average of a sequence of random
variables **converges almost surely** (with probability 1) to the expected
value. Our first result starts again with the version requiring **finite second
moments**.

:::{.theorem data-title="Strong Law of Large Numbers"}

Given a collection of i.i.d. random variables $X_{1}, \dots, X_{n}$ each with
finite mean $\mathbb{E}[X_{i}]=\mu$ and $\mathbb{E}[X_{i}^2]<\infty$, then the
sample mean [[convergence-almost-surely|converges almost surely]] to $\mu$,
i.e.
$$
\bar{X}_{n}\stackrel{a.s.}{\to}\mu\quad (n \to \infty),
$$
that is, $\mathbb{P}(\lim_{ n \to \infty }\bar{X}_{n}=\mu)=1$.

:::

*Proof:*

Next we state that general result for the Strong Law of Large Numbers which has
the condition of pairwise independence.

:::{.theorem data-title="General Strong Law of Large Numbers"}

Let $X_{1}, X_{2}, \dots$ be pairwise independent identically distributed
random variables with $\mathbb{E}\lvert X_{1} \rvert<\infty$. Let
$\mathbb{E}[X_{1}]=\mu$ then
$$
\frac{S_{n}}{n}= \frac{\sum_{i=1}^nX_{i}}{n} \stackrel{a.s}{\to}\mu\quad \text{as}\quad n \to \infty.
$$

:::

*Proof:*
