---
title: "Supremum & Infimum"
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Supremum & Infimum (Real Numbers)

The **supremum** and **infimum** are key concepts for defining
[[completeness|completeness]]. In real analysis, we can use the
[[order|ordering properties]] of $\mathbb{R}$ to define the supremum and
infimum of a set of real numbers.  

:::{.definition data-title="Supremum & Infimum"}

The set of real numbers $A\subset \mathbb{R}$ has an upper bound
$M \in \mathbb{R}$ such that $M \leq M'$ for every upper bound $M'$ of $A$,
then $M$ is the **least upper bound** or **supremum** of $A$, denoted
$$
M=\sup{A}.
$$
Similarly, if $A \subset \mathbb{R}$ has a lower bound $m \in \mathbb{R}$ such
that $m\geq m'$ for every lower bound $m'$ of $A$, then $m$ is the **greatest
lower bound** or **infimum** of $A$, denoted
$$
m=\inf{A}.
$$

:::

If $A=\{ x_{i}:i \in I \}$ is an indexed subset of $\mathbb{R}$ we write
$$
\sup{A}=\sup_{i \in I}{x_{i}},\quad \quad \inf{A}=\inf_{i \in I}{x_{i}}.
$$
Note that if $M,m \in A$ then the supremum $M$ and infimum $m$ are equivalent
to the maximum and minimum respectively. The key point is that the supremum and
infimum need not belong to the set $A$.

:::{.definition}

If a set $A \subset \mathbb{R}$ is not bounded from above, then
$\sup_{}{A}= \infty$ and if $A$ is not bounded from below then
$\inf_{}{A}=-\infty$.

:::

### Supremum & Infimum Properties

:::{.theorem}

If $A \subset \mathbb{R}$ then $M = \sup_{}{A}$ if and only if:
1. $M$ is an upper bound of $A$;
2. $\forall M'<M,~\exists x \in A~:~x>M'$.

Similarly, $m = \inf_{}{A}$ if and only if:
1. $m$ is a lower bound of $A$; and
2. $\forall m'>m,~\exists x \in A~:~x<m'$.

:::

We frequently use this proposition as follows:

1. If $M$ is an upper bound of $A$; then $\sup_{}{A}\leq M$.
2. If you $A$ is nonempty and bounded from above, then for every
   $\varepsilon>0,~\exists x \in A~s.t. x>\sup_{}{A}-\varepsilon$.




