---
title: Taylor Series
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Taylor Series

The **Taylor series expansion** of a function is an infinite sum of terms that
are expressed in terms of the functions derivatives at a single point. A Taylor
series is also known as a **Maclaurin series** when $0$ is the point where the
derivatives are considered. The partial sum formed by the first $n+1$ terms of
a Taylor series is a polynomial of degree $n$ and is called the **$n$th Taylor
polynomial** of the function.

## Taylor Series

The **Taylor series** of a real or complex function $f(x)$ that is infinitely
differentiable at a real or complex number $a$ is the
[[power-series|power series]]
$$
f(a)+ \frac{f'(a)}{1!}(x-a)+ \frac{f''(a)}{2!}(x-a)^2+ \dots=\sum_{n=0}^\infty \frac{f^{(n)}(a)}{n!},
$$
where $f^{(n)}(a)$ denotes the $n$th derivative of the function $f$ evaluated
at point $a$.

The Taylor series for a function $f$ at $a=0$ is known as the **Maclaurin
series**.

## Taylor Series Examples

### 1. Exponential Function

The **exponential function** $e^x$ has Maclaurin series
$$
e^x=\sum_{n=0}^\infty \frac{x^n}{n!}.
$$
The exponential [[generating-functions|generating function]] of the
[[bell-numbers|Bell numbers]] is the exponential function of the predecessor of
the exponential function
$$
\exp(\exp x -1) = \sum_{n=0}^\infty \frac{B_{n}}{n!}x^n.
$$
### 2. Natural Logarithm

The natural logarithm has Maclaurin series
$$
\begin{align}\log(1-x) & =-\sum_{n=1}^\infty \frac{x^n}{n}  \\ \log(1+x) & = \sum_{n=1}^\infty (-1)^{n+1} \frac{x^n}{n}.\tag{$\star$}\end{align}
$$
The series $(\star)$ is known as the **Mercator series**. Both of these series
converge for $|x|<1$ (in addition, the series for $\log(1-x)$ converged for
$x=-1$ and the series for $\log(1+x)$ converges for $x=1$).

### 3. Geometric Series

The **geometric series** and its derivatives have Maclaurin series
$$
\begin{align}\frac{1}{1-x} & = \sum_{n=0}^\infty x^n \\\frac{1}{(1-x)^2} & = \sum_{n=1}^\infty nx^{n-1}  \\\frac{1}{(1-x)^3} & = \sum_{{n=2}}^\infty \frac{(n-1)n}{2}x^{n-2} \\& \vdots\end{align}
$$
All are convergent for $|x|<1$. These are special cases of the binomial series
given below.

### 4. Binomial Series

The **binomial series** is the power series
$$
(1+x)^\alpha =\sum_{n=0}^\infty {\alpha \choose n}x^n,
$$
whose coefficients are the generalized binomial coefficients
$$
{\alpha\choose n}=\prod_{k=1}^n \frac{\alpha-k+1}{k}=\frac{{\alpha(\alpha-1)\cdots (\alpha-n+1)}}{n!}.
$$
It converges for $|x|<1$ for any real or complex number $\alpha$.

The special cases $\alpha=\frac{1}{2}$ and $\alpha= -\frac{1}{2}$ give the
**square root functon** and the **inverse square root function**
$$
\begin{align}
(1+x)^{1/2} & = \sum_{n=0}^\infty \frac{(-1)^{n-1}(2n)!}{4^n(n!)^2(2n-1)}x^n  \\
(1+x)^{-1/2} & = \sum_{n=0}^\infty \frac{(-1)^n (2n)!}{4^n(n!)^2}x^n.
\end{align}
$$
### 5. Trigonometric Functions

The usual **trigonometric functions** and their inverses have the following
Maclaurin series
$$
\begin{align}
\sin x & =\sum_{n=0}^\infty \frac{(-1)^n}{(2n+1)!}x^{2n+1} \\
\cos x & = \sum_{n=0}^\infty \frac{(-1)^n}{(2n)!}x^{2n} \\
\tan x & = \sum_{n=1}^\infty \frac{B_{2n}(-4)^n(1-4^n)}{(2n)!}x^{2n-1} \\
\sec x & = \sum_{n=0}^\infty\frac{(-1)^nE_{2n}}{(2n)!}x^{2n} \\
\arcsin x& = \sum_{n=0}^\infty \frac{(2n)!}{4^n(n!)^2(2n+1)}x^{2n+1} \\
\arccos x & = \frac{\pi}{2}-\arcsin x \\
\arctan x & = \sum_{n=0}\infty\frac{(-1)^n}{2n+1}x^{2n+1}.
\end{align}
$$
All angles are expressed in radians. The numbers $B_{k}$ are **Bernoulli
Numbers** and $E_{k}$ are **Euler Numbers**.

### 6. Hyperbolic Functions

The **hyperbolic functions** have Maclaurin series closely related to the
series for the corresponding trigonometric functions
$$
\begin{align}
\sinh x & = \sum_{n=0}^\infty\frac{x^{2n+1}}{(2n+1)!} \\
\cosh x & = \sum_{n=0}^\infty \frac{x^{2n}}{(2n)!} \\
\tanh x & = \sum_{n=1}^\infty\frac{B_{2n}4^n(4^n-1)}{(2n)!}x^{2n-1} \\
\text{arsinh} x & = \sum_{n=0}^\infty \frac{(-1)^n(2n)!}{4^n(n!)^2(2n+1)}x^{2n+1} \\
\text{arctanh} & = \sum_{n=0}^\infty \frac{x^{2n+1}}{2n+1}.
\end{align}
$$
