---
title: Tightness
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Tightness

**Tightness** (or being **bounded in probability** i.e. **stochastically
bounded**) is a property of sequences of distribution functions whereby the
[[limit-supremum-limit-infimum|limsup]] of the probability of the tails of the
sequence eventually vanish to zero.  

:::{.definition data-title="Tightness of Distribution Functions"}

A sequence of distribution functions is **tight** if
$$
\forall \varepsilon > 0,~\exists M_{\epsilon}>0: \limsup_{n \to \infty}\{ 1-F_{n}(M_{\varepsilon})+F_{n}(-M_{\varepsilon}) \}\leq  \varepsilon.
$$

:::

Notice that this is taking the limsup of
$\mathbb{P}(X_{n}\leq -M_{\varepsilon})+\mathbb{P}(X_{n}\geq M_{\epsilon})$ or
equivalently $\mathbb{P}(X_{n}\not\in[-M_{\varepsilon}, M_{\varepsilon}])$ so
proving that a sequence of distribution functions is tight means to show that
in the limit supremum, for some small $\varepsilon$ there is some interval
$[-M_{\varepsilon}, M_{\varepsilon}]$ such that the probability of $X_{n}$
falling within this interval is less than $\varepsilon$.

:::{.definition data-title="Equivalent Definition for Tightness of Distribution Functions"}

A sequence of distribution functions $\{ F_{n} \}$ is **tight** if for all
$\varepsilon >0$ there exists $M=M_\varepsilon>0$ such that
$$
\begin{align}& \forall n,~F_{n}([-M_{\varepsilon}, M_{\varepsilon}])>1-\varepsilon   \\ &\iff \inf_{n}F_{n}([-M_{\varepsilon}, M_{\varepsilon}])>1-\varepsilon  \\ &  \iff \sup_{n}F_{n}([-M_{\varepsilon},M_{\varepsilon}]^c)\leq  \varepsilon.\end{align}
$$

:::

### Tightness Results

:::{.theorem}

A sequence of distribution functions is tight if and only if every
sub-sequential limit is a distribution function.

:::

`\begin{proof}`

`\end{proof}`
Roughly, we have that [[convergence-in-law|weak convergence]] equals
[[vague-convergence|vague convergence]] plus **tightness**!

[[prohorovs-theorem]]

### Sufficient Conditions for Tightness

:::{.theorem data-title="Tightness Sufficient Condition I"}

Let $\{  X_{n} \}$ be r.v.s with d.f.s $\{  F_{n} \}$. If there exists
$\phi \geq 0$ such that $\phi(x)\uparrow \infty$ as
$\lvert x \rvert\uparrow \infty$ and
$C=\sup_{n}\mathbb{E}[\phi(X_{n})]<\infty$, then $\{  F_{n} \}$ is tight.

:::

Note that the most common criterion for tightness is for
$\phi(x)=\lvert x \rvert^r$, $r >0$.

:::{.theorem data-title="Tightness Sufficient Condition II"}

If there exists $r>0$ such that
$\limsup_{n}\mathbb{E}\lvert X_{n} \rvert^r<\infty$ then $\{ F_{n} \}$ is
tight.

:::

Note that it is therefore sufficient to show $L_{p}$ bounded. 
