---
title: Turlock Subbasin GSP Notes
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

# Turlock Subbasin GSP
###### Summary Notes
~~February 8th 2025~~
~~John Inston~~

## Water Budget Information

(pg 277)

Water budgets are generally provided for three interconnected systems that
define the overall hydrologic balance in the Turlock Subbasin, the land surface
system, the stream and river system, and the groundwater system.

Monthly water budgets are typically used to demonstrate variability in
agricultural water demand during the irrigation season, or monthly and seasonal
variability in surface water supply and groundwater pumping.  

Rainfall data is derived from the detailed dataset provided by the
Precipitation-Elevation Regressions on Independent Slopes Model (PRISM, 2010).
This data set is commonly used by the State DWR and other organizations for
mapping the spatial and temporal distribution of precipitation throughout the
state.

The DWR uses PRISM for the California Simulation of Evapotranspiration of
Applied Water (Cal-SIMETAW) model, a major source of calculation of ET of
applied water (ETAW) throughout the state. Identification of periods with
balance of wet and dry periods was performed by evaluating the cumulating
departure from mean precipitation.
[[dalystatisticaltopographicmodelmapping1994]]

**Add figure 5-2.**
<figcaption>Annual and cumulative departure from mean precipitation for the Turock Subbasin.</figcaption>

Water budgets were developed utlizing the C2VSimTM, a fully integrated surface
and groundwater flow model covering the entire Central Valley with refinements
focused on the Turlock, Modesto and Merced Subbasins. This version of the model
is based on the full C2VSimFG BETA2 model released by the DWR. The C2VSimTM, a
quasi-three-dimensional finite element model, was developed using the
Integrated Water Flow Model (IWFM) 2015 software package to simulate the
relevant hydrologic processes prevailing in the region.

<!-- TODO: image "Screenshot 2025-02-08 at 10.28.01 PM.png" not found in vault -->

- [Presentation](https://www.cwemf.org/workshops/C2VSimWrkshp/C2VSimWrkshpIntro.pdf)
- [[c2vsimfg-version1-01-release-notes-pdf]]
-  [C2vsimfg link](https://data.cnra.ca.gov/dataset/c2vsimfg)
- 

The C2VSimTM integrates the groundwater aquifer with the surface hydrologic
system and land surface processes and operations. The C2VSimTM integrates the
groundwater aquifer with the surface hydrologic system and land surface
processes and operations. Using data from federal, state, and local resources,
the C2VSimTM was calibrated for the hydrologic period of October 1991 to
September 2015 by comparing simulated evapotranspiration, groundwater levels,
and streamflow records with historical observed records. Development of the
model involved the study and analyses of hydrogeologic conditions, agricultural
and urban water demands, agricultural and urban water supplies, and an
evaluation of regional water quality conditions.

### Stream System

The primary components of the stream system are:

- Inflows:
	- Stream inflows into the Tuolumne River and Merced River at the boundary of
   the model and San Joaquin River inflows at the confluence of the Merced and
   San Joaquin River (bounding the Turlock Subbasin)
	- Tributary inflows from surface water contributions from small watersheds
   above the Subbasin
	- Operational outflow from the Turlock and Merced Irrigation District
   conveyance network to the stream system
	- Stream gain from the groundwater system
	- Surface runoff from precipitation to the stream system. Runoff is equal to
   precipitation minus infiltration
	- Return flow of applied water to the stream system.
- **Outflows:**
	- San Joaquin River outflows after the confluence with the Tuolumne River
	- Diverted surface water into canal distribution systems
	- Stream seepage to groundwater system
	- Native & riparian uptake from streams which is evapotranspiration from
   native vegetation along the riverbank

As the stream system includes the rivers bordering the Turlock Subbasin,
including their inflows, outflows, and interactions with neighboring Subbasins,
the stream system water budget is only presented at a Subbasin scale.

### Land Surface System

The primary components of the land surface system are:

- Supplies:
	- Precipitation
	- Surface water supplies
	- Groundwater supplies
	- Native and riparian uptake from streams which is evapotranspiration from
   native vegetation along the riverbank
- Demands:
	- Evapotranspiration
	- Surface runoff from precipitation to the stream system. Runoff is equal to
   precipitation minus infiltration.
	- Return flow from applied water to the stream system. Return flow is applied
   water that is not taken up by crops, percolated, or stored in the root zone
   system and flows to the stream system.
	- Percolation of water from the root zone to the groundwater system.
   Percolation in the urban areas is primarily due to the precipitation and
   applied water for outdoors water use, parks, cemeteries, and other open
   areas within the urban sphere of influence. Percolation from other sources
   such as rock wells, retention basins, and underground storage tanks are
   estimated based on the available data for each municipality.
	- Land surface system balance

### Groundwater System

The primary components of the groundwater system are:

- Inflows:
	- Deep percolation of water from the root zone/unsaturated zone to the
   aquifer.
	- Stream seepage from the Tuolumne, Merced, and San Joaquin River systems.
	- Subsurface inflow from neighboring subbasins and the foothills.
- Outflows:
	- Groundwater discharge to stream system.
	- Groundwater production (pumping) by private wells for agriculture, by TID
   for agricultural delivery and drainage, and by municipal and private
   domestic wells for urban/residential water supply.
	- Subsurface outflow to neighboring subbasins.
- Change in groundwater storage. A negative value represents depletion of the
  groundwater storage.

<!-- TODO: image "Screenshot 2025-02-08 at 8.13.46 PM.png" not found in vault -->
<figcaption>Annual Water Budget - Groundwater System</figcaption>
