---
title: Uniform Integrability
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Uniform Integrability
**Uniform integrability** is a compactness type concept for families of random
variables, not unlike that of [[tightness|tightness]]. Uniform integrability is
an extension to the notion of a family of functions being dominated in $L_{1}$
which is central in [[dominated-convergence-theorem|dominated convergence]].

 > [!definition] Uniform Integrability
> Given an arbitrary set $\mathcal{T}$,  a family $\{ X_{t},~t \in\mathcal{T} \}$ of random variables is **uniformly integrable** if $$\lim_{x \to \infty}\sup_{t \in\mathcal{T}}\mathbb{E}[|X_{t}|\cdot \mathbb{1}_{|X_{t}|\geq x}]=0.$$

*Recall: We say that $X$ is integrable if and only if $\mathbb{E}|X|<\infty$ or
equivalently, if and only if
$\mathbb{E}[\lvert X_{n} \rvert\mathbb{1}_{\{ \lvert  X_{n}\geq M \rvert \}}]\to 0$
as $M \to \infty$.*

We often discuss the case $\mathcal{T}:=\mathbb{N}_{0}$ and we may define it
for an arbitrary index set.

*Remark:* It follows from the
[[dominated-convergence-theorem|dominated convergence theorem]] that
$$
\lim_{x \to \infty}\mathbb{E}[|X_{t}|\mathbb{1}_{|X_{t}|\geq  x}]=0\quad\iff X_{t}\in L^1,
$$
i.e. that for integrable random variables, far tails contribute little to the
expectation. Uniformly integrable families are simply those for which the size
of this contribution can be controlled uniformly over all elements.

### Sufficient Conditions for Uniform Integrability

:::{.theorem data-title="Uniform Integrability Sufficient Conditions"}

The following are **sufficient conditions for uniform integrability** of
$(X_{n})$:

1.  If for all $n$, $|X_{n}|\leq Y$ for some integrable RV $Y$ (i.e.
    $\mathbb{E}|Y|<\infty$), then the sequence $(X_{n})$ is uniform integrable.
   
2. Let $\phi \geq 0$ be any non-negative function on $[0,\infty)$ such that
   $\frac{\phi(x)}{x}\nearrow \infty$ as $x \to \infty$. If for all $n$,
   $\mathbb{E}[\phi(|X_{n}|)]\leq C$ for some $C>0$, then sequence $(X_{n})$ is
   uniformly integrable.
   
3. Suppose there exists $\delta>0$ such that
   $sup_{n}\mathbb{E}|X_{n}|^{1+\delta}<\infty$, then the sequence $(X_{n})$ is
   uniformly integrable.

:::

`\begin{proof}`
See
[[files-notes-pstat213bc-lecture-notes-raya-pdf|Raya Feldman's PSTAT213BC Lecture Notes]].`\end{proof}`

The conditions above are sufficient but the lemma below gives the necessary and
sufficient conditions for uniform integrability.

:::{.theorem data-title="Uniform Integrability Necessary and Sufficient Conditions"}

The sequence $(X_{n})$ is **uniformly integrable** if and only if the following
two conditions hold:
1. $\sup_{n}\mathbb{E}[|X_{n}|]<\infty$; and
2. $\forall\varepsilon>0,~\exists \delta>0~s.t.\forall n,~\mathbb{E}[|X_{n}|\mathbb{1}_{A}]<\varepsilon$
   for any event $A$ such that $\mathbb{P}(A)<\delta$.

:::

`\begin{proof}`
See
[[files-notes-pstat213bc-lecture-notes-raya-pdf|Raya Feldman's PSTAT213BC Lecture Notes]].`\end{proof}`

The interpretation of this result is that the sequence $(X_{n})$ is uniformly
integrable iff and only if its first moments are uniformly bounded and
$X_{n}$'s cannot take large values on sets of small probability.

### Uniform Integrability Results

:::{.theorem data-title="Equivalence of convergence in $\mathbb{P}$ and in $L_1$ under uniform integrability"}

For $p>0$ assume that $X_n \in L^p$, $n \geq 1$ and
$X_{n}\stackrel{\mathbb{P}}{\to} X$. The following three statements are
equivalent:
1. $\{ |X_{n}|^p,~n\geq 1 \}$ is uniformly integrable;
2. $X_{n}\stackrel{L^p}{\to}X$ and $X\in L^p$; and
3. $\lim_{n \to \infty}\mathbb{E}[|X_{n}|^p]=\mathbb{E}[|X|^p]<\infty$.

:::

### Uniform Integrability Examples





##### Resources
1. Lecture 12: Uniform Integrability, Gordan Zitkovic, Fall 2015 -
   [[uniform-integrability-zitkovic-2015-pdf]].
2. Uniform Integrability, Karl Sigman 2009 - [[uniform-integrability-pdf]]