---
title: University (Old)
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Key Areas
- [[question-bank]]
- [[article-library]]
### Classes
#### Mathematics

- [[math201-real-analysis]]

#### Statistics

- [[pstat8-mathematical-proof]]
- [[pstat10-introduction-to-data-science]]

- [[pstat207-statistical-theory]]
- [[pstat210-measure-theory]]
- [[pstat213-probability-theory]]
- [[pstat215-bayesian-inference]]
- PSTAT220 Advanced Statistical Methods
- PSTAT223 Financial Models
- [[pstat222-computational-finance]]
- PSTAT231 Machine Learning
- PSTAT274 Time Series Analysis
- PSTAT275 Survival Analysis
- PSTAT277 Advanced Time Series

#### Environmental Science

- [[esm226-groundwater-management]]
#### 2024
- **Fall 2024**
	- [[math118-real-analysis]]
	- [[math201a-real-analysis]]
	- [[pstat274-time-series-analysis]]
- **Summer 2024**
	- [[pstat10-introduction-to-data-science]]
- **Spring 2024**
	- [[pstat221c-blockastics]]
	- [[pstat223c-energy-finance-hf-trading]]
	- [[pstat220c-advanced-statistical-methods]]
	- [[pstat213-qualifying-exam-preparation]]
	- [[pstat175-survival-analysis]]
- **Winter 2024**
	- [[pstat220b-advanced-statistical-methods]]
	- [[pstat223b-financial-models]]
	- [[pstat215a-bayesian-inference]]
	- [[pstat274-time-series-analysis]]
	- [[pstat171-mathematics-of-fixed-income-market]]
##### 2023
- **Fall 2023**
	- [[pstat223a-stochastic-calculus]]
	- PSTAT220A Advanced Statistical Methods
	- MATH201A Real Analysis
- **Summer 2023**
- **Spring 2023**
	- PSTAT207C Statistical Theory
	- [[pstat213-qualifying-exam-preparation]]

