---
title: Upcrossings
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Upcrossings

Let $(y_{n})$ be a sequence of real numbers and fix a finite interval $[a,b]$.
We define
$$
T_{1}=\min\{ n:y_{n}\leq a \}\quad \& \quad T_{2}=\min\{ n > T_{1}:y_{n}\geq b \}.
$$
The interval $[T_{1}, T_{2}]$ is called an **upcrossing** of $[a,b]$.  

For $k\geq 2$ we define
$$
T_{2k-1}=\min\{ n>T_{2k-2}:y_{n}\leq a \}\quad\&\quad T_{2k}=\min\{ n>T_{2k-1}:y_{n}\geq b \}.
$$

The **number of upcrossings** of $[a,b]$ be the finite sequence
$(y_{0}, \dots, y_{n})$ is denoted $U_{n}(a,b;y)$. The **total number of
upcrossings** of $[a,b]$ or the infinite sequence $y_n$ is defined as
$$
U(a,b;y):=\lim_{ n \to \infty } U_{n}(a,b;y).
$$
Clearly one can define **downcrossings** similarly by reversing the
inequalities and flipping $a$ and $b$
$$
T_{1}=\min\{ n:y_{n}\geq b \}\quad \& \quad T_{2}=\min\{ n > T_{1}:y_{n}\leq a \}.
$$

:::{.theorem data-title="Upcrossings and Convergence"}

If a sequence of real numbers $(y_{n})$ diverges, then there exists
$a<b\in \mathbb{Q}$ s.t. $U(a,b;y)=\infty$.

:::

`\begin{proof}`
If a sequence $\{  y_{n} \}$ diverges, then there exist rational numbers $a<b$
and subsequences $\{  y_{n_{k}} \}$ and $\{ y_{m_{l}} \}$ such that
$\lim_{ k \to \infty }y_{n_{k}}<a<b<\lim_{ l \to \infty }y_{m_{l}}$. Then
$y_{n}\leq a$ for infinitely many indices $n$ and $y_{n}\geq b$ for infinitely
many indices $n$, that is $(y_{n})$ will cross the interval $[a,b]$ infinitely
many times $U(a,b;y)=\infty$.`\end{proof}`

