---
title: Vector Space (Linear Space)
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Vector Space Axioms

In mathematics and physics, [[vector|vector]] is a term that refers informally
to some quantities that **cannot be expressed by a single** number (a scalar),
or to elements of some vector spaces.

Given some [[field|field]] $F$ we can define a **vector space** (also known as
a **linear space**) which is a collection of vectors with elements from field
$F$ that satisfies the vector space axioms.

| Axiom                                                                   | Statement                                                                                                                                            |
| ----------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Associativity** of vector addition                                    | **u** + (**v** + **w**) = (**u** + **v**) + **w**                                                                                                    |
| **Commutativity** of vector addition                                    | **u** + **v** = **v** + **u**                                                                                                                        |
| **Identity element** of vector addition                                 | There exists an element **0** ∈ _V_, called the zero vector, such that **v** + **0** = **v** for all **v** ∈ _V_.                                    |
| **Inverse elements** of vector addition                                 | For every $\vec{v} \in \mathcal{V}$, there exists an element −**v** ∈ _V_, called the additive inverse of **v**, such that **v** + (−**v**) = **0**. |
| Compatibility of scalar multiplication with field multiplication        | $a(b \vec{v}) = (ab)\vec{v}$                                                                                                                         |
| Identity element of scalar multiplication                               | $1\vec{v}=\vec{v}$, where 1 denotes the multiplicative identity in F.                                                                                |
| Distributivity of scalar multiplication with respect to vector addition | _a_(**u** + **v**) = _a_**u** + _a_**v**                                                                                                             |
| Distributivity of scalar multiplication with respect to field addition  | (_a_ + _b_)**v** = _a_**v** + _b_**v**                                                                                                               |
### Properties of Vector Spaces

:::{.theorem data-title="Linear Vector Space"}

A [[vector-space-linear-space|vector space]] $(\mathcal{V}, F)$ is **linear**,
that is for all $v_{1}, v_{2} \in \mathcal{V}$ and $\alpha,\beta \in F$, the
linear combination
$$
\alpha v_{1}+\beta v_{2}\in\mathcal{V}.
$$

:::

