---
title: Volatility Models
author: John Robin Inston
date: 2026-09-25
number-sections: true
title-block-banner: true
---

### Motivation

The implied volatility curve is symmetric before 1987, i.e. the slope of the
cure $K\mapsto I(T,K)$ is close to zero at $K=S_{0}$ (at-the-money) but it
became asymmetric after 1987, i.e. the slope of the curve is negative at
$K=S_0$.

Empirical observation from the stock market implies that the implied volatility
based on options with time to maturity $T$ and strike $K$ denoted $I(T,K)$ is
not flat in both $T$ and $K$. Naturally, the [[geometric-brownian-motion]] of
the [[black-scholes-merton-model]] is not a good model for stock price since it
assumes constant volatility $\sigma$.

As a result, changes are made to the Black-Scholes Model in primarily two
directions, introducing jumps in the stock price or to change the volatility
setting.

### Areas

- Constant Volatility ([[black-scholes-merton-model]])
- [[time-dependent-volatility-model]]
- [[local-volatility-model]]
- [[stochastic-volatility-model]]
- Uncertain Volatility
- Fractional Brownian Motion Volatility Models