---
title: Fundamentals of option pricing under Black-Scholes model
subtitle: Financial Mathematics
author: John Robin Inston
date: "2025-11-20"
categories: [Stochastic Calculus, Derivatives Pricing, Financial Mathematics]
toc: true
draft: true
date-modified: "2025-11-21"
title-block-banner: true
---

## Introduction

This is the first post in our series discussing topics in _mathematical finance_.  In this note we discuss the fundamentals of pricing financial derivatives using stochastic and partial differential equations.  We begin by discussing both the PDE approach and the risk-neutral pricing approach for 

We first introduce the problem of pricing simple European options, specifically deriving the pricing formula for European call options on a stock with dynamics given by the Black-Scholes model.  We will then construct a real world example, estimating model parameters using historical stock prices and a theoretical option.  

## Problem Outline

The [Black-Scholes-Merton model](https://en.wikipedia.org/wiki/Black–Scholes_model) is a mathematical model for financial markets whereby one assumes that the price of a stock $(S_t)$ follows _Geometric Brownian Motion (GBM)_
$$
dS_t = \mu S_t dt + \sigma S_t dW_t, 
$$

with drift term $\mu$ and diffusion term $\sigma$ and where $(W_t)$ is Brownian motion.  Now consider a European call option on this stock which is a financial contract giving the holding the option but not the obligation to buy the underlying stock at a future time $T$ (the _maturity_) for prespecified price $K$ (the _strike_).  

::: callout-note
## Definition (Black-Scholes Formula)
For a European call option with maturity $T$ and strike price $K$ the option price at time $t_0$ is given by
$$
C
$$
:::
