---
title: Neural Networks with PyTorch
author: John Robin Inston
date: today
categories: [Python, Machine Learning, PyTorch]
draft: true
toc: true
jupyter: python3
---

In this note we investigate how to implement neural networks in python using 'PyTorch' for recognizing handwritten digits using the MNIST dataset.  We shall be following the guide [MNIST Handwritten Digit Recognition in PyTorch](https://nextjournal.com/gkoehler/pytorch-mnist) provided by [Gregor Koehler](https://nextjournal.com/gkoehler) in his article on [Nextjournal](https://nextjournal.com/home).

## Background

```{python}
# Packages
import numpy
import torch
import torchvision
```

## Data

We begin by defining the hyperparameters we will be using for the experiment.  The **number of epochs** defines how many times we will loop over the complete training data, while `learning rate` and `momentum` are hyperparametersfor the optimizer we plan on implementing.

```{python}
n_epochs = 3
batch_size_train = 64
batch_size_test = 1000
learning_rate = 0.01
momentum = 0.5
log_interval = 10

random_seed = 1
torch.backends.cudnn.enabled = False
torch.manual_seed(random_seed)
```

We note that cuDNN uses nondeterministic algorithms which we disable by setting `torch.backends.cudnn.enabled = False`.  TorchVision offers useful transformations such as cropping or normalization.

```{python}
train_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('posts/deep-learning-torch-mnist/static/data', train=True, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_train, shuffle=True)

test_loader = torch.utils.data.DataLoader(
  torchvision.datasets.MNIST('posts/deep-learning-torch-mnist/static/data', train=False, download=True,
                             transform=torchvision.transforms.Compose([
                               torchvision.transforms.ToTensor(),
                               torchvision.transforms.Normalize(
                                 (0.1307,), (0.3081,))
                             ])),
  batch_size=batch_size_test, shuffle=True)
```

```{python}
examples = enumerate(test_loader)
batch_idx, (example_data, example_targets) = next(examples)
```