---
title: "PSTAT100 Data Science and Analysis"
subtitle: "Lecture Notes"
author: "John Robin Inston"
date: "2026-03-16"
date-modified: "2026-03-16"
toc: true
title-block-banner: false
sidebar: pstat100-notes
page-navigation: true
---

## Introduction

These are my online lecture notes for the PSTAT100 Data Science and Analysis course taught at UC Santa Barbara. In these lecture notes we study fundamental topics in data science and the tools we use for data retrieval, analysis, visualization, and reproducible research in preparation for advanced data science courses.

Throughout these notes we will conduct our data analysis using the programming language `python`.  It is assumed throughout this course that you have had some experience working in `python` or a similar programming language such as `R`.  You may use the **Integrated Development Environment (IDE)** of your choice but my recommendation would be to use **VSCode** or some branch of the repository such as **Positron** or **Cursor**.  If you are unfamiliar with `python` and require some help with setup I have included some guidance in the preliminary materials.

## Contents

- **Preliminary Material:**
    - [Getting Started with Python](../00.1-python-installation-guide/index.qmd)
    - [Python Fundamentals](../00.2-python-fundamentals/index.qmd)
    - [Linear Algebra](../00.3-linear-algebra/index.qmd)
- **Introduction:**
  - [Data Science Fundamentals](../01-data-science-fundamentals/index.qmd)
  - [Data Structure](../02-data-structure/index.qmd)
- **Data Exploration:**
  - [Data Preparation](../03-data-preparation/index.qmd)
  - [Visualization](../04-visualization/index.qmd)
  - [Exploratory Data Analysis](../05-eda/index.qmd)
- **Probability and Statistics:**
  - [Probability Theory Fundamentals](../06-probability/index.qmd)
  - [Statistics](../07-statistics/index.qmd)
- **Statistical Models:**
    - [Simple Linear Regression](../08-slr/index.qmd)
    - [Multiple Linear Regression](../09-mlr/index.qmd)
    - [Generalized Linear Models](../10-glm/index.qmd)
      - [Logistic Regression](../10.1-logistic-regression/index.qmd)
      - [Poisson Regression](../10.2-poisson-regression/index.qmd)
    - [Model Selection](../11-model-selection/index.qmd)
      - [Regularization](../12-regularization/index.qmd)
- **Machine Learning Models:**
  - [Decision Trees](../13-classification/index.qmd)
  - [Random Forests](../13-classification//index.qmd)
