---
title: "Forecasting historical atmospheric carbon dioxide levels above Mauna Loa, Hawaii using the SARIMA model family."
author: "John Robin Inston"
date: "2023-06-17"
categories: [Atmospheric Modelling, Time Series, Statistics, R, SARIMA]
toc: true
---

**Abstract:**

In this report we aim to select and fit an appropriate Seasonal Autoregressive Integrated Moving Average (SARIMA) model in order to produce accuruate five year ahead forecasts of atmospheric CO2 levels above Mauna Loa, Hawaii. We investigate the underlying properties of the time series data, the suitability of SARIMA models, and whether the forecasts they produce accurately capture future observations. Throughout the project we implement various univariate time series analysis techniques including exploratory analysis, model selection procedures based on the adjusted Akaike Information Criteria, diagnostic checking, residual analysis and spectral analysis. Our first choice $\text{SARIMA}(0,1,3)(0,1,1)_{12}$ model performed well, producing approximately Gaussian WN residuals and accurate forecasts with confidence intervals capturing the true observed future values of the time series.

## Introduction


