---
title: 
  "**PSTAT170** Introduction to Mathematical Finance"
subtitle: Summer 2026
author: "John Robin Inston"
image: "assets/pstat188-thumbnail.svg"
date: "2026-09-27"
toc: true
title-block-banner: false
categories: [Current, UCSB, Finance, Math]

about:
  template: trestles
  image-width: 16em
  image-shape: rounded
  id: hero-heading

---

::: {#hero-heading}
<div class="h1">Welcome to PSTAT10!</div>

My name is [John Inston](about.qmd) and I am a 5th year Ph.D. candidate in 
the Department of Statistics and Applied Probability here at UC Santa Barbara.
I am the teaching assistant, alongside my collegue Ka Lok Lam, assisting 
[Prof. Tomoyuki Ichiba]() in holding the PSTAT170 Introduction to 
Mathematical Finance course this summer.  

Throughout this course you will be introduced to the mathematical methods 
used in finance for estimating and evaluating asset pricing models, 
equilibrium and derivative pricing, options, bonds, and the term-structure 
of interest rates.  You will also explore finance optimization models 
for risk management and financial engineering. 

#### 🔍 Reference Material

Any material provided on this website was authored by myself based on the 
course material, including the course textbook and lecture notes provided 
by Prof. Ichiba, or published with the express permission of the author. 
For specific section and assignment problem worksheets and solutions 
please refer to the course Canvas page.

:::

## 📚 Material

## ✏️ Topics




