---
title: "Data Science with R"
author: "John Robin Inston"
date: "2025-01-21"
categories: [Data Science, R]
toc: true
date-modified: "2025-05-30"
title-block-banner: true
---

```{r}
#| echo: false
#| message: false
#| fig-width: 12
#| fig-height: 7
 
library(tidyverse)

mtcars |>
    ggplot(aes(x = mpg, y = hp)) +
    geom_point(aes(colour = as.factor(cyl), shape = as.factor(cyl))) +
    geom_smooth() +
    labs(
        y = "Horse Power",
        x = "Miles per Gallon",
        shape = "Cylinders",
        color = "Cylinders"
    ) +
    theme_light() +
    theme(legend.position = "bottom")
```

## ✏️ Information

Welcome to **Data Science with R**, a course providing an introduction on how to use the programming language `R` for data science and statistical modelling.

The aim of this course is to provide a thorough introduction to programming in R for individuals who may have never written or utilized a programming language before.  First we outline how to install `R` on our operating system, how to download and use an Interactive Development Environment (IDE) such as `RStudio`, `Positron` or `VSCode`, and how to install packages on our system.  We will then explore various ways to explore, manage and analyze data using both the in-built functionality in `R` as well as available libraries such as `tidyverse`.

## ✍️ Topics

This course is based fundamentally on the PSTAT10 Data Science Principles class I have taught in the past at UCSB.  The course is split into the following topics:

1. [Installing and using R and RStudio](/posts/rds1-installation/index.qmd).

2. [R Basics I - Operators, Logic & Data Types](/posts/rds2-basics1-operators/index.qmd).

3. [R Basics II - Atomic Data Structures](/posts/rds3-basics2-atomicdata/index.qmd).

4. [R Basics III - Dataframes and Lists](/posts/rds4-basics3-dataframes/index.qmd)

5. R Basics IV - Functions

6. R Basics V - Looping and Branching

7. [Fundamentals of Probability Theory](/posts/rds5-probability-basics/index.qmd).

8. Basic Simulation with R.

9. Data Handling with the `tidyverse` package.

10. Plotting with `ggplot2`.

11. SQL Basics.

12. SQL Aggregation and Joins.


## 📚 Materials

Each topic links to a website post with the relevant material.  A pdf copy of the combined course notes can be downloaded here.  Furthermore, each wesite post links to the corresponding youtube video going through the material.

For this course you will need to download the language R, your chosen IDE and Quarto using the following links:

- [Link to download R & RStudio](https://posit.co/download/rstudio-desktop/)

- [Link to download Quarto](https://quarto.org/docs/get-started/)

Some helpful resources and additional guides and linked below:

- [Documentation: Quarto for PDF documents](https://quarto.org/docs/output-formats/pdf-basics.html)

- [Documentation: Writing maths using LaTeX](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

- [Documentation: Plotting with `ggplot`](https://ggplot2-book.org/)

If you found any of this material helpful consider buying me a coffee but only if you can afford to!  Thank you for visiting this course page. 😊

<div style="text-align: center;">
  <script type="text/javascript" 
          src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" 
          data-name="bmc-button" 
          data-slug="johnrobininston" 
          data-color="#FF5F5F" 
          data-emoji="" 
          data-font="Cookie" 
          data-text="Buy me a coffee! " 
          data-outline-color="#000000" 
          data-font-color="#ffffff" 
          data-coffee-color="#FFDD00">
  </script>
</div>







